/* Generated by native.c11; do not edit. */
#ifndef NATIVE_MODULE_0_ABI_H
#define NATIVE_MODULE_0_ABI_H

#include "native_shim.h"

typedef int64_t native_m0_type_0;
_Static_assert(sizeof(native_m0_type_0) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_0) == 8, "layout alignment");

typedef struct native_m0_type_1 {
  native_m0_type_0 field_0;
  native_m0_type_0 field_1;
} native_m0_type_1;
_Static_assert(sizeof(native_m0_type_1) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_1) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_1, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_1, field_1) == 8, "field offset");

native_m0_type_0 native_m0_fn_0(native_arena *arena, const native_capability *capability, native_m0_type_0 native_v_0, native_m0_type_0 native_v_1);

#endif
