// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub fn mapAbort(xs: []const i64) []const i64 {
    return blk1: { const __src = xs; const __out = rt.cliAlloc().alloc(i64, __src.len) catch @panic("oom"); for (__src, 0..) |x, __i| { __out[__i] = (x + 1); } break :blk1 __out; };
}

pub fn mapFallible(ctx: *rt.Ctx, xs: []const i64) std.mem.Allocator.Error![]const i64 {
    return blk1: { const __src = xs; const __out = try ctx.tick.alloc(i64, __src.len); for (__src, 0..) |x, __i| { __out[__i] = (x + 1); } break :blk1 __out; };
}

pub fn stringAbort(left: []const u8, right: []const u8) []const u8 {
    return rt.str2(rt.str1(left), rt.str1(right));
}
