// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub const Dyn0Tag = enum(u16) {
    string = 0,
    int = 1,
    boolean = 2,
    vec_string = 3,
    map_string_int = 4,
};
pub const Dyn0 = union(Dyn0Tag) {
    string: []const u8,
    int: i64,
    boolean: bool,
    vec_string: []const []const u8,
    map_string_int: rt.Map(i64),
};

pub fn dynString(value: []const u8) Dyn0 {
    return Dyn0{ .string = value };
}

pub fn dynInt(value: i64) Dyn0 {
    return Dyn0{ .int = value };
}

pub fn dynBool(value: bool) Dyn0 {
    return Dyn0{ .boolean = value };
}

pub fn dynVector(value: []const []const u8) Dyn0 {
    return Dyn0{ .vec_string = value };
}

pub fn dynMap(value: rt.Map(i64)) Dyn0 {
    return Dyn0{ .map_string_int = value };
}

pub fn roundTrip(value: Dyn0) Dyn0 {
    return value;
}

pub fn observe(__ctx: *rt.Ctx, value: Dyn0) []const u8 {
    return (if ((std.meta.activeTag(value) == .string)) rt.str2(__ctx.tick, rt.str1(__ctx.tick, "string:"), rt.str1(__ctx.tick, value.string)) else (if ((std.meta.activeTag(value) == .int)) rt.str2(__ctx.tick, rt.str1(__ctx.tick, "int:"), rt.str1(__ctx.tick, value.int)) else (if ((std.meta.activeTag(value) == .boolean)) rt.str2(__ctx.tick, rt.str1(__ctx.tick, "bool:"), rt.str1(__ctx.tick, value.boolean)) else (if ((std.meta.activeTag(value) == .vec_string)) rt.str2(__ctx.tick, rt.str1(__ctx.tick, "vec:"), rt.str1(__ctx.tick, rt.count(value.vec_string))) else (if ((std.meta.activeTag(value) == .map_string_int)) "map" else "unreachable")))));
}
