// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub fn keywordMapCount() i64 {
    const values = rt.ValueMap(rt.Keyword, i64).empty().assoc(rt.keyword("", "alpha"), 1).assoc(rt.keyword("beagle", "beta"), 2);
    return rt.count(values);
}

pub fn keywordMapAbsent() bool {
    const values = rt.ValueMap(rt.Keyword, i64).empty().assoc(rt.keyword("", "alpha"), 1);
    return (!values.contains(rt.keyword("", "missing")));
}

pub fn compoundMapPresent() bool {
    const needle = &.{ 1, 2 };
    const values = rt.ValueMap([]const i64, []const u8).empty().assoc(&.{ 1, 2 }, "pair");
    return values.contains(needle);
}

pub fn setDedupCount() i64 {
    const values = rt.ValueSet([]const i64).empty().conj(&.{ 1, 2 }).conj(&.{ (0 + 1), 2 }).conj(&.{ 2, 3 });
    return rt.count(values);
}

pub fn setPresent() bool {
    const needle = &.{ 1, 2 };
    const values = rt.ValueSet([]const i64).empty().conj(&.{ 1, 2 }).conj(&.{ 2, 3 });
    return values.contains(needle);
}

pub fn compoundEqual() bool {
    const left = &.{ &.{ 1, 2 }, &.{ 3 } };
    const right = &.{ &.{ 1, 2 }, &.{ 3 } };
    return rt.eq(left, right);
}

pub fn compoundHashConsistent() bool {
    const left = &.{ &.{ 1, 2 }, &.{ 3 } };
    const right = &.{ &.{ 1, 2 }, &.{ 3 } };
    return rt.eq(rt.hash(left), rt.hash(right));
}

pub fn keywordDistinctFromString() bool {
    return (!rt.eq(rt.keyword("", "alpha"), "alpha"));
}
