// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub fn keySetMatches(__ctx: *rt.Ctx, record: rt.ValueMap(rt.Keyword, i64)) bool {
    const expected = rt.ValueSet(rt.Keyword).empty().conj(__ctx.tick, rt.keyword("", "alpha")).conj(__ctx.tick, rt.keyword("", "beta"));
    return rt.eq(expected, record.keySet(__ctx.tick));
}

pub fn keyCount(__ctx: *rt.Ctx, record: rt.ValueMap(rt.Keyword, i64)) i64 {
    _ = __ctx;
    return rt.count(record);
}

pub fn valuesEmpty(__ctx: *rt.Ctx, record: rt.ValueMap(rt.Keyword, i64)) bool {
    _ = __ctx;
    return rt.is_empty(record);
}

pub fn keyPresent(__ctx: *rt.Ctx, record: rt.ValueMap(rt.Keyword, i64)) bool {
    return record.keySet(__ctx.tick).contains(rt.keyword("", "alpha"));
}
