// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub const RewriteCrash = struct {
    message: []const u8,
    path: []const u8,
    refusal: bool,
};

pub const RewriteCrashErrorPayload = union(enum) {
    rewrite_crash: RewriteCrash,
};

pub const RewriteCrashErrorCarrier = struct {
    payload: ?RewriteCrashErrorPayload = null,
};

pub const RewriteCrashError = error{
    RewriteCrash,
};

pub fn classifyRewriteCrash(__errors: *RewriteCrashErrorCarrier, coord: []const u8, live_ino: ?i64, old_ino: ?i64, new_ino: ?i64, old_bytes: ?i64, old_sha: ?[]const u8, new_sha1: ?[]const u8, live_line1_sha: ?[]const u8, live_prefix_sha: ?[]const u8) (std.mem.Allocator.Error || RewriteCrashError)!rt.Keyword {
    return (if ((live_ino == null)) blk1: { __errors.payload = .{ .rewrite_crash = RewriteCrash{ .message = try rt.str2Alloc(rt.cliAlloc(), try rt.str2Alloc(rt.cliAlloc(), try rt.str2Alloc(rt.cliAlloc(), "rewrite intent present but ", coord), " does not exist — refusing to classify"), ""), .path = coord, .refusal = true } }; break :blk1 error.RewriteCrash; } else if (((old_ino != null) and rt.eq(live_ino, old_ino))) rt.keyword("", "roll-back") else if (((new_ino != null) and rt.eq(live_ino, new_ino))) rt.keyword("", "roll-forward") else if (((new_sha1 != null) and rt.eq(new_sha1, live_line1_sha))) rt.keyword("", "roll-forward") else if (((old_bytes != null) and (old_sha != null) and rt.eq(old_sha, live_prefix_sha))) rt.keyword("", "roll-back") else blk2: { __errors.payload = .{ .rewrite_crash = RewriteCrash{ .message = try rt.str2Alloc(rt.cliAlloc(), try rt.str2Alloc(rt.cliAlloc(), "rewrite intent does not match the live corpus at ", coord), " (neither source nor replacement inode/sha) — refusing to classify; operator intervention required"), .path = coord, .refusal = true } }; break :blk2 error.RewriteCrash; });
}
