// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub const Cell = struct {
    value: i64,
};

pub const World = struct {
    cell: Cell,
    score: i64,
};

pub fn borrowedScore(world: World) i64 {
    return world.score;
}

pub fn worldTick(ctx: *rt.Ctx, world: World) World {
    _ = ctx;
    return World{ .cell = Cell{ .value = (world.cell.value + 1) }, .score = (borrowedScore(world) + 1) };
}

pub fn observe(ctx: *rt.Ctx) i64 {
    const next = worldTick(ctx, World{ .cell = Cell{ .value = 4 }, .score = 10 });
    return (next.cell.value + next.score);
}

/// Commit-boundary copy: world state leaves tick memory by
/// value (escape-checked slice-free in v1).
pub fn promote(v: World) World {
    return v;
}
