// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub const RewriteFailure = struct {
    message: []const u8,
    path: []const u8,
    refusal: bool,
};

pub const RewriteErrorPayload = union(enum) {
    rewrite_failure: RewriteFailure,
};

pub const RewriteErrorCarrier = struct {
    payload: ?RewriteErrorPayload = null,
};

pub const RewriteError = error{
    RewriteFailure,
};

pub fn classify(__errors: *RewriteErrorCarrier, missing: bool, path: []const u8) RewriteError![]const u8 {
    return if (missing) blk1: { __errors.payload = .{ .rewrite_failure = RewriteFailure{ .message = rt.str2(rt.str1("missing "), rt.str1(path)), .path = path, .refusal = true } }; break :blk1 error.RewriteFailure; } else "roll-back";
}

pub fn propagate(__errors: *RewriteErrorCarrier, missing: bool, path: []const u8) RewriteError![]const u8 {
    return try classify(__errors, missing, path);
}

pub fn render(missing: bool, path: []const u8) []const u8 {
    return blk1: { var __errors: RewriteErrorCarrier = .{}; const __value = classify(&__errors, missing, path) catch { const err = __errors.payload.?.rewrite_failure; break :blk1 err.message; }; break :blk1 __value; };
}
