#lang racket/base

;; CLJS-specific stdlib entries: ClojureScript/JavaScript interop.
;;
;; Split from stdlib-types.rkt. Merged into the unified STDLIB-TYPES at
;; require time; kept separate so the CLJ pipeline can exclude cleanly.

(require "types.rkt"
         "stdlib-helpers.rkt")

(define STDLIB-CLJS
  (hash
   ;; --- CLJS object interop -------------------------------------------------
   'js-obj         (fn-of '() 'Any #:rest 'Any)
   'js-keys        (fn-of '(Any) 'Any)
   'js-delete      (fn-of '(Any Any) 'Bool)
   'js-invoke      (fn-of '(Any Any) 'Any #:rest 'Any)
   'js-mod         (fn-of '(Int Int) 'Int)
   'js-debugger    (fn-of '() 'Nil)
   ;; --- CLJS type conversion -------------------------------------------------
   'js->clj        (fn-of '(Any) 'Any #:rest 'Any)
   'clj->js        (fn-of '(Any) 'Any #:rest 'Any)
   ;; --- CLJS type predicates -------------------------------------------------
   'undefined?     (fn-of '(Any) 'Bool)
   'object?        (fn-of '(Any) 'Bool)
   'array?         (fn-of '(Any) 'Bool)
   'js-symbol?     (fn-of '(Any) 'Bool)
   'iterable?      (fn-of '(Any) 'Bool)
   'cloneable?     (fn-of '(Any) 'Bool)
   ;; --- CLJS utilities -------------------------------------------------------
   'exists?        (fn-of '(Any) 'Bool)
   'specify!       (fn-of '(Any) 'Any #:rest 'Any)
   'specify        (fn-of '(Any) 'Any #:rest 'Any)
   'es6-iterator-seq  (fn-of '(Any) 'Any)
   'js-iterable->seq  (fn-of '(Any) 'Any)
   'array-seq      (fn-of '(Any) 'Any #:rest 'Int)
   'array-chunk    (fn-of '(Any) 'Any)
   'set-print-fn!      (fn-of '(Any) 'Nil)
   'set-print-err-fn!  (fn-of '(Any) 'Nil)
   ;; --- JS globals (ClojureScript) -------------------------------------------
   'js/parseInt       (fn-of '(Any) 'Int #:rest 'Any)
   'js/parseFloat     (fn-of '(String) 'Float)
   'js/isNaN          (fn-of '(Any) 'Bool)
   'js/isFinite       (fn-of '(Any) 'Bool)
   'js/encodeURI      (fn-of '(String) 'String)
   'js/decodeURI      (fn-of '(String) 'String)
   'js/encodeURIComponent (fn-of '(String) 'String)
   'js/decodeURIComponent (fn-of '(String) 'String)
   'js/Math.abs       (fn-of '(Any) 'Any)
   'js/Math.floor     (fn-of '(Float) 'Float)
   'js/Math.ceil      (fn-of '(Float) 'Float)
   'js/Math.round     (fn-of '(Float) 'Int)
   'js/Math.max       (fn-of '(Any Any) 'Any #:rest 'Any)
   'js/Math.min       (fn-of '(Any Any) 'Any #:rest 'Any)
   'js/Math.pow       (fn-of '(Float Float) 'Float)
   'js/Math.sqrt      (fn-of '(Float) 'Float)
   'js/Math.random    (fn-of '() 'Float)
   'js/Math.log       (fn-of '(Float) 'Float)
   'js/Math.sin       (fn-of '(Float) 'Float)
   'js/Math.cos       (fn-of '(Float) 'Float)
   'js/console.log    (fn-of '() 'Nil #:rest 'Any)
   'js/console.warn   (fn-of '() 'Nil #:rest 'Any)
   'js/console.error  (fn-of '() 'Nil #:rest 'Any)
   ;; --- JS constructors & static methods -------------------------------------
   'js/Date           (fn-of '() 'Any #:rest 'Any)
   'js/Date.now       (fn-of '() 'Int)
   'js/Promise         (fn-of '(Any) 'Any)
   'js/Error           (fn-of '(String) 'Any)
   'js/RegExp          (fn-of '(String) 'Any #:rest 'String)
   'js/Array.isArray   (fn-of '(Any) 'Bool)
   'js/Array.from      (fn-of '(Any) 'Any #:rest 'Any)
   'js/Object.keys     (fn-of '(Any) 'Any)
   'js/Object.values   (fn-of '(Any) 'Any)
   'js/Object.entries  (fn-of '(Any) 'Any)
   'js/Object.assign   (fn-of '(Any) 'Any #:rest 'Any)
   'js/Object.freeze   (fn-of '(Any) 'Any)
   'js/Object.create   (fn-of '(Any) 'Any #:rest 'Any)
   'js/JSON.stringify  (fn-of '(Any) 'String #:rest 'Any)
   'js/JSON.parse      (fn-of '(String) 'Any)
   'js/setTimeout      (fn-of '(Any Int) 'Int)
   'js/setInterval     (fn-of '(Any Int) 'Int)
   'js/clearTimeout    (fn-of '(Int) 'Nil)
   'js/clearInterval   (fn-of '(Int) 'Nil)
   ;; --- DOM ------------------------------------------------------------------
   'js/document.createElement    (fn-of '(String) 'Any)
   'js/document.getElementById   (fn-of '(String) 'Any)
   'js/document.querySelector    (fn-of '(String) 'Any)
   'js/document.querySelectorAll (fn-of '(String) 'Any)
   'js/document.createTextNode   (fn-of '(String) 'Any)
   'js/window.requestAnimationFrame (fn-of '(Any) 'Int)
   'js/window.cancelAnimationFrame  (fn-of '(Int) 'Nil)
   ;; --- BOM: window / location / history -----------------------------------
   'js/window.alert     (fn-of '(String) 'Nil)
   'js/window.confirm   (fn-of '(String) 'Bool)
   'js/window.prompt    (fn-of '(String) 'Any #:rest 'String)
   'js/window.open      (fn-of '(String) 'Any #:rest 'String)
   'js/window.close     (fn-of '() 'Nil)
   'js/window.scrollTo  (fn-of '(Int Int) 'Nil)
   'js/window.scrollBy  (fn-of '(Int Int) 'Nil)
   'js/window.location.href     (p 'String)
   'js/window.location.pathname (p 'String)
   'js/window.location.search   (p 'String)
   'js/window.location.hash     (p 'String)
   'js/window.location.host     (p 'String)
   'js/window.location.protocol (p 'String)
   'js/window.location.reload   (fn-of '() 'Nil)
   'js/window.location.replace  (fn-of '(String) 'Nil)
   'js/window.location.assign   (fn-of '(String) 'Nil)
   'js/window.history.back      (fn-of '() 'Nil)
   'js/window.history.forward   (fn-of '() 'Nil)
   'js/window.history.go        (fn-of '(Int) 'Nil)
   'js/window.history.pushState (fn-of '(Any String String) 'Nil)
   ;; --- Storage --------------------------------------------------------------
   'js/localStorage.getItem    (fn-of '(String) 'Any)
   'js/localStorage.setItem    (fn-of '(String String) 'Nil)
   'js/localStorage.removeItem (fn-of '(String) 'Nil)
   'js/localStorage.clear      (fn-of '() 'Nil)
   'js/localStorage.key        (fn-of '(Int) 'Any)
   'js/sessionStorage.getItem    (fn-of '(String) 'Any)
   'js/sessionStorage.setItem    (fn-of '(String String) 'Nil)
   'js/sessionStorage.removeItem (fn-of '(String) 'Nil)
   'js/sessionStorage.clear      (fn-of '() 'Nil)
   ;; --- Fetch / async --------------------------------------------------------
   ;; fetch returns a Promise<Response>; opts is optional init object
   'js/fetch                     (fn-of '(String) 'Any #:rest 'Any)
   'js/Promise.resolve           (fn-of '(Any) 'Any)
   'js/Promise.reject            (fn-of '(Any) 'Any)
   'js/Promise.all               (fn-of '(Any) 'Any)
   'js/Promise.race              (fn-of '(Any) 'Any)
   'js/Promise.allSettled        (fn-of '(Any) 'Any)
   ;; --- JS Math extras -------------------------------------------------------
   'js/Math.tan       (fn-of '(Float) 'Float)
   'js/Math.asin      (fn-of '(Float) 'Float)
   'js/Math.acos      (fn-of '(Float) 'Float)
   'js/Math.atan      (fn-of '(Float) 'Float)
   'js/Math.atan2     (fn-of '(Float Float) 'Float)
   'js/Math.exp       (fn-of '(Float) 'Float)
   'js/Math.log2      (fn-of '(Float) 'Float)
   'js/Math.log10     (fn-of '(Float) 'Float)
   'js/Math.sign      (fn-of '(Any) 'Int)
   'js/Math.trunc     (fn-of '(Float) 'Int)
   'js/Math.hypot     (fn-of '(Float Float) 'Float #:rest 'Float)
   'js/Math.PI        (p 'Float)
   'js/Math.E         (p 'Float)
   ;; --- JS Number / String statics ------------------------------------------
   'js/Number.parseInt          (fn-of '(Any) 'Int #:rest 'Any)
   'js/Number.parseFloat        (fn-of '(Any) 'Float)
   'js/Number.isInteger         (fn-of '(Any) 'Bool)
   'js/Number.isFinite          (fn-of '(Any) 'Bool)
   'js/Number.isNaN             (fn-of '(Any) 'Bool)
   'js/Number.MAX_SAFE_INTEGER  (p 'Int)
   'js/Number.MIN_SAFE_INTEGER  (p 'Int)
   'js/String.fromCharCode      (fn-of '(Int) 'String #:rest 'Int)
   ;; --- JS globals (values) --------------------------------------------------
   'js/undefined      (p 'Nil)
   'js/NaN            (p 'Float)
   'js/Infinity       (p 'Float)
   'js/globalThis     (p 'Any)
   ))

(provide STDLIB-CLJS)
