/* Generated by native.fold-c17; do not edit. */
#ifndef NATIVE_MODULE_0_ABI_H
#define NATIVE_MODULE_0_ABI_H

#include "native_shim.h"

typedef void *native_m0_type_0;
_Static_assert(sizeof(native_m0_type_0) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_0) == 8, "layout alignment");

typedef int64_t native_m0_type_1;
_Static_assert(sizeof(native_m0_type_1) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_1) == 8, "layout alignment");

typedef bool native_m0_type_2;
_Static_assert(sizeof(native_m0_type_2) == 1, "layout size");
_Static_assert(_Alignof(native_m0_type_2) == 1, "layout alignment");

typedef double native_m0_type_3;
_Static_assert(sizeof(native_m0_type_3) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_3) == 8, "layout alignment");

typedef uint64_t native_m0_type_4;
_Static_assert(sizeof(native_m0_type_4) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_4) == 8, "layout alignment");

typedef uint64_t native_m0_type_5;
_Static_assert(sizeof(native_m0_type_5) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_5) == 8, "layout alignment");

typedef int64_t native_m0_type_6;
_Static_assert(sizeof(native_m0_type_6) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_6) == 8, "layout alignment");

typedef struct native_m0_type_7 {
  native_m0_type_6 tag;
  union {
    native_m0_type_2 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_3 variant_2;
    native_m0_type_4 variant_3;
    native_m0_type_5 variant_4;
  } payload;
} native_m0_type_7;
_Static_assert(sizeof(native_m0_type_7) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_7) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_7, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_7, payload) == 8, "union payload offset");

typedef struct native_m0_type_8 {
  native_m0_type_6 tag;
} native_m0_type_8;
_Static_assert(sizeof(native_m0_type_8) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_8) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_8, tag) == 0, "union tag offset");

typedef struct native_m0_type_9 {
  native_m0_type_6 tag;
} native_m0_type_9;
_Static_assert(sizeof(native_m0_type_9) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_9) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_9, tag) == 0, "union tag offset");

typedef struct native_m0_type_10 {
  native_m0_type_6 tag;
  union {
    native_m0_type_1 variant_0;
  } payload;
} native_m0_type_10;
_Static_assert(sizeof(native_m0_type_10) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_10) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_10, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_10, payload) == 8, "union payload offset");

typedef struct native_m0_type_11 {
  native_m0_type_6 tag;
  union {
    native_m0_type_1 variant_0;
  } payload;
} native_m0_type_11;
_Static_assert(sizeof(native_m0_type_11) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_11) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_11, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_11, payload) == 8, "union payload offset");

/* insertion-order map of native_m0_type_5 to native_m0_type_32 */
typedef native_map *native_m0_type_12;
_Static_assert(sizeof(native_m0_type_12) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_12) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_36 */
typedef native_map *native_m0_type_13;
_Static_assert(sizeof(native_m0_type_13) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_13) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_29 */
typedef native_map *native_m0_type_14;
_Static_assert(sizeof(native_m0_type_14) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_14) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_38 */
typedef native_map *native_m0_type_15;
_Static_assert(sizeof(native_m0_type_15) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_15) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_33 */
typedef native_map *native_m0_type_16;
_Static_assert(sizeof(native_m0_type_16) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_16) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_40 */
typedef native_map *native_m0_type_17;
_Static_assert(sizeof(native_m0_type_17) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_17) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_31 */
typedef native_map *native_m0_type_18;
_Static_assert(sizeof(native_m0_type_18) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_18) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_35 */
typedef native_map *native_m0_type_19;
_Static_assert(sizeof(native_m0_type_19) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_19) == 8, "layout alignment");

/* insertion-order map of native_m0_type_5 to native_m0_type_37 */
typedef native_map *native_m0_type_20;
_Static_assert(sizeof(native_m0_type_20) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_20) == 8, "layout alignment");

/* insertion-order set of native_m0_type_5 */
typedef native_set *native_m0_type_21;
_Static_assert(sizeof(native_m0_type_21) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_21) == 8, "layout alignment");

/* vector of native_m0_type_34, stride 16 */
typedef native_vec *native_m0_type_22;
_Static_assert(sizeof(native_m0_type_22) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_22) == 8, "layout alignment");

/* vector of native_m0_type_22, stride 8 */
typedef native_vec *native_m0_type_23;
_Static_assert(sizeof(native_m0_type_23) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_23) == 8, "layout alignment");

/* vector of native_m0_type_4, stride 8 */
typedef native_vec *native_m0_type_24;
_Static_assert(sizeof(native_m0_type_24) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_24) == 8, "layout alignment");

/* vector of native_m0_type_5, stride 8 */
typedef native_vec *native_m0_type_25;
_Static_assert(sizeof(native_m0_type_25) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_25) == 8, "layout alignment");

/* vector of native_m0_type_24, stride 8 */
typedef native_vec *native_m0_type_26;
_Static_assert(sizeof(native_m0_type_26) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_26) == 8, "layout alignment");

/* vector of native_m0_type_4, stride 8 */
typedef native_vec *native_m0_type_27;
_Static_assert(sizeof(native_m0_type_27) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_27) == 8, "layout alignment");

typedef struct native_m0_type_28 {
  native_m0_type_6 tag;
  union {
    native_m0_type_1 variant_0;
    native_m0_type_9 variant_1;
  } payload;
} native_m0_type_28;
_Static_assert(sizeof(native_m0_type_28) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_28) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_28, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_28, payload) == 8, "union payload offset");

typedef struct native_m0_type_29 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
  } payload;
} native_m0_type_29;
_Static_assert(sizeof(native_m0_type_29) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_29) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_29, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_29, payload) == 8, "union payload offset");

typedef struct native_m0_type_30 {
  native_m0_type_6 tag;
  union {
    native_m0_type_29 variant_0;
    native_m0_type_9 variant_1;
  } payload;
} native_m0_type_30;
_Static_assert(sizeof(native_m0_type_30) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_30) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_30, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_30, payload) == 8, "union payload offset");

typedef struct native_m0_type_31 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_2 variant_2;
    native_m0_type_5 variant_3;
    native_m0_type_9 variant_4;
    native_m0_type_24 variant_5;
    native_m0_type_26 variant_6;
  } payload;
} native_m0_type_31;
_Static_assert(sizeof(native_m0_type_31) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_31) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_31, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_31, payload) == 8, "union payload offset");

typedef struct native_m0_type_32 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_2 variant_2;
    native_m0_type_5 variant_3;
    native_m0_type_9 variant_4;
    native_m0_type_24 variant_5;
    native_m0_type_26 variant_6;
    native_m0_type_18 variant_7;
  } payload;
} native_m0_type_32;
_Static_assert(sizeof(native_m0_type_32) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_32) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_32, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_32, payload) == 8, "union payload offset");

typedef struct native_m0_type_33 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_2 variant_2;
    native_m0_type_5 variant_3;
    native_m0_type_9 variant_4;
    native_m0_type_24 variant_5;
    native_m0_type_26 variant_6;
    native_m0_type_18 variant_7;
    native_m0_type_12 variant_8;
  } payload;
} native_m0_type_33;
_Static_assert(sizeof(native_m0_type_33) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_33) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_33, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_33, payload) == 8, "union payload offset");

typedef struct native_m0_type_34 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_3 variant_2;
    native_m0_type_2 variant_3;
    native_m0_type_5 variant_4;
    native_m0_type_9 variant_5;
  } payload;
} native_m0_type_34;
_Static_assert(sizeof(native_m0_type_34) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_34) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_34, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_34, payload) == 8, "union payload offset");

typedef struct native_m0_type_35 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_3 variant_2;
    native_m0_type_2 variant_3;
    native_m0_type_5 variant_4;
    native_m0_type_9 variant_5;
    native_m0_type_24 variant_6;
    native_m0_type_26 variant_7;
  } payload;
} native_m0_type_35;
_Static_assert(sizeof(native_m0_type_35) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_35) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_35, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_35, payload) == 8, "union payload offset");

typedef struct native_m0_type_36 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_3 variant_2;
    native_m0_type_2 variant_3;
    native_m0_type_5 variant_4;
    native_m0_type_9 variant_5;
    native_m0_type_24 variant_6;
    native_m0_type_26 variant_7;
    native_m0_type_19 variant_8;
  } payload;
} native_m0_type_36;
_Static_assert(sizeof(native_m0_type_36) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_36) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_36, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_36, payload) == 8, "union payload offset");

typedef struct native_m0_type_37 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_3 variant_2;
    native_m0_type_2 variant_3;
    native_m0_type_5 variant_4;
    native_m0_type_9 variant_5;
    native_m0_type_24 variant_6;
    native_m0_type_23 variant_7;
  } payload;
} native_m0_type_37;
_Static_assert(sizeof(native_m0_type_37) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_37) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_37, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_37, payload) == 8, "union payload offset");

typedef struct native_m0_type_38 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_5 variant_2;
  } payload;
} native_m0_type_38;
_Static_assert(sizeof(native_m0_type_38) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_38) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_38, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_38, payload) == 8, "union payload offset");

typedef struct native_m0_type_39 {
  native_m0_type_6 tag;
  union {
    native_m0_type_38 variant_0;
    native_m0_type_9 variant_1;
  } payload;
} native_m0_type_39;
_Static_assert(sizeof(native_m0_type_39) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_39) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_39, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_39, payload) == 8, "union payload offset");

typedef struct native_m0_type_40 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_1 variant_1;
    native_m0_type_5 variant_2;
    native_m0_type_24 variant_3;
  } payload;
} native_m0_type_40;
_Static_assert(sizeof(native_m0_type_40) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_40) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_40, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_40, payload) == 8, "union payload offset");

typedef struct native_m0_type_41 {
  native_m0_type_6 tag;
  union {
    native_m0_type_40 variant_0;
    native_m0_type_9 variant_1;
  } payload;
} native_m0_type_41;
_Static_assert(sizeof(native_m0_type_41) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_41) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_41, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_41, payload) == 8, "union payload offset");

typedef struct native_m0_type_42 {
  native_m0_type_6 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_9 variant_1;
  } payload;
} native_m0_type_42;
_Static_assert(sizeof(native_m0_type_42) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_42) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_42, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_42, payload) == 8, "union payload offset");

typedef struct native_m0_type_43 {
  native_m0_type_6 tag;
  union {
    native_m0_type_20 variant_0;
    native_m0_type_9 variant_1;
  } payload;
} native_m0_type_43;
_Static_assert(sizeof(native_m0_type_43) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_43) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_43, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_43, payload) == 8, "union payload offset");

native_m0_type_28 native_m0_fn_0(native_m0_type_4 native_v_0, native_m0_type_4 native_v_1);
native_m0_type_24 native_m0_fn_1(native_arena *arena, const native_capability *capability, native_m0_type_4 native_v_0);
native_m0_type_2 native_m0_fn_2(native_m0_type_4 native_v_0, native_m0_type_4 native_v_1);
native_m0_type_24 native_m0_fn_3(native_arena *arena, const native_capability *capability, native_m0_type_4 native_v_0);
native_m0_type_4 native_m0_fn_4(native_arena *arena, const native_capability *capability, native_m0_type_4 native_v_0);
native_m0_type_4 native_m0_fn_5(native_arena *arena, const native_capability *capability, native_m0_type_4 native_v_0);
native_m0_type_4 native_m0_fn_6(native_arena *arena, const native_capability *capability, native_m0_type_4 native_v_0);
native_m0_type_2 native_m0_fn_7(native_m0_type_4 native_v_0);
native_m0_type_2 native_m0_fn_8(native_m0_type_4 native_v_0);
native_m0_type_4 native_m0_fn_9(native_arena *arena, const native_capability *capability, native_m0_type_4 native_v_0, native_m0_type_1 native_v_1);
native_m0_type_2 native_m0_fn_10(native_m0_type_14 native_v_0);
native_m0_type_2 native_m0_fn_11(native_m0_type_4 native_v_0);
native_m0_type_2 native_m0_fn_12(native_m0_type_4 native_v_0);
native_m0_type_2 native_m0_fn_13(native_m0_type_14 native_v_0);
native_m0_type_2 native_m0_fn_14(native_arena *arena, const native_capability *capability, native_m0_type_14 native_v_0, native_m0_type_4 native_v_1);
native_m0_type_5 native_m0_fn_15(native_m0_type_4 native_v_0, native_m0_type_28 native_v_1, native_m0_type_28 native_v_2, native_m0_type_28 native_v_3, native_m0_type_28 native_v_4, native_m0_type_42 native_v_5, native_m0_type_42 native_v_6, native_m0_type_42 native_v_7, native_m0_type_42 native_v_8);
native_m0_type_16 native_m0_fn_16(native_arena *arena, const native_capability *capability, native_m0_type_4 native_v_0, native_m0_type_12 native_v_1);
native_m0_type_4 native_m0_fn_17(native_arena *arena, const native_capability *capability, native_m0_type_24 native_v_0);
native_m0_type_4 native_m0_fn_18(native_arena *arena, const native_capability *capability, native_m0_type_17 native_v_0);
native_m0_type_1 native_m0_fn_19(native_m0_type_14 native_v_0);
native_m0_type_1 native_m0_fn_20(native_m0_type_15 native_v_0);
native_m0_type_4 native_m0_fn_21(native_arena *arena, const native_capability *capability, native_m0_type_1 native_v_0, native_m0_type_13 native_v_1);
native_m0_type_4 native_m0_fn_22(native_arena *arena, const native_capability *capability, native_m0_type_1 native_v_0);
native_m0_type_43 native_m0_fn_23(native_m0_type_20 native_v_0);
native_m0_type_43 native_m0_fn_24(native_m0_type_20 native_v_0);

#endif
