/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

struct native_m0_text_0_blob { uint64_t length; uint8_t bytes[sizeof ","]; };
static const struct native_m0_text_0_blob native_m0_text_0 = { (uint64_t)(sizeof "," - 1U), "," };
_Static_assert(offsetof(struct native_m0_text_0_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_1_blob { uint64_t length; uint8_t bytes[sizeof "^(\\S+)\\s+(.*)$"]; };
static const struct native_m0_text_1_blob native_m0_text_1 = { (uint64_t)(sizeof "^(\\S+)\\s+(.*)$" - 1U), "^(\\S+)\\s+(.*)$" };
_Static_assert(offsetof(struct native_m0_text_1_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_2_blob { uint64_t length; uint8_t bytes[sizeof ""]; };
static const struct native_m0_text_2_blob native_m0_text_2 = { (uint64_t)(sizeof "" - 1U), "" };
_Static_assert(offsetof(struct native_m0_text_2_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_3_blob { uint64_t length; uint8_t bytes[sizeof "-"]; };
static const struct native_m0_text_3_blob native_m0_text_3 = { (uint64_t)(sizeof "-" - 1U), "-" };
_Static_assert(offsetof(struct native_m0_text_3_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_4_blob { uint64_t length; uint8_t bytes[sizeof "[^a-z0-9]+"]; };
static const struct native_m0_text_4_blob native_m0_text_4 = { (uint64_t)(sizeof "[^a-z0-9]+" - 1U), "[^a-z0-9]+" };
_Static_assert(offsetof(struct native_m0_text_4_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_5_blob { uint64_t length; uint8_t bytes[sizeof "^_+"]; };
static const struct native_m0_text_5_blob native_m0_text_5 = { (uint64_t)(sizeof "^_+" - 1U), "^_+" };
_Static_assert(offsetof(struct native_m0_text_5_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_6_blob { uint64_t length; uint8_t bytes[sizeof "_+$"]; };
static const struct native_m0_text_6_blob native_m0_text_6 = { (uint64_t)(sizeof "_+$" - 1U), "_+$" };
_Static_assert(offsetof(struct native_m0_text_6_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_7_blob { uint64_t length; uint8_t bytes[sizeof "_"]; };
static const struct native_m0_text_7_blob native_m0_text_7 = { (uint64_t)(sizeof "_" - 1U), "_" };
_Static_assert(offsetof(struct native_m0_text_7_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_8_blob { uint64_t length; uint8_t bytes[sizeof "untitled"]; };
static const struct native_m0_text_8_blob native_m0_text_8 = { (uint64_t)(sizeof "untitled" - 1U), "untitled" };
_Static_assert(offsetof(struct native_m0_text_8_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_9_blob { uint64_t length; uint8_t bytes[sizeof "[^0-9]"]; };
static const struct native_m0_text_9_blob native_m0_text_9 = { (uint64_t)(sizeof "[^0-9]" - 1U), "[^0-9]" };
_Static_assert(offsetof(struct native_m0_text_9_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_10_blob { uint64_t length; uint8_t bytes[sizeof "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}"]; };
static const struct native_m0_text_10_blob native_m0_text_10 = { (uint64_t)(sizeof "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}" - 1U), "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}" };
_Static_assert(offsetof(struct native_m0_text_10_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_11_blob { uint64_t length; uint8_t bytes[sizeof "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}"]; };
static const struct native_m0_text_11_blob native_m0_text_11 = { (uint64_t)(sizeof "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}" - 1U), "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}" };
_Static_assert(offsetof(struct native_m0_text_11_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_12_blob { uint64_t length; uint8_t bytes[sizeof "[0-9a-f]{64}"]; };
static const struct native_m0_text_12_blob native_m0_text_12 = { (uint64_t)(sizeof "[0-9a-f]{64}" - 1U), "[0-9a-f]{64}" };
_Static_assert(offsetof(struct native_m0_text_12_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_13_blob { uint64_t length; uint8_t bytes[sizeof "coordinator DOWN on 127.0.0.1:"]; };
static const struct native_m0_text_13_blob native_m0_text_13 = { (uint64_t)(sizeof "coordinator DOWN on 127.0.0.1:" - 1U), "coordinator DOWN on 127.0.0.1:" };
_Static_assert(offsetof(struct native_m0_text_13_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_14_blob { uint64_t length; uint8_t bytes[sizeof " — start it with bin/fram-up"]; };
static const struct native_m0_text_14_blob native_m0_text_14 = { (uint64_t)(sizeof " — start it with bin/fram-up" - 1U), " — start it with bin/fram-up" };
_Static_assert(offsetof(struct native_m0_text_14_blob, bytes) == 8, "text blob is length-prefixed");

native_m0_type_9 native_m0_fn_0(native_m0_type_3 native_v_0, native_m0_type_3 native_v_1) {
  native_m0_type_9 native_s_0;
  memset(&native_s_0, 0, sizeof native_s_0);
  if (native_text_index_of(native_v_0, native_v_1, &native_s_0.payload.variant_0)) {
    native_s_0.tag = INT64_C(0);
  } else {
    native_s_0.tag = INT64_C(1);
  }
  return native_s_0;
}
native_m0_type_7 native_m0_fn_1(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_7 native_s_2;
  native_m0_type_7 native_s_3;
  native_m0_type_7 native_s_4;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_0;
  native_s_2 = native_text_regex_split((native_arena *)native_s_0, native_v_0, native_s_1);
  native_s_3 = native_text_vector_trim((native_arena *)native_s_0, native_s_2);
  native_s_4 = native_text_vector_remove_blank((native_arena *)native_s_0, native_s_3);
  return native_s_4;
}
native_m0_type_2 native_m0_fn_2(native_m0_type_3 native_v_0, native_m0_type_3 native_v_1) {
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_2 native_s_2;
  native_s_0 = native_text_compare(native_v_0, native_v_1);
  native_s_1 = INT64_C(0);
  native_s_2 = (native_s_0 < native_s_1);
  return native_s_2;
}
native_m0_type_7 native_m0_fn_3(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_8 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_2 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_3 native_s_8;
  native_m0_type_1 native_s_9;
  native_m0_type_3 native_s_10;
  native_m0_type_1 native_s_11;
  native_m0_type_7 native_s_12;
  native_m0_type_7 native_s_13;
  native_m0_type_7 native_s_14;
  native_m0_type_3 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_7 native_s_17;
  native_m0_type_7 native_s_18;
  native_m0_type_7 native_s_19;
  native_m0_type_7 native_s_20;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_1;
  native_s_2 = native_text_trim((native_arena *)native_s_0, native_v_0);
  native_s_3 = native_text_regex_find((native_arena *)native_s_0, native_s_2, native_s_1);
  native_s_4 = native_vec_length(native_s_3);
  native_s_5 = INT64_C(0);
  native_s_6 = (native_s_5 < native_s_4);
  if (native_s_6) {
    goto native_l3_1;
  } else {
    goto native_l3_2;
  }
native_l3_1: ;
  native_s_7 = INT64_C(1);
  native_s_8 = *(const native_m0_type_3 *)native_vec_at(native_s_3, native_s_7, INT64_C(8));
  native_s_9 = INT64_C(2);
  native_s_10 = *(const native_m0_type_3 *)native_vec_at(native_s_3, native_s_9, INT64_C(8));
  native_s_11 = INT64_C(2);
  native_s_12 = native_vec_new((native_arena *)native_s_0, native_s_11, INT64_C(8), (size_t)8);
  native_s_13 = native_vec_push((native_arena *)native_s_0, native_s_12, &native_s_8, INT64_C(8), (size_t)8);
  native_s_14 = native_vec_push((native_arena *)native_s_0, native_s_13, &native_s_10, INT64_C(8), (size_t)8);
  native_s_20 = native_s_14;
  goto native_l3_3;
native_l3_2: ;
  native_s_15 = (uint64_t)(uintptr_t)&native_m0_text_2;
  native_s_16 = INT64_C(2);
  native_s_17 = native_vec_new((native_arena *)native_s_0, native_s_16, INT64_C(8), (size_t)8);
  native_s_18 = native_vec_push((native_arena *)native_s_0, native_s_17, &native_s_2, INT64_C(8), (size_t)8);
  native_s_19 = native_vec_push((native_arena *)native_s_0, native_s_18, &native_s_15, INT64_C(8), (size_t)8);
  native_s_20 = native_s_19;
  goto native_l3_3;
native_l3_3: ;
  return native_s_20;
}
native_m0_type_3 native_m0_fn_4(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_3 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_3 native_s_8;
  native_m0_type_3 native_s_9;
  native_m0_type_1 native_s_10;
  native_m0_type_1 native_s_11;
  native_m0_type_3 native_s_12;
  native_m0_type_3 native_s_13;
  native_m0_type_1 native_s_14;
  native_m0_type_1 native_s_15;
  native_m0_type_3 native_s_16;
  native_m0_type_3 native_s_17;
  native_s_0 = arena;
  (void)native_s_0;
  {
    const uint64_t native_parts_1[1] = { native_v_0 };
    native_s_1 = native_text_concat((native_arena *)native_s_0, native_parts_1, UINT64_C(1));
  }
  native_s_2 = INT64_C(0);
  native_s_3 = INT64_C(4);
  if ((native_s_2 < INT64_C(0)) || (native_s_3 < native_s_2) ||
      (native_s_3 > (int64_t)native_text_length(native_s_1))) {
    native_trap(UINT32_C(3));
  }
  native_s_4 = native_text_slice((native_arena *)native_s_0, native_s_1, (uint64_t)native_s_2, (uint64_t)native_s_3);
  native_s_5 = (uint64_t)(uintptr_t)&native_m0_text_3;
  native_s_6 = INT64_C(4);
  native_s_7 = INT64_C(6);
  if ((native_s_6 < INT64_C(0)) || (native_s_7 < native_s_6) ||
      (native_s_7 > (int64_t)native_text_length(native_s_1))) {
    native_trap(UINT32_C(3));
  }
  native_s_8 = native_text_slice((native_arena *)native_s_0, native_s_1, (uint64_t)native_s_6, (uint64_t)native_s_7);
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_text_3;
  native_s_10 = INT64_C(6);
  native_s_11 = INT64_C(8);
  if ((native_s_10 < INT64_C(0)) || (native_s_11 < native_s_10) ||
      (native_s_11 > (int64_t)native_text_length(native_s_1))) {
    native_trap(UINT32_C(3));
  }
  native_s_12 = native_text_slice((native_arena *)native_s_0, native_s_1, (uint64_t)native_s_10, (uint64_t)native_s_11);
  native_s_13 = (uint64_t)(uintptr_t)&native_m0_text_3;
  native_s_14 = INT64_C(8);
  native_s_15 = INT64_C(14);
  if ((native_s_14 < INT64_C(0)) || (native_s_15 < native_s_14) ||
      (native_s_15 > (int64_t)native_text_length(native_s_1))) {
    native_trap(UINT32_C(3));
  }
  native_s_16 = native_text_slice((native_arena *)native_s_0, native_s_1, (uint64_t)native_s_14, (uint64_t)native_s_15);
  {
    const uint64_t native_parts_17[7] = { native_s_4, native_s_5, native_s_8, native_s_9, native_s_12, native_s_13, native_s_16 };
    native_s_17 = native_text_concat((native_arena *)native_s_0, native_parts_17, UINT64_C(7));
  }
  return native_s_17;
}
native_m0_type_3 native_m0_fn_5(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_3 native_s_3;
  native_m0_type_3 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_3 native_s_6;
  native_m0_type_3 native_s_7;
  native_m0_type_3 native_s_8;
  native_m0_type_3 native_s_9;
  native_m0_type_3 native_s_10;
  native_m0_type_3 native_s_11;
  native_m0_type_1 native_s_12;
  native_m0_type_1 native_s_13;
  native_m0_type_2 native_s_14;
  native_m0_type_1 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_3 native_s_17;
  native_m0_type_3 native_s_18;
  native_m0_type_3 native_s_19;
  native_m0_type_3 native_s_20;
  native_m0_type_2 native_s_21;
  native_m0_type_3 native_s_22;
  native_m0_type_3 native_s_23;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_4;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_5;
  native_s_3 = (uint64_t)(uintptr_t)&native_m0_text_6;
  {
    const uint64_t native_parts_4[1] = { native_v_0 };
    native_s_4 = native_text_concat((native_arena *)native_s_0, native_parts_4, UINT64_C(1));
  }
  native_s_5 = native_text_lower_ascii((native_arena *)native_s_0, native_s_4);
  native_s_6 = (uint64_t)(uintptr_t)&native_m0_text_7;
  native_s_7 = native_text_regex_replace((native_arena *)native_s_0, native_s_5, native_s_1, native_s_6);
  native_s_8 = (uint64_t)(uintptr_t)&native_m0_text_2;
  native_s_9 = native_text_regex_replace((native_arena *)native_s_0, native_s_7, native_s_2, native_s_8);
  native_s_10 = (uint64_t)(uintptr_t)&native_m0_text_2;
  native_s_11 = native_text_regex_replace((native_arena *)native_s_0, native_s_9, native_s_3, native_s_10);
  native_s_12 = (int64_t)native_text_length(native_s_11);
  native_s_13 = INT64_C(60);
  native_s_14 = (native_s_13 < native_s_12);
  if (native_s_14) {
    goto native_l5_1;
  } else {
    goto native_l5_2;
  }
native_l5_1: ;
  native_s_15 = INT64_C(0);
  native_s_16 = INT64_C(60);
  if ((native_s_15 < INT64_C(0)) || (native_s_16 < native_s_15) ||
      (native_s_16 > (int64_t)native_text_length(native_s_11))) {
    native_trap(UINT32_C(3));
  }
  native_s_17 = native_text_slice((native_arena *)native_s_0, native_s_11, (uint64_t)native_s_15, (uint64_t)native_s_16);
  native_s_18 = native_s_17;
  goto native_l5_3;
native_l5_2: ;
  native_s_18 = native_s_11;
  goto native_l5_3;
native_l5_3: ;
  native_s_19 = (uint64_t)(uintptr_t)&native_m0_text_2;
  native_s_20 = native_text_regex_replace((native_arena *)native_s_0, native_s_18, native_s_3, native_s_19);
  native_s_21 = native_text_is_blank(native_s_20);
  if (native_s_21) {
    goto native_l5_4;
  } else {
    goto native_l5_5;
  }
native_l5_4: ;
  native_s_22 = (uint64_t)(uintptr_t)&native_m0_text_8;
  native_s_23 = native_s_22;
  goto native_l5_6;
native_l5_5: ;
  native_s_23 = native_s_20;
  goto native_l5_6;
native_l5_6: ;
  return native_s_23;
}
native_m0_type_3 native_m0_fn_6(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_3 native_s_3;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_9;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_2;
  native_s_3 = native_text_regex_replace((native_arena *)native_s_0, native_v_0, native_s_1, native_s_2);
  return native_s_3;
}
native_m0_type_2 native_m0_fn_7(native_m0_type_3 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_2 native_s_5;
  native_m0_type_2 native_s_6;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_10;
  native_s_1 = INT64_C(19);
  native_s_2 = (int64_t)native_text_length(native_v_0);
  native_s_3 = (native_s_1 == native_s_2);
  if (native_s_3) {
    goto native_l7_1;
  } else {
    goto native_l7_2;
  }
native_l7_1: ;
  native_s_4 = native_text_regex_matches(native_v_0, native_s_0);
  native_s_6 = native_s_4;
  goto native_l7_3;
native_l7_2: ;
  native_s_5 = false;
  native_s_6 = native_s_5;
  goto native_l7_3;
native_l7_3: ;
  return native_s_6;
}
native_m0_type_2 native_m0_fn_8(native_m0_type_3 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_2 native_s_5;
  native_m0_type_2 native_s_6;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_11;
  native_s_1 = INT64_C(16);
  native_s_2 = (int64_t)native_text_length(native_v_0);
  native_s_3 = (native_s_1 == native_s_2);
  if (native_s_3) {
    goto native_l8_1;
  } else {
    goto native_l8_2;
  }
native_l8_1: ;
  native_s_4 = native_text_regex_matches(native_v_0, native_s_0);
  native_s_6 = native_s_4;
  goto native_l8_3;
native_l8_2: ;
  native_s_5 = false;
  native_s_6 = native_s_5;
  goto native_l8_3;
native_l8_3: ;
  return native_s_6;
}
native_m0_type_2 native_m0_fn_9(native_m0_type_3 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_2 native_s_1;
  native_m0_type_2 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_12;
  native_s_1 = true;
  if (native_s_1) {
    goto native_l9_1;
  } else {
    goto native_l9_2;
  }
native_l9_1: ;
  native_s_2 = native_text_regex_matches(native_v_0, native_s_0);
  native_s_4 = native_s_2;
  goto native_l9_3;
native_l9_2: ;
  native_s_3 = false;
  native_s_4 = native_s_3;
  goto native_l9_3;
native_l9_3: ;
  return native_s_4;
}
native_m0_type_2 native_m0_fn_10(native_m0_type_3 native_v_0) {
  native_m0_type_2 native_s_0;
  native_m0_type_2 native_s_1;
  native_m0_type_2 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_2 native_s_5;
  native_s_0 = true;
  if (native_s_0) {
    goto native_l10_1;
  } else {
    goto native_l10_2;
  }
native_l10_1: ;
  native_s_1 = native_text_is_blank(native_v_0);
  native_s_2 = false;
  native_s_3 = (native_s_1 == native_s_2);
  native_s_5 = native_s_3;
  goto native_l10_3;
native_l10_2: ;
  native_s_4 = false;
  native_s_5 = native_s_4;
  goto native_l10_3;
native_l10_3: ;
  return native_s_5;
}
native_m0_type_3 native_m0_fn_11(native_arena *arena, const native_capability *capability, native_m0_type_1 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_3 native_s_3;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_13;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_14;
  {
    const uint64_t native_parts_3[3] = { native_s_1, native_text_from_int((native_arena *)native_s_0, native_v_0), native_s_2 };
    native_s_3 = native_text_concat((native_arena *)native_s_0, native_parts_3, UINT64_C(3));
  }
  return native_s_3;
}
