#ifndef NATIVE_KERNEL_CLASSIFY_FUNCTION_MAP_H
#define NATIVE_KERNEL_CLASSIFY_FUNCTION_MAP_H

#define KC_STRIP_AT native_m0_fn_0
#define KC_HAS_WHITESPACE native_m0_fn_1
#define KC_REF_SHAPE native_m0_fn_2
#define KC_VEC_MEMBER native_m0_fn_3
#define KC_EMOJI_SINGLE native_m0_fn_4
#define KC_CONFIGURED_SINGLE native_m0_fn_5
#define KC_META_SINGLE_SEED native_m0_fn_6
#define KC_SINGLE_EFF native_m0_fn_7
#define KC_KEY_OF_GROUP native_m0_fn_8
#define KC_KEY_OF_TRIPLE native_m0_fn_9
#define KC_NORMALIZE_REF_VALUE native_m0_fn_10
#define KC_LEASE_INVALID native_m0_fn_11
#define KC_LEASE_SUBJECT native_m0_fn_12
#define KC_LEASE_ENCODE native_m0_fn_13
#define KC_LEASE_DECODE native_m0_fn_14
#define KC_DELIVERY_TRIGGER native_m0_fn_15
#define KC_OBSERVED_FALLBACK_SINGLE native_m0_fn_16
#define KC_OBSERVED_KEY_SEP native_m0_fn_17
#define KC_OBSERVED_LEASE_SCHEMA_LINES native_m0_fn_18

#endif
