/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

struct native_m0_text_0_blob { uint64_t length; uint8_t bytes[sizeof "@"]; };
static const struct native_m0_text_0_blob native_m0_text_0 = { (uint64_t)(sizeof "@" - 1U), "@" };
_Static_assert(offsetof(struct native_m0_text_0_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_1_blob { uint64_t length; uint8_t bytes[sizeof "\t"]; };
static const struct native_m0_text_1_blob native_m0_text_1 = { (uint64_t)(sizeof "\t" - 1U), "\t" };
_Static_assert(offsetof(struct native_m0_text_1_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_2_blob { uint64_t length; uint8_t bytes[sizeof "\n"]; };
static const struct native_m0_text_2_blob native_m0_text_2 = { (uint64_t)(sizeof "\n" - 1U), "\n" };
_Static_assert(offsetof(struct native_m0_text_2_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_3_blob { uint64_t length; uint8_t bytes[sizeof "\v"]; };
static const struct native_m0_text_3_blob native_m0_text_3 = { (uint64_t)(sizeof "\v" - 1U), "\v" };
_Static_assert(offsetof(struct native_m0_text_3_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_4_blob { uint64_t length; uint8_t bytes[sizeof "\f"]; };
static const struct native_m0_text_4_blob native_m0_text_4 = { (uint64_t)(sizeof "\f" - 1U), "\f" };
_Static_assert(offsetof(struct native_m0_text_4_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_5_blob { uint64_t length; uint8_t bytes[sizeof "\r"]; };
static const struct native_m0_text_5_blob native_m0_text_5 = { (uint64_t)(sizeof "\r" - 1U), "\r" };
_Static_assert(offsetof(struct native_m0_text_5_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_6_blob { uint64_t length; uint8_t bytes[sizeof " "]; };
static const struct native_m0_text_6_blob native_m0_text_6 = { (uint64_t)(sizeof " " - 1U), " " };
_Static_assert(offsetof(struct native_m0_text_6_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_7_blob { uint64_t length; uint8_t bytes[sizeof "emoji_"]; };
static const struct native_m0_text_7_blob native_m0_text_7 = { (uint64_t)(sizeof "emoji_" - 1U), "emoji_" };
_Static_assert(offsetof(struct native_m0_text_7_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_8_blob { uint64_t length; uint8_t bytes[sizeof "cardinality"]; };
static const struct native_m0_text_8_blob native_m0_text_8 = { (uint64_t)(sizeof "cardinality" - 1U), "cardinality" };
_Static_assert(offsetof(struct native_m0_text_8_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_9_blob { uint64_t length; uint8_t bytes[sizeof "value_kind"]; };
static const struct native_m0_text_9_blob native_m0_text_9 = { (uint64_t)(sizeof "value_kind" - 1U), "value_kind" };
_Static_assert(offsetof(struct native_m0_text_9_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_10_blob { uint64_t length; uint8_t bytes[sizeof "name"]; };
static const struct native_m0_text_10_blob native_m0_text_10 = { (uint64_t)(sizeof "name" - 1U), "name" };
_Static_assert(offsetof(struct native_m0_text_10_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_11_blob { uint64_t length; uint8_t bytes[sizeof "acyclic"]; };
static const struct native_m0_text_11_blob native_m0_text_11 = { (uint64_t)(sizeof "acyclic" - 1U), "acyclic" };
_Static_assert(offsetof(struct native_m0_text_11_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_12_blob { uint64_t length; uint8_t bytes[sizeof "predicate_name"]; };
static const struct native_m0_text_12_blob native_m0_text_12 = { (uint64_t)(sizeof "predicate_name" - 1U), "predicate_name" };
_Static_assert(offsetof(struct native_m0_text_12_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_13_blob { uint64_t length; uint8_t bytes[sizeof "title"]; };
static const struct native_m0_text_13_blob native_m0_text_13 = { (uint64_t)(sizeof "title" - 1U), "title" };
_Static_assert(offsetof(struct native_m0_text_13_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_14_blob { uint64_t length; uint8_t bytes[sizeof "owner"]; };
static const struct native_m0_text_14_blob native_m0_text_14 = { (uint64_t)(sizeof "owner" - 1U), "owner" };
_Static_assert(offsetof(struct native_m0_text_14_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_15_blob { uint64_t length; uint8_t bytes[sizeof "lead"]; };
static const struct native_m0_text_15_blob native_m0_text_15 = { (uint64_t)(sizeof "lead" - 1U), "lead" };
_Static_assert(offsetof(struct native_m0_text_15_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_16_blob { uint64_t length; uint8_t bytes[sizeof "driver"]; };
static const struct native_m0_text_16_blob native_m0_text_16 = { (uint64_t)(sizeof "driver" - 1U), "driver" };
_Static_assert(offsetof(struct native_m0_text_16_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_17_blob { uint64_t length; uint8_t bytes[sizeof "source"]; };
static const struct native_m0_text_17_blob native_m0_text_17 = { (uint64_t)(sizeof "source" - 1U), "source" };
_Static_assert(offsetof(struct native_m0_text_17_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_18_blob { uint64_t length; uint8_t bytes[sizeof "part_of"]; };
static const struct native_m0_text_18_blob native_m0_text_18 = { (uint64_t)(sizeof "part_of" - 1U), "part_of" };
_Static_assert(offsetof(struct native_m0_text_18_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_19_blob { uint64_t length; uint8_t bytes[sizeof "do_on"]; };
static const struct native_m0_text_19_blob native_m0_text_19 = { (uint64_t)(sizeof "do_on" - 1U), "do_on" };
_Static_assert(offsetof(struct native_m0_text_19_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_20_blob { uint64_t length; uint8_t bytes[sizeof "valid_until"]; };
static const struct native_m0_text_20_blob native_m0_text_20 = { (uint64_t)(sizeof "valid_until" - 1U), "valid_until" };
_Static_assert(offsetof(struct native_m0_text_20_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_21_blob { uint64_t length; uint8_t bytes[sizeof "estimate_hours"]; };
static const struct native_m0_text_21_blob native_m0_text_21 = { (uint64_t)(sizeof "estimate_hours" - 1U), "estimate_hours" };
_Static_assert(offsetof(struct native_m0_text_21_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_22_blob { uint64_t length; uint8_t bytes[sizeof "created_at"]; };
static const struct native_m0_text_22_blob native_m0_text_22 = { (uint64_t)(sizeof "created_at" - 1U), "created_at" };
_Static_assert(offsetof(struct native_m0_text_22_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_23_blob { uint64_t length; uint8_t bytes[sizeof "updated_at"]; };
static const struct native_m0_text_23_blob native_m0_text_23 = { (uint64_t)(sizeof "updated_at" - 1U), "updated_at" };
_Static_assert(offsetof(struct native_m0_text_23_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_24_blob { uint64_t length; uint8_t bytes[sizeof "body"]; };
static const struct native_m0_text_24_blob native_m0_text_24 = { (uint64_t)(sizeof "body" - 1U), "body" };
_Static_assert(offsetof(struct native_m0_text_24_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_25_blob { uint64_t length; uint8_t bytes[sizeof "created_by"]; };
static const struct native_m0_text_25_blob native_m0_text_25 = { (uint64_t)(sizeof "created_by" - 1U), "created_by" };
_Static_assert(offsetof(struct native_m0_text_25_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_26_blob { uint64_t length; uint8_t bytes[sizeof "committed"]; };
static const struct native_m0_text_26_blob native_m0_text_26 = { (uint64_t)(sizeof "committed" - 1U), "committed" };
_Static_assert(offsetof(struct native_m0_text_26_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_27_blob { uint64_t length; uint8_t bytes[sizeof "outcome"]; };
static const struct native_m0_text_27_blob native_m0_text_27 = { (uint64_t)(sizeof "outcome" - 1U), "outcome" };
_Static_assert(offsetof(struct native_m0_text_27_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_28_blob { uint64_t length; uint8_t bytes[sizeof "abandoned"]; };
static const struct native_m0_text_28_blob native_m0_text_28 = { (uint64_t)(sizeof "abandoned" - 1U), "abandoned" };
_Static_assert(offsetof(struct native_m0_text_28_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_29_blob { uint64_t length; uint8_t bytes[sizeof "superseded_by"]; };
static const struct native_m0_text_29_blob native_m0_text_29 = { (uint64_t)(sizeof "superseded_by" - 1U), "superseded_by" };
_Static_assert(offsetof(struct native_m0_text_29_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_30_blob { uint64_t length; uint8_t bytes[sizeof "merged_into"]; };
static const struct native_m0_text_30_blob native_m0_text_30 = { (uint64_t)(sizeof "merged_into" - 1U), "merged_into" };
_Static_assert(offsetof(struct native_m0_text_30_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_31_blob { uint64_t length; uint8_t bytes[sizeof "session_of"]; };
static const struct native_m0_text_31_blob native_m0_text_31 = { (uint64_t)(sizeof "session_of" - 1U), "session_of" };
_Static_assert(offsetof(struct native_m0_text_31_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_32_blob { uint64_t length; uint8_t bytes[sizeof "start_time"]; };
static const struct native_m0_text_32_blob native_m0_text_32 = { (uint64_t)(sizeof "start_time" - 1U), "start_time" };
_Static_assert(offsetof(struct native_m0_text_32_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_33_blob { uint64_t length; uint8_t bytes[sizeof "end_time"]; };
static const struct native_m0_text_33_blob native_m0_text_33 = { (uint64_t)(sizeof "end_time" - 1U), "end_time" };
_Static_assert(offsetof(struct native_m0_text_33_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_34_blob { uint64_t length; uint8_t bytes[sizeof "clockify_id"]; };
static const struct native_m0_text_34_blob native_m0_text_34 = { (uint64_t)(sizeof "clockify_id" - 1U), "clockify_id" };
_Static_assert(offsetof(struct native_m0_text_34_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_35_blob { uint64_t length; uint8_t bytes[sizeof "\001"]; };
static const struct native_m0_text_35_blob native_m0_text_35 = { (uint64_t)(sizeof "\001" - 1U), "\001" };
_Static_assert(offsetof(struct native_m0_text_35_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_36_blob { uint64_t length; uint8_t bytes[sizeof "ref"]; };
static const struct native_m0_text_36_blob native_m0_text_36 = { (uint64_t)(sizeof "ref" - 1U), "ref" };
_Static_assert(offsetof(struct native_m0_text_36_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_37_blob { uint64_t length; uint8_t bytes[sizeof ""]; };
static const struct native_m0_text_37_blob native_m0_text_37 = { (uint64_t)(sizeof "" - 1U), "" };
_Static_assert(offsetof(struct native_m0_text_37_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_38_blob { uint64_t length; uint8_t bytes[sizeof "@lease:"]; };
static const struct native_m0_text_38_blob native_m0_text_38 = { (uint64_t)(sizeof "@lease:" - 1U), "@lease:" };
_Static_assert(offsetof(struct native_m0_text_38_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_39_blob { uint64_t length; uint8_t bytes[sizeof "|"]; };
static const struct native_m0_text_39_blob native_m0_text_39 = { (uint64_t)(sizeof "|" - 1U), "|" };
_Static_assert(offsetof(struct native_m0_text_39_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_40_blob { uint64_t length; uint8_t bytes[sizeof "to"]; };
static const struct native_m0_text_40_blob native_m0_text_40 = { (uint64_t)(sizeof "to" - 1U), "to" };
_Static_assert(offsetof(struct native_m0_text_40_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_41_blob { uint64_t length; uint8_t bytes[sizeof "target"]; };
static const struct native_m0_text_41_blob native_m0_text_41 = { (uint64_t)(sizeof "target" - 1U), "target" };
_Static_assert(offsetof(struct native_m0_text_41_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_42_blob { uint64_t length; uint8_t bytes[sizeof "@lease cardinality single"]; };
static const struct native_m0_text_42_blob native_m0_text_42 = { (uint64_t)(sizeof "@lease cardinality single" - 1U), "@lease cardinality single" };
_Static_assert(offsetof(struct native_m0_text_42_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_text_43_blob { uint64_t length; uint8_t bytes[sizeof "@lease value_kind literal"]; };
static const struct native_m0_text_43_blob native_m0_text_43 = { (uint64_t)(sizeof "@lease value_kind literal" - 1U), "@lease value_kind literal" };
_Static_assert(offsetof(struct native_m0_text_43_blob, bytes) == 8, "text blob is length-prefixed");

native_m0_type_3 native_m0_fn_0(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_11 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_2 native_s_5;
  native_m0_type_2 native_s_6;
  native_m0_type_2 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_1 native_s_9;
  native_m0_type_3 native_s_10;
  native_m0_type_3 native_s_11;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_0;
  memset(&native_s_2, 0, sizeof native_s_2);
  if (native_text_index_of(native_v_0, native_s_1, &native_s_2.payload.variant_0)) {
    native_s_2.tag = INT64_C(0);
  } else {
    native_s_2.tag = INT64_C(1);
  }
  native_s_3 = INT64_C(0);
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l0_1;
  case INT64_C(1):
    goto native_l0_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l0_1: ;
  if (native_s_2.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_4 = native_s_2.payload.variant_0;
  native_s_5 = (native_s_3 == native_s_4);
  native_s_7 = native_s_5;
  goto native_l0_3;
native_l0_2: ;
  native_s_6 = false;
  native_s_7 = native_s_6;
  goto native_l0_3;
native_l0_3: ;
  if (native_s_7) {
    goto native_l0_4;
  } else {
    goto native_l0_5;
  }
native_l0_4: ;
  native_s_8 = INT64_C(1);
  native_s_9 = (int64_t)native_text_length(native_v_0);
  if ((native_s_8 < INT64_C(0)) || (native_s_9 < native_s_8) ||
      (native_s_9 > (int64_t)native_text_length(native_v_0))) {
    native_trap(UINT32_C(3));
  }
  native_s_10 = native_text_slice((native_arena *)native_s_0, native_v_0, (uint64_t)native_s_8, (uint64_t)native_s_9);
  native_s_11 = native_s_10;
  goto native_l0_6;
native_l0_5: ;
  native_s_11 = native_v_0;
  goto native_l0_6;
native_l0_6: ;
  return native_s_11;
}
native_m0_type_2 native_m0_fn_1(native_m0_type_3 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_11 native_s_1;
  native_m0_type_2 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_11 native_s_6;
  native_m0_type_2 native_s_7;
  native_m0_type_2 native_s_8;
  native_m0_type_2 native_s_9;
  native_m0_type_3 native_s_10;
  native_m0_type_11 native_s_11;
  native_m0_type_2 native_s_12;
  native_m0_type_2 native_s_13;
  native_m0_type_2 native_s_14;
  native_m0_type_3 native_s_15;
  native_m0_type_11 native_s_16;
  native_m0_type_2 native_s_17;
  native_m0_type_2 native_s_18;
  native_m0_type_2 native_s_19;
  native_m0_type_3 native_s_20;
  native_m0_type_11 native_s_21;
  native_m0_type_2 native_s_22;
  native_m0_type_2 native_s_23;
  native_m0_type_2 native_s_24;
  native_m0_type_3 native_s_25;
  native_m0_type_11 native_s_26;
  native_m0_type_2 native_s_27;
  native_m0_type_2 native_s_28;
  native_m0_type_2 native_s_29;
  native_m0_type_2 native_s_30;
  native_m0_type_2 native_s_31;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_1;
  memset(&native_s_1, 0, sizeof native_s_1);
  if (native_text_index_of(native_v_0, native_s_0, &native_s_1.payload.variant_0)) {
    native_s_1.tag = INT64_C(0);
  } else {
    native_s_1.tag = INT64_C(1);
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l1_1;
  case INT64_C(1):
    goto native_l1_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l1_1: ;
  native_s_2 = true;
  native_s_4 = native_s_2;
  goto native_l1_3;
native_l1_2: ;
  native_s_3 = false;
  native_s_4 = native_s_3;
  goto native_l1_3;
native_l1_3: ;
  if (native_s_4) {
    goto native_l1_24;
  } else {
    goto native_l1_4;
  }
native_l1_4: ;
  native_s_5 = (uint64_t)(uintptr_t)&native_m0_text_2;
  memset(&native_s_6, 0, sizeof native_s_6);
  if (native_text_index_of(native_v_0, native_s_5, &native_s_6.payload.variant_0)) {
    native_s_6.tag = INT64_C(0);
  } else {
    native_s_6.tag = INT64_C(1);
  }
  switch (native_s_6.tag) {
  case INT64_C(0):
    goto native_l1_5;
  case INT64_C(1):
    goto native_l1_6;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l1_5: ;
  native_s_7 = true;
  native_s_9 = native_s_7;
  goto native_l1_7;
native_l1_6: ;
  native_s_8 = false;
  native_s_9 = native_s_8;
  goto native_l1_7;
native_l1_7: ;
  if (native_s_9) {
    goto native_l1_24;
  } else {
    goto native_l1_8;
  }
native_l1_8: ;
  native_s_10 = (uint64_t)(uintptr_t)&native_m0_text_3;
  memset(&native_s_11, 0, sizeof native_s_11);
  if (native_text_index_of(native_v_0, native_s_10, &native_s_11.payload.variant_0)) {
    native_s_11.tag = INT64_C(0);
  } else {
    native_s_11.tag = INT64_C(1);
  }
  switch (native_s_11.tag) {
  case INT64_C(0):
    goto native_l1_9;
  case INT64_C(1):
    goto native_l1_10;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l1_9: ;
  native_s_12 = true;
  native_s_14 = native_s_12;
  goto native_l1_11;
native_l1_10: ;
  native_s_13 = false;
  native_s_14 = native_s_13;
  goto native_l1_11;
native_l1_11: ;
  if (native_s_14) {
    goto native_l1_24;
  } else {
    goto native_l1_12;
  }
native_l1_12: ;
  native_s_15 = (uint64_t)(uintptr_t)&native_m0_text_4;
  memset(&native_s_16, 0, sizeof native_s_16);
  if (native_text_index_of(native_v_0, native_s_15, &native_s_16.payload.variant_0)) {
    native_s_16.tag = INT64_C(0);
  } else {
    native_s_16.tag = INT64_C(1);
  }
  switch (native_s_16.tag) {
  case INT64_C(0):
    goto native_l1_13;
  case INT64_C(1):
    goto native_l1_14;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l1_13: ;
  native_s_17 = true;
  native_s_19 = native_s_17;
  goto native_l1_15;
native_l1_14: ;
  native_s_18 = false;
  native_s_19 = native_s_18;
  goto native_l1_15;
native_l1_15: ;
  if (native_s_19) {
    goto native_l1_24;
  } else {
    goto native_l1_16;
  }
native_l1_16: ;
  native_s_20 = (uint64_t)(uintptr_t)&native_m0_text_5;
  memset(&native_s_21, 0, sizeof native_s_21);
  if (native_text_index_of(native_v_0, native_s_20, &native_s_21.payload.variant_0)) {
    native_s_21.tag = INT64_C(0);
  } else {
    native_s_21.tag = INT64_C(1);
  }
  switch (native_s_21.tag) {
  case INT64_C(0):
    goto native_l1_17;
  case INT64_C(1):
    goto native_l1_18;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l1_17: ;
  native_s_22 = true;
  native_s_24 = native_s_22;
  goto native_l1_19;
native_l1_18: ;
  native_s_23 = false;
  native_s_24 = native_s_23;
  goto native_l1_19;
native_l1_19: ;
  if (native_s_24) {
    goto native_l1_24;
  } else {
    goto native_l1_20;
  }
native_l1_20: ;
  native_s_25 = (uint64_t)(uintptr_t)&native_m0_text_6;
  memset(&native_s_26, 0, sizeof native_s_26);
  if (native_text_index_of(native_v_0, native_s_25, &native_s_26.payload.variant_0)) {
    native_s_26.tag = INT64_C(0);
  } else {
    native_s_26.tag = INT64_C(1);
  }
  switch (native_s_26.tag) {
  case INT64_C(0):
    goto native_l1_21;
  case INT64_C(1):
    goto native_l1_22;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l1_21: ;
  native_s_27 = true;
  native_s_29 = native_s_27;
  goto native_l1_23;
native_l1_22: ;
  native_s_28 = false;
  native_s_29 = native_s_28;
  goto native_l1_23;
native_l1_23: ;
  native_s_31 = native_s_29;
  goto native_l1_25;
native_l1_24: ;
  native_s_30 = true;
  native_s_31 = native_s_30;
  goto native_l1_25;
native_l1_25: ;
  return native_s_31;
}
native_m0_type_2 native_m0_fn_2(native_m0_type_3 native_v_0) {
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_2 native_s_2;
  native_m0_type_3 native_s_3;
  native_m0_type_11 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_2 native_s_7;
  native_m0_type_2 native_s_8;
  native_m0_type_2 native_s_9;
  native_m0_type_2 native_s_10;
  native_m0_type_2 native_s_11;
  native_m0_type_2 native_s_12;
  native_m0_type_2 native_s_13;
  native_m0_type_2 native_s_14;
  native_s_0 = (int64_t)native_text_length(native_v_0);
  native_s_1 = INT64_C(1);
  native_s_2 = (native_s_1 < native_s_0);
  if (native_s_2) {
    goto native_l2_1;
  } else {
    goto native_l2_6;
  }
native_l2_1: ;
  native_s_3 = (uint64_t)(uintptr_t)&native_m0_text_0;
  memset(&native_s_4, 0, sizeof native_s_4);
  if (native_text_index_of(native_v_0, native_s_3, &native_s_4.payload.variant_0)) {
    native_s_4.tag = INT64_C(0);
  } else {
    native_s_4.tag = INT64_C(1);
  }
  native_s_5 = INT64_C(0);
  switch (native_s_4.tag) {
  case INT64_C(0):
    goto native_l2_2;
  case INT64_C(1):
    goto native_l2_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l2_2: ;
  if (native_s_4.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = native_s_4.payload.variant_0;
  native_s_7 = (native_s_5 == native_s_6);
  native_s_9 = native_s_7;
  goto native_l2_4;
native_l2_3: ;
  native_s_8 = false;
  native_s_9 = native_s_8;
  goto native_l2_4;
native_l2_4: ;
  if (native_s_9) {
    goto native_l2_5;
  } else {
    goto native_l2_6;
  }
native_l2_5: ;
  native_s_10 = native_m0_fn_1(native_v_0);
  native_s_11 = false;
  native_s_12 = (native_s_10 == native_s_11);
  native_s_14 = native_s_12;
  goto native_l2_7;
native_l2_6: ;
  native_s_13 = false;
  native_s_14 = native_s_13;
  goto native_l2_7;
native_l2_7: ;
  return native_s_14;
}
native_m0_type_2 native_m0_fn_3(native_m0_type_10 native_v_0, native_m0_type_3 native_v_1) {
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_2 native_s_6;
  native_m0_type_2 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_8 native_s_9;
  native_m0_type_1 native_s_10;
  native_m0_type_8 native_s_11;
  native_m0_type_1 native_s_12;
  native_m0_type_2 native_s_13;
  native_m0_type_2 native_s_14;
  native_s_0 = INT64_C(0);
  native_s_1 = native_s_0;
  goto native_l3_1;
native_l3_1: ;
  native_s_2 = native_vec_length(native_v_0);
  native_s_3 = (native_s_2 <= native_s_1);
  if (native_s_3) {
    goto native_l3_2;
  } else {
    goto native_l3_3;
  }
native_l3_2: ;
  native_s_4 = false;
  native_s_14 = native_s_4;
  goto native_l3_9;
native_l3_3: ;
  native_s_5 = *(const native_m0_type_3 *)native_vec_at(native_v_0, native_s_1, INT64_C(8));
  native_s_6 = native_text_eq(native_s_5, native_v_1);
  if (native_s_6) {
    goto native_l3_4;
  } else {
    goto native_l3_5;
  }
native_l3_4: ;
  native_s_7 = true;
  native_s_13 = native_s_7;
  goto native_l3_8;
native_l3_5: ;
  native_s_8 = INT64_C(1);
  if (__builtin_add_overflow(native_s_1, native_s_8, &native_s_9.payload.variant_0)) {
    native_s_9.tag = INT64_C(1);
  } else {
    native_s_9.tag = INT64_C(0);
  }
  switch (native_s_9.tag) {
  case INT64_C(0):
    native_s_11 = native_s_9;
  goto native_l3_7;
  case INT64_C(1):
    goto native_l3_6;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l3_6: ;
  native_s_10 = INT64_C(2);
  native_trap((uint32_t)native_s_10);
native_l3_7: ;
  native_s_12 = native_s_11.payload.variant_0;
  native_s_1 = native_s_12;
  goto native_l3_1;
native_l3_8: ;
  native_s_14 = native_s_13;
  goto native_l3_9;
native_l3_9: ;
  return native_s_14;
}
native_m0_type_2 native_m0_fn_4(native_m0_type_3 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_11 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_2 native_s_5;
  native_m0_type_2 native_s_6;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_7;
  memset(&native_s_1, 0, sizeof native_s_1);
  if (native_text_index_of(native_v_0, native_s_0, &native_s_1.payload.variant_0)) {
    native_s_1.tag = INT64_C(0);
  } else {
    native_s_1.tag = INT64_C(1);
  }
  native_s_2 = INT64_C(0);
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l4_1;
  case INT64_C(1):
    goto native_l4_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l4_1: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = native_s_1.payload.variant_0;
  native_s_4 = (native_s_2 == native_s_3);
  native_s_6 = native_s_4;
  goto native_l4_3;
native_l4_2: ;
  native_s_5 = false;
  native_s_6 = native_s_5;
  goto native_l4_3;
native_l4_3: ;
  return native_s_6;
}
native_m0_type_2 native_m0_fn_5(native_m0_type_10 native_v_0, native_m0_type_3 native_v_1) {
  native_m0_type_2 native_s_0;
  native_s_0 = native_m0_fn_3(native_v_0, native_v_1);
  return native_s_0;
}
native_m0_type_2 native_m0_fn_6(native_m0_type_3 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_2 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_3 native_s_4;
  native_m0_type_2 native_s_5;
  native_m0_type_3 native_s_6;
  native_m0_type_2 native_s_7;
  native_m0_type_3 native_s_8;
  native_m0_type_2 native_s_9;
  native_m0_type_2 native_s_10;
  native_m0_type_2 native_s_11;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_8;
  native_s_1 = native_text_eq(native_v_0, native_s_0);
  if (native_s_1) {
    goto native_l6_5;
  } else {
    goto native_l6_1;
  }
native_l6_1: ;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_9;
  native_s_3 = native_text_eq(native_v_0, native_s_2);
  if (native_s_3) {
    goto native_l6_5;
  } else {
    goto native_l6_2;
  }
native_l6_2: ;
  native_s_4 = (uint64_t)(uintptr_t)&native_m0_text_10;
  native_s_5 = native_text_eq(native_v_0, native_s_4);
  if (native_s_5) {
    goto native_l6_5;
  } else {
    goto native_l6_3;
  }
native_l6_3: ;
  native_s_6 = (uint64_t)(uintptr_t)&native_m0_text_11;
  native_s_7 = native_text_eq(native_v_0, native_s_6);
  if (native_s_7) {
    goto native_l6_5;
  } else {
    goto native_l6_4;
  }
native_l6_4: ;
  native_s_8 = (uint64_t)(uintptr_t)&native_m0_text_12;
  native_s_9 = native_text_eq(native_v_0, native_s_8);
  native_s_11 = native_s_9;
  goto native_l6_6;
native_l6_5: ;
  native_s_10 = true;
  native_s_11 = native_s_10;
  goto native_l6_6;
native_l6_6: ;
  return native_s_11;
}
native_m0_type_2 native_m0_fn_7(native_arena *arena, const native_capability *capability, native_m0_type_2 native_v_0, native_m0_type_2 native_v_1, native_m0_type_2 native_v_2, native_m0_type_3 native_v_3) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_3 native_s_3;
  native_m0_type_3 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_3 native_s_6;
  native_m0_type_3 native_s_7;
  native_m0_type_3 native_s_8;
  native_m0_type_3 native_s_9;
  native_m0_type_3 native_s_10;
  native_m0_type_3 native_s_11;
  native_m0_type_3 native_s_12;
  native_m0_type_3 native_s_13;
  native_m0_type_3 native_s_14;
  native_m0_type_3 native_s_15;
  native_m0_type_3 native_s_16;
  native_m0_type_3 native_s_17;
  native_m0_type_3 native_s_18;
  native_m0_type_3 native_s_19;
  native_m0_type_3 native_s_20;
  native_m0_type_3 native_s_21;
  native_m0_type_3 native_s_22;
  native_m0_type_3 native_s_23;
  native_m0_type_1 native_s_24;
  native_m0_type_10 native_s_25;
  native_m0_type_10 native_s_26;
  native_m0_type_10 native_s_27;
  native_m0_type_10 native_s_28;
  native_m0_type_10 native_s_29;
  native_m0_type_10 native_s_30;
  native_m0_type_10 native_s_31;
  native_m0_type_10 native_s_32;
  native_m0_type_10 native_s_33;
  native_m0_type_10 native_s_34;
  native_m0_type_10 native_s_35;
  native_m0_type_10 native_s_36;
  native_m0_type_10 native_s_37;
  native_m0_type_10 native_s_38;
  native_m0_type_10 native_s_39;
  native_m0_type_10 native_s_40;
  native_m0_type_10 native_s_41;
  native_m0_type_10 native_s_42;
  native_m0_type_10 native_s_43;
  native_m0_type_10 native_s_44;
  native_m0_type_10 native_s_45;
  native_m0_type_10 native_s_46;
  native_m0_type_10 native_s_47;
  native_m0_type_10 native_s_48;
  native_m0_type_2 native_s_49;
  native_m0_type_2 native_s_50;
  native_m0_type_2 native_s_51;
  native_m0_type_2 native_s_52;
  native_m0_type_2 native_s_53;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_13;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_14;
  native_s_3 = (uint64_t)(uintptr_t)&native_m0_text_15;
  native_s_4 = (uint64_t)(uintptr_t)&native_m0_text_16;
  native_s_5 = (uint64_t)(uintptr_t)&native_m0_text_17;
  native_s_6 = (uint64_t)(uintptr_t)&native_m0_text_18;
  native_s_7 = (uint64_t)(uintptr_t)&native_m0_text_19;
  native_s_8 = (uint64_t)(uintptr_t)&native_m0_text_20;
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_text_21;
  native_s_10 = (uint64_t)(uintptr_t)&native_m0_text_22;
  native_s_11 = (uint64_t)(uintptr_t)&native_m0_text_23;
  native_s_12 = (uint64_t)(uintptr_t)&native_m0_text_10;
  native_s_13 = (uint64_t)(uintptr_t)&native_m0_text_24;
  native_s_14 = (uint64_t)(uintptr_t)&native_m0_text_25;
  native_s_15 = (uint64_t)(uintptr_t)&native_m0_text_26;
  native_s_16 = (uint64_t)(uintptr_t)&native_m0_text_27;
  native_s_17 = (uint64_t)(uintptr_t)&native_m0_text_28;
  native_s_18 = (uint64_t)(uintptr_t)&native_m0_text_29;
  native_s_19 = (uint64_t)(uintptr_t)&native_m0_text_30;
  native_s_20 = (uint64_t)(uintptr_t)&native_m0_text_31;
  native_s_21 = (uint64_t)(uintptr_t)&native_m0_text_32;
  native_s_22 = (uint64_t)(uintptr_t)&native_m0_text_33;
  native_s_23 = (uint64_t)(uintptr_t)&native_m0_text_34;
  native_s_24 = INT64_C(23);
  native_s_25 = native_vec_new((native_arena *)native_s_0, native_s_24, INT64_C(8), (size_t)8);
  native_s_26 = native_vec_push((native_arena *)native_s_0, native_s_25, &native_s_1, INT64_C(8), (size_t)8);
  native_s_27 = native_vec_push((native_arena *)native_s_0, native_s_26, &native_s_2, INT64_C(8), (size_t)8);
  native_s_28 = native_vec_push((native_arena *)native_s_0, native_s_27, &native_s_3, INT64_C(8), (size_t)8);
  native_s_29 = native_vec_push((native_arena *)native_s_0, native_s_28, &native_s_4, INT64_C(8), (size_t)8);
  native_s_30 = native_vec_push((native_arena *)native_s_0, native_s_29, &native_s_5, INT64_C(8), (size_t)8);
  native_s_31 = native_vec_push((native_arena *)native_s_0, native_s_30, &native_s_6, INT64_C(8), (size_t)8);
  native_s_32 = native_vec_push((native_arena *)native_s_0, native_s_31, &native_s_7, INT64_C(8), (size_t)8);
  native_s_33 = native_vec_push((native_arena *)native_s_0, native_s_32, &native_s_8, INT64_C(8), (size_t)8);
  native_s_34 = native_vec_push((native_arena *)native_s_0, native_s_33, &native_s_9, INT64_C(8), (size_t)8);
  native_s_35 = native_vec_push((native_arena *)native_s_0, native_s_34, &native_s_10, INT64_C(8), (size_t)8);
  native_s_36 = native_vec_push((native_arena *)native_s_0, native_s_35, &native_s_11, INT64_C(8), (size_t)8);
  native_s_37 = native_vec_push((native_arena *)native_s_0, native_s_36, &native_s_12, INT64_C(8), (size_t)8);
  native_s_38 = native_vec_push((native_arena *)native_s_0, native_s_37, &native_s_13, INT64_C(8), (size_t)8);
  native_s_39 = native_vec_push((native_arena *)native_s_0, native_s_38, &native_s_14, INT64_C(8), (size_t)8);
  native_s_40 = native_vec_push((native_arena *)native_s_0, native_s_39, &native_s_15, INT64_C(8), (size_t)8);
  native_s_41 = native_vec_push((native_arena *)native_s_0, native_s_40, &native_s_16, INT64_C(8), (size_t)8);
  native_s_42 = native_vec_push((native_arena *)native_s_0, native_s_41, &native_s_17, INT64_C(8), (size_t)8);
  native_s_43 = native_vec_push((native_arena *)native_s_0, native_s_42, &native_s_18, INT64_C(8), (size_t)8);
  native_s_44 = native_vec_push((native_arena *)native_s_0, native_s_43, &native_s_19, INT64_C(8), (size_t)8);
  native_s_45 = native_vec_push((native_arena *)native_s_0, native_s_44, &native_s_20, INT64_C(8), (size_t)8);
  native_s_46 = native_vec_push((native_arena *)native_s_0, native_s_45, &native_s_21, INT64_C(8), (size_t)8);
  native_s_47 = native_vec_push((native_arena *)native_s_0, native_s_46, &native_s_22, INT64_C(8), (size_t)8);
  native_s_48 = native_vec_push((native_arena *)native_s_0, native_s_47, &native_s_23, INT64_C(8), (size_t)8);
  if (native_v_0) {
    goto native_l7_1;
  } else {
    goto native_l7_2;
  }
native_l7_1: ;
  native_s_53 = native_v_1;
  goto native_l7_7;
native_l7_2: ;
  if (native_v_2) {
    goto native_l7_5;
  } else {
    goto native_l7_3;
  }
native_l7_3: ;
  native_s_49 = native_m0_fn_3(native_s_48, native_v_3);
  if (native_s_49) {
    goto native_l7_5;
  } else {
    goto native_l7_4;
  }
native_l7_4: ;
  native_s_50 = native_m0_fn_4(native_v_3);
  native_s_52 = native_s_50;
  goto native_l7_6;
native_l7_5: ;
  native_s_51 = true;
  native_s_52 = native_s_51;
  goto native_l7_6;
native_l7_6: ;
  native_s_53 = native_s_52;
  goto native_l7_7;
native_l7_7: ;
  return native_s_53;
}
native_m0_type_3 native_m0_fn_8(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0, native_m0_type_3 native_v_1) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_35;
  {
    const uint64_t native_parts_2[3] = { native_v_0, native_s_1, native_v_1 };
    native_s_2 = native_text_concat((native_arena *)native_s_0, native_parts_2, UINT64_C(3));
  }
  return native_s_2;
}
native_m0_type_3 native_m0_fn_9(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0, native_m0_type_3 native_v_1, native_m0_type_3 native_v_2) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_35;
  {
    const uint64_t native_parts_2[5] = { native_v_0, native_s_1, native_v_1, native_s_1, native_v_2 };
    native_s_2 = native_text_concat((native_arena *)native_s_0, native_parts_2, UINT64_C(5));
  }
  return native_s_2;
}
native_m0_type_3 native_m0_fn_10(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0, native_m0_type_3 native_v_1) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_2 native_s_2;
  native_m0_type_3 native_s_3;
  native_m0_type_11 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_2 native_s_7;
  native_m0_type_2 native_s_8;
  native_m0_type_2 native_s_9;
  native_m0_type_2 native_s_10;
  native_m0_type_2 native_s_11;
  native_m0_type_2 native_s_12;
  native_m0_type_2 native_s_13;
  native_m0_type_2 native_s_14;
  native_m0_type_2 native_s_15;
  native_m0_type_2 native_s_16;
  native_m0_type_2 native_s_17;
  native_m0_type_2 native_s_18;
  native_m0_type_2 native_s_19;
  native_m0_type_3 native_s_20;
  native_m0_type_3 native_s_21;
  native_m0_type_3 native_s_22;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_36;
  native_s_2 = native_text_eq(native_s_1, native_v_0);
  if (native_s_2) {
    goto native_l10_1;
  } else {
    goto native_l10_7;
  }
native_l10_1: ;
  native_s_3 = (uint64_t)(uintptr_t)&native_m0_text_0;
  memset(&native_s_4, 0, sizeof native_s_4);
  if (native_text_index_of(native_v_1, native_s_3, &native_s_4.payload.variant_0)) {
    native_s_4.tag = INT64_C(0);
  } else {
    native_s_4.tag = INT64_C(1);
  }
  native_s_5 = INT64_C(0);
  switch (native_s_4.tag) {
  case INT64_C(0):
    goto native_l10_2;
  case INT64_C(1):
    goto native_l10_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l10_2: ;
  if (native_s_4.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = native_s_4.payload.variant_0;
  native_s_7 = (native_s_5 == native_s_6);
  native_s_9 = native_s_7;
  goto native_l10_4;
native_l10_3: ;
  native_s_8 = false;
  native_s_9 = native_s_8;
  goto native_l10_4;
native_l10_4: ;
  native_s_10 = false;
  native_s_11 = (native_s_9 == native_s_10);
  if (native_s_11) {
    goto native_l10_5;
  } else {
    goto native_l10_7;
  }
native_l10_5: ;
  native_s_12 = native_text_is_blank(native_v_1);
  native_s_13 = false;
  native_s_14 = (native_s_12 == native_s_13);
  if (native_s_14) {
    goto native_l10_6;
  } else {
    goto native_l10_7;
  }
native_l10_6: ;
  native_s_15 = native_m0_fn_1(native_v_1);
  native_s_16 = false;
  native_s_17 = (native_s_15 == native_s_16);
  native_s_19 = native_s_17;
  goto native_l10_8;
native_l10_7: ;
  native_s_18 = false;
  native_s_19 = native_s_18;
  goto native_l10_8;
native_l10_8: ;
  if (native_s_19) {
    goto native_l10_9;
  } else {
    goto native_l10_10;
  }
native_l10_9: ;
  native_s_20 = (uint64_t)(uintptr_t)&native_m0_text_0;
  {
    const uint64_t native_parts_21[2] = { native_s_20, native_v_1 };
    native_s_21 = native_text_concat((native_arena *)native_s_0, native_parts_21, UINT64_C(2));
  }
  native_s_22 = native_s_21;
  goto native_l10_11;
native_l10_10: ;
  native_s_22 = native_v_1;
  goto native_l10_11;
native_l10_11: ;
  return native_s_22;
}
native_m0_type_4 native_m0_fn_11(void) {
  native_m0_type_3 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_4 native_s_4;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_37;
  native_s_1 = INT64_C(0);
  native_s_2 = INT64_C(0);
  native_s_3 = false;
  native_s_4 = (native_m0_type_4){ .field_0 = native_s_0, .field_1 = native_s_1, .field_2 = native_s_2, .field_3 = native_s_3 };
  return native_s_4;
}
native_m0_type_3 native_m0_fn_12(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_38;
  {
    const uint64_t native_parts_2[2] = { native_s_1, native_v_0 };
    native_s_2 = native_text_concat((native_arena *)native_s_0, native_parts_2, UINT64_C(2));
  }
  return native_s_2;
}
native_m0_type_3 native_m0_fn_13(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0, native_m0_type_1 native_v_1, native_m0_type_1 native_v_2) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_3 native_s_3;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_39;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_39;
  {
    const uint64_t native_parts_3[5] = { native_v_0, native_s_1, native_text_from_int((native_arena *)native_s_0, native_v_1), native_s_2, native_text_from_int((native_arena *)native_s_0, native_v_2) };
    native_s_3 = native_text_concat((native_arena *)native_s_0, native_parts_3, UINT64_C(5));
  }
  return native_s_3;
}
native_m0_type_4 native_m0_fn_14(native_arena *arena, const native_capability *capability, native_m0_type_3 native_v_0) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_11 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_2 native_s_5;
  native_m0_type_4 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_3 native_s_9;
  native_m0_type_1 native_s_10;
  native_m0_type_1 native_s_11;
  native_m0_type_8 native_s_12;
  native_m0_type_1 native_s_13;
  native_m0_type_8 native_s_14;
  native_m0_type_1 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_3 native_s_17;
  native_m0_type_3 native_s_18;
  native_m0_type_11 native_s_19;
  native_m0_type_2 native_s_20;
  native_m0_type_2 native_s_21;
  native_m0_type_2 native_s_22;
  native_m0_type_4 native_s_23;
  native_m0_type_1 native_s_24;
  native_m0_type_1 native_s_25;
  native_m0_type_3 native_s_26;
  native_m0_type_1 native_s_27;
  native_m0_type_1 native_s_28;
  native_m0_type_8 native_s_29;
  native_m0_type_1 native_s_30;
  native_m0_type_8 native_s_31;
  native_m0_type_1 native_s_32;
  native_m0_type_1 native_s_33;
  native_m0_type_3 native_s_34;
  native_m0_type_3 native_s_35;
  native_m0_type_11 native_s_36;
  native_m0_type_2 native_s_37;
  native_m0_type_2 native_s_38;
  native_m0_type_2 native_s_39;
  native_m0_type_4 native_s_40;
  native_m0_type_11 native_s_41;
  native_m0_type_11 native_s_42;
  native_m0_type_2 native_s_43;
  native_m0_type_2 native_s_44;
  native_m0_type_2 native_s_45;
  native_m0_type_4 native_s_46;
  native_m0_type_2 native_s_47;
  native_m0_type_2 native_s_48;
  native_m0_type_2 native_s_49;
  native_m0_type_4 native_s_50;
  native_m0_type_2 native_s_51;
  native_m0_type_1 native_s_52;
  native_m0_type_1 native_s_53;
  native_m0_type_4 native_s_54;
  native_m0_type_4 native_s_55;
  native_m0_type_4 native_s_56;
  native_m0_type_4 native_s_57;
  native_m0_type_4 native_s_58;
  native_m0_type_4 native_s_59;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_39;
  memset(&native_s_2, 0, sizeof native_s_2);
  if (native_text_index_of(native_v_0, native_s_1, &native_s_2.payload.variant_0)) {
    native_s_2.tag = INT64_C(0);
  } else {
    native_s_2.tag = INT64_C(1);
  }
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l14_2;
  case INT64_C(1):
    goto native_l14_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_1: ;
  native_s_3 = true;
  native_s_5 = native_s_3;
  goto native_l14_3;
native_l14_2: ;
  native_s_4 = false;
  native_s_5 = native_s_4;
  goto native_l14_3;
native_l14_3: ;
  if (native_s_5) {
    goto native_l14_4;
  } else {
    goto native_l14_5;
  }
native_l14_4: ;
  native_s_6 = native_m0_fn_11();
  native_s_59 = native_s_6;
  goto native_l14_34;
native_l14_5: ;
  native_s_7 = INT64_C(0);
  if (native_s_2.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_8 = native_s_2.payload.variant_0;
  if ((native_s_7 < INT64_C(0)) || (native_s_8 < native_s_7) ||
      (native_s_8 > (int64_t)native_text_length(native_v_0))) {
    native_trap(UINT32_C(3));
  }
  native_s_9 = native_text_slice((native_arena *)native_s_0, native_v_0, (uint64_t)native_s_7, (uint64_t)native_s_8);
  native_s_10 = INT64_C(1);
  if (native_s_2.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_11 = native_s_2.payload.variant_0;
  if (__builtin_add_overflow(native_s_11, native_s_10, &native_s_12.payload.variant_0)) {
    native_s_12.tag = INT64_C(1);
  } else {
    native_s_12.tag = INT64_C(0);
  }
  switch (native_s_12.tag) {
  case INT64_C(0):
    native_s_14 = native_s_12;
  goto native_l14_7;
  case INT64_C(1):
    goto native_l14_6;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_6: ;
  native_s_13 = INT64_C(2);
  native_trap((uint32_t)native_s_13);
native_l14_7: ;
  native_s_15 = native_s_14.payload.variant_0;
  native_s_16 = (int64_t)native_text_length(native_v_0);
  if ((native_s_15 < INT64_C(0)) || (native_s_16 < native_s_15) ||
      (native_s_16 > (int64_t)native_text_length(native_v_0))) {
    native_trap(UINT32_C(3));
  }
  native_s_17 = native_text_slice((native_arena *)native_s_0, native_v_0, (uint64_t)native_s_15, (uint64_t)native_s_16);
  native_s_18 = (uint64_t)(uintptr_t)&native_m0_text_39;
  memset(&native_s_19, 0, sizeof native_s_19);
  if (native_text_index_of(native_s_17, native_s_18, &native_s_19.payload.variant_0)) {
    native_s_19.tag = INT64_C(0);
  } else {
    native_s_19.tag = INT64_C(1);
  }
  switch (native_s_19.tag) {
  case INT64_C(0):
    goto native_l14_9;
  case INT64_C(1):
    goto native_l14_8;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_8: ;
  native_s_20 = true;
  native_s_22 = native_s_20;
  goto native_l14_10;
native_l14_9: ;
  native_s_21 = false;
  native_s_22 = native_s_21;
  goto native_l14_10;
native_l14_10: ;
  if (native_s_22) {
    goto native_l14_11;
  } else {
    goto native_l14_12;
  }
native_l14_11: ;
  native_s_23 = native_m0_fn_11();
  native_s_58 = native_s_23;
  goto native_l14_33;
native_l14_12: ;
  native_s_24 = INT64_C(0);
  if (native_s_19.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_25 = native_s_19.payload.variant_0;
  if ((native_s_24 < INT64_C(0)) || (native_s_25 < native_s_24) ||
      (native_s_25 > (int64_t)native_text_length(native_s_17))) {
    native_trap(UINT32_C(3));
  }
  native_s_26 = native_text_slice((native_arena *)native_s_0, native_s_17, (uint64_t)native_s_24, (uint64_t)native_s_25);
  native_s_27 = INT64_C(1);
  if (native_s_19.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_28 = native_s_19.payload.variant_0;
  if (__builtin_add_overflow(native_s_28, native_s_27, &native_s_29.payload.variant_0)) {
    native_s_29.tag = INT64_C(1);
  } else {
    native_s_29.tag = INT64_C(0);
  }
  switch (native_s_29.tag) {
  case INT64_C(0):
    native_s_31 = native_s_29;
  goto native_l14_14;
  case INT64_C(1):
    goto native_l14_13;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_13: ;
  native_s_30 = INT64_C(2);
  native_trap((uint32_t)native_s_30);
native_l14_14: ;
  native_s_32 = native_s_31.payload.variant_0;
  native_s_33 = (int64_t)native_text_length(native_s_17);
  if ((native_s_32 < INT64_C(0)) || (native_s_33 < native_s_32) ||
      (native_s_33 > (int64_t)native_text_length(native_s_17))) {
    native_trap(UINT32_C(3));
  }
  native_s_34 = native_text_slice((native_arena *)native_s_0, native_s_17, (uint64_t)native_s_32, (uint64_t)native_s_33);
  native_s_35 = (uint64_t)(uintptr_t)&native_m0_text_39;
  memset(&native_s_36, 0, sizeof native_s_36);
  if (native_text_index_of(native_s_34, native_s_35, &native_s_36.payload.variant_0)) {
    native_s_36.tag = INT64_C(0);
  } else {
    native_s_36.tag = INT64_C(1);
  }
  switch (native_s_36.tag) {
  case INT64_C(0):
    goto native_l14_15;
  case INT64_C(1):
    goto native_l14_16;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_15: ;
  native_s_37 = true;
  native_s_39 = native_s_37;
  goto native_l14_17;
native_l14_16: ;
  native_s_38 = false;
  native_s_39 = native_s_38;
  goto native_l14_17;
native_l14_17: ;
  if (native_s_39) {
    goto native_l14_18;
  } else {
    goto native_l14_19;
  }
native_l14_18: ;
  native_s_40 = native_m0_fn_11();
  native_s_57 = native_s_40;
  goto native_l14_32;
native_l14_19: ;
  memset(&native_s_41, 0, sizeof native_s_41);
  if (native_text_parse_i64(native_s_26, &native_s_41.payload.variant_0)) {
    native_s_41.tag = INT64_C(0);
  } else {
    native_s_41.tag = INT64_C(1);
  }
  memset(&native_s_42, 0, sizeof native_s_42);
  if (native_text_parse_i64(native_s_34, &native_s_42.payload.variant_0)) {
    native_s_42.tag = INT64_C(0);
  } else {
    native_s_42.tag = INT64_C(1);
  }
  switch (native_s_41.tag) {
  case INT64_C(0):
    goto native_l14_21;
  case INT64_C(1):
    goto native_l14_20;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_20: ;
  native_s_43 = true;
  native_s_45 = native_s_43;
  goto native_l14_22;
native_l14_21: ;
  native_s_44 = false;
  native_s_45 = native_s_44;
  goto native_l14_22;
native_l14_22: ;
  if (native_s_45) {
    goto native_l14_23;
  } else {
    goto native_l14_24;
  }
native_l14_23: ;
  native_s_46 = native_m0_fn_11();
  native_s_56 = native_s_46;
  goto native_l14_31;
native_l14_24: ;
  switch (native_s_42.tag) {
  case INT64_C(0):
    goto native_l14_26;
  case INT64_C(1):
    goto native_l14_25;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_25: ;
  native_s_47 = true;
  native_s_49 = native_s_47;
  goto native_l14_27;
native_l14_26: ;
  native_s_48 = false;
  native_s_49 = native_s_48;
  goto native_l14_27;
native_l14_27: ;
  if (native_s_49) {
    goto native_l14_28;
  } else {
    goto native_l14_29;
  }
native_l14_28: ;
  native_s_50 = native_m0_fn_11();
  native_s_55 = native_s_50;
  goto native_l14_30;
native_l14_29: ;
  native_s_51 = true;
  if (native_s_41.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_52 = native_s_41.payload.variant_0;
  if (native_s_42.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_53 = native_s_42.payload.variant_0;
  native_s_54 = (native_m0_type_4){ .field_0 = native_s_9, .field_1 = native_s_52, .field_2 = native_s_53, .field_3 = native_s_51 };
  native_s_55 = native_s_54;
  goto native_l14_30;
native_l14_30: ;
  native_s_56 = native_s_55;
  goto native_l14_31;
native_l14_31: ;
  native_s_57 = native_s_56;
  goto native_l14_32;
native_l14_32: ;
  native_s_58 = native_s_57;
  goto native_l14_33;
native_l14_33: ;
  native_s_59 = native_s_58;
  goto native_l14_34;
native_l14_34: ;
  return native_s_59;
}
native_m0_type_2 native_m0_fn_15(native_m0_type_3 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_2 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_2 native_s_4;
  native_m0_type_2 native_s_5;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_40;
  native_s_1 = native_text_eq(native_v_0, native_s_0);
  if (native_s_1) {
    goto native_l15_2;
  } else {
    goto native_l15_1;
  }
native_l15_1: ;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_41;
  native_s_3 = native_text_eq(native_v_0, native_s_2);
  native_s_5 = native_s_3;
  goto native_l15_3;
native_l15_2: ;
  native_s_4 = true;
  native_s_5 = native_s_4;
  goto native_l15_3;
native_l15_3: ;
  return native_s_5;
}
native_m0_type_10 native_m0_fn_16(native_arena *arena, const native_capability *capability) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_3 native_s_3;
  native_m0_type_3 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_3 native_s_6;
  native_m0_type_3 native_s_7;
  native_m0_type_3 native_s_8;
  native_m0_type_3 native_s_9;
  native_m0_type_3 native_s_10;
  native_m0_type_3 native_s_11;
  native_m0_type_3 native_s_12;
  native_m0_type_3 native_s_13;
  native_m0_type_3 native_s_14;
  native_m0_type_3 native_s_15;
  native_m0_type_3 native_s_16;
  native_m0_type_3 native_s_17;
  native_m0_type_3 native_s_18;
  native_m0_type_3 native_s_19;
  native_m0_type_3 native_s_20;
  native_m0_type_3 native_s_21;
  native_m0_type_3 native_s_22;
  native_m0_type_3 native_s_23;
  native_m0_type_1 native_s_24;
  native_m0_type_10 native_s_25;
  native_m0_type_10 native_s_26;
  native_m0_type_10 native_s_27;
  native_m0_type_10 native_s_28;
  native_m0_type_10 native_s_29;
  native_m0_type_10 native_s_30;
  native_m0_type_10 native_s_31;
  native_m0_type_10 native_s_32;
  native_m0_type_10 native_s_33;
  native_m0_type_10 native_s_34;
  native_m0_type_10 native_s_35;
  native_m0_type_10 native_s_36;
  native_m0_type_10 native_s_37;
  native_m0_type_10 native_s_38;
  native_m0_type_10 native_s_39;
  native_m0_type_10 native_s_40;
  native_m0_type_10 native_s_41;
  native_m0_type_10 native_s_42;
  native_m0_type_10 native_s_43;
  native_m0_type_10 native_s_44;
  native_m0_type_10 native_s_45;
  native_m0_type_10 native_s_46;
  native_m0_type_10 native_s_47;
  native_m0_type_10 native_s_48;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_13;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_14;
  native_s_3 = (uint64_t)(uintptr_t)&native_m0_text_15;
  native_s_4 = (uint64_t)(uintptr_t)&native_m0_text_16;
  native_s_5 = (uint64_t)(uintptr_t)&native_m0_text_17;
  native_s_6 = (uint64_t)(uintptr_t)&native_m0_text_18;
  native_s_7 = (uint64_t)(uintptr_t)&native_m0_text_19;
  native_s_8 = (uint64_t)(uintptr_t)&native_m0_text_20;
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_text_21;
  native_s_10 = (uint64_t)(uintptr_t)&native_m0_text_22;
  native_s_11 = (uint64_t)(uintptr_t)&native_m0_text_23;
  native_s_12 = (uint64_t)(uintptr_t)&native_m0_text_10;
  native_s_13 = (uint64_t)(uintptr_t)&native_m0_text_24;
  native_s_14 = (uint64_t)(uintptr_t)&native_m0_text_25;
  native_s_15 = (uint64_t)(uintptr_t)&native_m0_text_26;
  native_s_16 = (uint64_t)(uintptr_t)&native_m0_text_27;
  native_s_17 = (uint64_t)(uintptr_t)&native_m0_text_28;
  native_s_18 = (uint64_t)(uintptr_t)&native_m0_text_29;
  native_s_19 = (uint64_t)(uintptr_t)&native_m0_text_30;
  native_s_20 = (uint64_t)(uintptr_t)&native_m0_text_31;
  native_s_21 = (uint64_t)(uintptr_t)&native_m0_text_32;
  native_s_22 = (uint64_t)(uintptr_t)&native_m0_text_33;
  native_s_23 = (uint64_t)(uintptr_t)&native_m0_text_34;
  native_s_24 = INT64_C(23);
  native_s_25 = native_vec_new((native_arena *)native_s_0, native_s_24, INT64_C(8), (size_t)8);
  native_s_26 = native_vec_push((native_arena *)native_s_0, native_s_25, &native_s_1, INT64_C(8), (size_t)8);
  native_s_27 = native_vec_push((native_arena *)native_s_0, native_s_26, &native_s_2, INT64_C(8), (size_t)8);
  native_s_28 = native_vec_push((native_arena *)native_s_0, native_s_27, &native_s_3, INT64_C(8), (size_t)8);
  native_s_29 = native_vec_push((native_arena *)native_s_0, native_s_28, &native_s_4, INT64_C(8), (size_t)8);
  native_s_30 = native_vec_push((native_arena *)native_s_0, native_s_29, &native_s_5, INT64_C(8), (size_t)8);
  native_s_31 = native_vec_push((native_arena *)native_s_0, native_s_30, &native_s_6, INT64_C(8), (size_t)8);
  native_s_32 = native_vec_push((native_arena *)native_s_0, native_s_31, &native_s_7, INT64_C(8), (size_t)8);
  native_s_33 = native_vec_push((native_arena *)native_s_0, native_s_32, &native_s_8, INT64_C(8), (size_t)8);
  native_s_34 = native_vec_push((native_arena *)native_s_0, native_s_33, &native_s_9, INT64_C(8), (size_t)8);
  native_s_35 = native_vec_push((native_arena *)native_s_0, native_s_34, &native_s_10, INT64_C(8), (size_t)8);
  native_s_36 = native_vec_push((native_arena *)native_s_0, native_s_35, &native_s_11, INT64_C(8), (size_t)8);
  native_s_37 = native_vec_push((native_arena *)native_s_0, native_s_36, &native_s_12, INT64_C(8), (size_t)8);
  native_s_38 = native_vec_push((native_arena *)native_s_0, native_s_37, &native_s_13, INT64_C(8), (size_t)8);
  native_s_39 = native_vec_push((native_arena *)native_s_0, native_s_38, &native_s_14, INT64_C(8), (size_t)8);
  native_s_40 = native_vec_push((native_arena *)native_s_0, native_s_39, &native_s_15, INT64_C(8), (size_t)8);
  native_s_41 = native_vec_push((native_arena *)native_s_0, native_s_40, &native_s_16, INT64_C(8), (size_t)8);
  native_s_42 = native_vec_push((native_arena *)native_s_0, native_s_41, &native_s_17, INT64_C(8), (size_t)8);
  native_s_43 = native_vec_push((native_arena *)native_s_0, native_s_42, &native_s_18, INT64_C(8), (size_t)8);
  native_s_44 = native_vec_push((native_arena *)native_s_0, native_s_43, &native_s_19, INT64_C(8), (size_t)8);
  native_s_45 = native_vec_push((native_arena *)native_s_0, native_s_44, &native_s_20, INT64_C(8), (size_t)8);
  native_s_46 = native_vec_push((native_arena *)native_s_0, native_s_45, &native_s_21, INT64_C(8), (size_t)8);
  native_s_47 = native_vec_push((native_arena *)native_s_0, native_s_46, &native_s_22, INT64_C(8), (size_t)8);
  native_s_48 = native_vec_push((native_arena *)native_s_0, native_s_47, &native_s_23, INT64_C(8), (size_t)8);
  return native_s_48;
}
native_m0_type_3 native_m0_fn_17(void) {
  native_m0_type_3 native_s_0;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_35;
  return native_s_0;
}
native_m0_type_10 native_m0_fn_18(native_arena *arena, const native_capability *capability) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_10 native_s_4;
  native_m0_type_10 native_s_5;
  native_m0_type_10 native_s_6;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_text_42;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_43;
  native_s_3 = INT64_C(2);
  native_s_4 = native_vec_new((native_arena *)native_s_0, native_s_3, INT64_C(8), (size_t)8);
  native_s_5 = native_vec_push((native_arena *)native_s_0, native_s_4, &native_s_1, INT64_C(8), (size_t)8);
  native_s_6 = native_vec_push((native_arena *)native_s_0, native_s_5, &native_s_2, INT64_C(8), (size_t)8);
  return native_s_6;
}
