/* Generated by native.body-c17; do not edit. */
#include "module_1.h"

struct native_m1_text_0_blob { uint64_t length; uint8_t bytes[sizeof "epoch"]; };
static const struct native_m1_text_0_blob native_m1_text_0 = { (uint64_t)(sizeof "epoch" - 1U), "epoch" };
_Static_assert(offsetof(struct native_m1_text_0_blob, bytes) == 8, "text blob is length-prefixed");

native_m1_type_2 native_m1_fn_0(native_arena *arena, const native_capability *capability, native_m1_type_2 native_v_0) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  native_m1_type_0 native_s_0;
  native_m1_type_2 native_s_1;
  native_m1_type_2 native_s_2;
  native_m1_type_2 native_s_3;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m1_text_0;
  (void)native_s_1;
  {
    const uint64_t native_parts_2[2] = { native_s_1, native_v_0 };
    native_s_2 = native_text_concat((native_arena *)native_s_0, native_parts_2, UINT64_C(2));
  }
  native_s_3 = native_s_2;
  return native_s_3;
}
native_m1_type_2 native_m1_fn_1(native_arena *arena, const native_capability *capability, native_m1_type_2 native_v_0) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  native_m1_type_0 native_s_0;
  native_m1_type_2 native_s_1;
  native_m1_type_2 native_s_2;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m1_text_0;
  (void)native_s_1;
  {
    const uint64_t native_parts_2[2] = { native_s_1, native_v_0 };
    native_s_2 = native_text_concat((native_arena *)native_s_0, native_parts_2, UINT64_C(2));
  }
  return native_s_2;
}
native_m1_type_1 native_m1_fn_2(native_m1_type_1 native_v_0) {
  (void)native_v_0;
  native_m1_type_1 native_s_0;
  native_m1_type_5 native_s_1;
  native_m1_type_1 native_s_2;
  native_m1_type_5 native_s_3;
  native_m1_type_1 native_s_4;
  native_m1_type_1 native_s_5;
  native_s_0 = INT64_C(1);
  (void)native_s_0;
  if (__builtin_add_overflow(native_v_0, native_s_0, &native_s_1.payload.variant_0)) {
    native_s_1.tag = INT64_C(1);
  } else {
    native_s_1.tag = INT64_C(0);
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    native_s_3 = native_s_1;
  goto native_l2_2;
  case INT64_C(1):
    goto native_l2_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l2_1: ;
  native_s_2 = INT64_C(2);
  (void)native_s_2;
  native_trap((uint32_t)native_s_2);
native_l2_2: ;
  native_s_4 = native_s_3.payload.variant_0;
  native_s_5 = native_s_4;
  return native_s_5;
}
native_m1_type_2 native_m1_fn_3(native_arena *arena, const native_capability *capability, native_m1_type_2 native_v_0) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  native_m1_type_0 native_s_0;
  native_m1_type_2 native_s_1;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = native_v_0;
  return native_s_1;
}
