/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

struct native_m0_text_0_blob { uint64_t length; uint8_t bytes[sizeof "fram usage: validate | tell <subject> <slot> <value> | retract <subject> <slot> <value> (alias: untell) | query <edn> | selfcheck --deep"]; };
static const struct native_m0_text_0_blob native_m0_text_0 = { (uint64_t)(sizeof "fram usage: validate | tell <subject> <slot> <value> | retract <subject> <slot> <value> (alias: untell) | query <edn> | selfcheck --deep" - 1U), "fram usage: validate | tell <subject> <slot> <value> | retract <subject> <slot> <value> (alias: untell) | query <edn> | selfcheck --deep" };
_Static_assert(offsetof(struct native_m0_text_0_blob, bytes) == 8, "text blob is length-prefixed");

native_m0_type_3 native_m0_fn_0(const native_capability *capability) {
  (void)capability;
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_0;
  (void)native_s_0;
  native_host_stdout_write_line_v0(capability, native_s_0);
  memset(&native_s_1, 0, sizeof native_s_1);
  return native_s_1;
}
