/* Generated by native.fold-c17; do not edit. */
#ifndef NATIVE_MODULE_0_ABI_H
#define NATIVE_MODULE_0_ABI_H

#include "native_shim.h"

typedef uint64_t native_m0_type_0;
_Static_assert(sizeof(native_m0_type_0) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_0) == 8, "layout alignment");

typedef int64_t native_m0_type_1;
_Static_assert(sizeof(native_m0_type_1) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_1) == 8, "layout alignment");

typedef struct native_m0_type_2 {
  native_m0_type_1 tag;
} native_m0_type_2;
_Static_assert(sizeof(native_m0_type_2) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_2) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_2, tag) == 0, "union tag offset");

typedef struct native_m0_type_3 {
  native_m0_type_1 tag;
} native_m0_type_3;
_Static_assert(sizeof(native_m0_type_3) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_3) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_3, tag) == 0, "union tag offset");

native_m0_type_3 native_m0_fn_0(const native_capability *capability);

#endif
