export type {
  IntegerInput,
  StringTerm,
  IntegerTerm,
  Float64Term,
  BooleanTerm,
  KeywordTerm,
  InstantTerm,
  TripleTerm,
  Term,
  TermInput,
  TransactionCoordinateTerm,
  OccurrenceCoordinateTerm,
  OccurrenceAction,
  Occurrence,
  QueryVariable,
  QueryTermInput,
  QueryHead,
  QueryRelationClause,
  QueryPredicateClause,
  QueryFunctionClause,
  QueryClause,
  QueryRule,
  QueryAggregate,
  QueryHaving,
  QueryAggregateFind,
  StructuredQueryRules,
  StructuredQueryStrata,
  StructuredQuery,
  TriplePattern,
  PageRequest,
  PageResponse,
  RequestOptions,
  PagedRequestOptions,
  ScanAllOptions,
  ScanAllResult,
  SinceSelector,
  QueryOptions,
  WriteOptions,
  BatchAction,
  BatchPreflight,
  BatchPreflightOptions,
  BatchOptions,
  StoreResponse,
  MutationActionResult,
  StatusResult,
  ValidationResult,
  StoreInstant,
  LeaseGrant,
  LeaseCheck,
  StoreClient,
  StoreNativeCheckpointResult,
  StoreTransportEntry,
  StoreTransportRequest,
  StoreTransport,
  StoreTransportClientOptions,
} from '@tompassarelli/beagle-store-rpc';

export {
  STORERPC_VERSION,
  STORERPC_MAX_BATCH_ACTIONS,
  STORERPC_MAX_PACKET_BYTES,
  StoreProtocolError,
  StoreTransportError,
  StoreRpcError,
  stringTerm,
  integerTerm,
  float64Term,
  booleanTerm,
  keywordTerm,
  instantTerm,
  tripleTerm,
  validateTerm,
  term,
  float64Value,
  integerValue,
  listValues,
  recordFields,
  lowerQueryPlan,
  tripleQuery,
  storeTransportCheckpoint,
  storeRpcDeclaredPacketBytes,
  scanAll,
} from '@tompassarelli/beagle-store-rpc';

import type {
  StoreClient,
  StoreTransportClientOptions,
} from '@tompassarelli/beagle-store-rpc';

/** Runtime-neutral Store RPC client over an injected exact-packet transport. */
export function storeClient(options: StoreTransportClientOptions): StoreClient;
