/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

struct native_m0_text_0_blob { uint64_t length; uint8_t bytes[sizeof "unknown op"]; };
static const struct native_m0_text_0_blob native_m0_text_0 = { (uint64_t)(sizeof "unknown op" - 1U), "unknown op" };
_Static_assert(offsetof(struct native_m0_text_0_blob, bytes) == 8, "text blob is length-prefixed");
struct native_m0_keyword_0_blob { uint64_t length; uint8_t bytes[sizeof "code"]; };
static const struct native_m0_keyword_0_blob native_m0_keyword_0 = { (uint64_t)(sizeof "code" - 1U), "code" };
_Static_assert(offsetof(struct native_m0_keyword_0_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_1_blob { uint64_t length; uint8_t bytes[sizeof "version"]; };
static const struct native_m0_keyword_1_blob native_m0_keyword_1 = { (uint64_t)(sizeof "version" - 1U), "version" };
_Static_assert(offsetof(struct native_m0_keyword_1_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_2_blob { uint64_t length; uint8_t bytes[sizeof "error"]; };
static const struct native_m0_keyword_2_blob native_m0_keyword_2 = { (uint64_t)(sizeof "error" - 1U), "error" };
_Static_assert(offsetof(struct native_m0_keyword_2_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_3_blob { uint64_t length; uint8_t bytes[sizeof "reject"]; };
static const struct native_m0_keyword_3_blob native_m0_keyword_3 = { (uint64_t)(sizeof "reject" - 1U), "reject" };
_Static_assert(offsetof(struct native_m0_keyword_3_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_4_blob { uint64_t length; uint8_t bytes[sizeof "other"]; };
static const struct native_m0_keyword_4_blob native_m0_keyword_4 = { (uint64_t)(sizeof "other" - 1U), "other" };
_Static_assert(offsetof(struct native_m0_keyword_4_blob, bytes) == 8, "keyword blob is length-prefixed");

native_m0_type_0 native_m0_fn_0(native_m0_type_4 native_v_0) {
  (void)native_v_0;
  native_m0_type_0 native_s_0;
  native_s_0 = native_v_0.field_0;
  return native_s_0;
}
native_m0_type_6 native_m0_fn_1(void) {
  native_m0_type_6 native_s_0;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  return native_s_0;
}
native_m0_type_1 native_m0_fn_2(native_m0_type_13 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l2_1;
  case INT64_C(1):
    goto native_l2_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l2_1: ;
  native_s_2 = true;
  (void)native_s_2;
  native_s_4 = native_s_2;
  goto native_l2_3;
native_l2_2: ;
  native_s_3 = false;
  (void)native_s_3;
  native_s_4 = native_s_3;
  goto native_l2_3;
native_l2_3: ;
  return native_s_4;
}
native_m0_type_1 native_m0_fn_3(native_m0_type_13 native_v_0, native_m0_type_0 native_v_1) {
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_0 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l3_1;
  case INT64_C(1):
    goto native_l3_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l3_1: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  native_s_3 = (native_v_1 == native_s_2);
  native_s_5 = native_s_3;
  goto native_l3_3;
native_l3_2: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l3_3;
native_l3_3: ;
  return native_s_5;
}
native_m0_type_0 native_m0_fn_4(native_m0_type_13 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_9 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_20 native_s_10;
  native_m0_type_0 native_s_11;
  native_m0_type_0 native_s_12;
  native_m0_type_0 native_s_13;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l4_5;
  case INT64_C(1):
    goto native_l4_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l4_1: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_1;
  (void)native_s_2;
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l4_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l4_4;
native_l4_3: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l4_4;
native_l4_4: ;
  native_s_8 = native_s_5;
  goto native_l4_7;
native_l4_5: ;
  native_s_6 = true;
  (void)native_s_6;
  native_s_8 = native_s_6;
  goto native_l4_7;
  native_s_7 = false;
  (void)native_s_7;
  native_s_8 = native_s_7;
  goto native_l4_7;
native_l4_7: ;
  if (native_s_8) {
    goto native_l4_8;
  } else {
    goto native_l4_9;
  }
native_l4_8: ;
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_9;
  {
    const void *native_map_hit_10 = native_map_get(native_v_0, &native_s_9, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_10, 0, sizeof native_s_10);
    if (native_map_hit_10 != NULL) {
      native_s_10.tag = INT64_C(0);
      native_s_10.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_10;
    } else {
      native_s_10.tag = INT64_C(1);
    }
  }
  if (native_s_10.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_11 = native_s_10.payload.variant_0;
  native_s_13 = native_s_11;
  goto native_l4_10;
native_l4_9: ;
  native_s_12 = INT64_C(-1);
  (void)native_s_12;
  native_s_13 = native_s_12;
  goto native_l4_10;
native_l4_10: ;
  return native_s_13;
}
native_m0_type_0 native_m0_fn_5(native_m0_type_13 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_9 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_20 native_s_10;
  native_m0_type_0 native_s_11;
  native_m0_type_0 native_s_12;
  native_m0_type_0 native_s_13;
  native_m0_type_0 native_s_14;
  native_m0_type_0 native_s_15;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l5_5;
  case INT64_C(1):
    goto native_l5_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l5_1: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_1;
  (void)native_s_2;
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l5_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l5_4;
native_l5_3: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l5_4;
native_l5_4: ;
  native_s_8 = native_s_5;
  goto native_l5_7;
native_l5_5: ;
  native_s_6 = true;
  (void)native_s_6;
  native_s_8 = native_s_6;
  goto native_l5_7;
  native_s_7 = false;
  (void)native_s_7;
  native_s_8 = native_s_7;
  goto native_l5_7;
native_l5_7: ;
  if (native_s_8) {
    goto native_l5_8;
  } else {
    goto native_l5_9;
  }
native_l5_8: ;
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_9;
  {
    const void *native_map_hit_10 = native_map_get(native_v_0, &native_s_9, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_10, 0, sizeof native_s_10);
    if (native_map_hit_10 != NULL) {
      native_s_10.tag = INT64_C(0);
      native_s_10.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_10;
    } else {
      native_s_10.tag = INT64_C(1);
    }
  }
  if (native_s_10.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_11 = native_s_10.payload.variant_0;
  native_s_13 = native_s_11;
  goto native_l5_10;
native_l5_9: ;
  native_s_12 = INT64_C(-1);
  (void)native_s_12;
  native_s_14 = native_s_12;
  goto native_l5_11;
native_l5_10: ;
  native_s_15 = native_s_13;
  goto native_l5_12;
native_l5_11: ;
  native_s_15 = native_s_14;
  goto native_l5_12;
native_l5_12: ;
  return native_s_15;
}
native_m0_type_0 native_m0_fn_6(native_m0_type_13 native_v_0, native_m0_type_0 native_v_1) {
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_0 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_6 native_s_6;
  native_m0_type_20 native_s_7;
  native_m0_type_0 native_s_8;
  native_m0_type_0 native_s_9;
  native_m0_type_0 native_s_10;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l6_1;
  case INT64_C(1):
    goto native_l6_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l6_1: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  native_s_3 = (native_v_1 == native_s_2);
  native_s_5 = native_s_3;
  goto native_l6_3;
native_l6_2: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l6_3;
native_l6_3: ;
  if (native_s_5) {
    goto native_l6_4;
  } else {
    goto native_l6_5;
  }
native_l6_4: ;
  native_s_6 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_6;
  {
    const void *native_map_hit_7 = native_map_get(native_v_0, &native_s_6, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_7, 0, sizeof native_s_7);
    if (native_map_hit_7 != NULL) {
      native_s_7.tag = INT64_C(0);
      native_s_7.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_7;
    } else {
      native_s_7.tag = INT64_C(1);
    }
  }
  if (native_s_7.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_8 = native_s_7.payload.variant_0;
  native_s_10 = native_s_8;
  goto native_l6_6;
native_l6_5: ;
  native_s_9 = INT64_C(-1);
  (void)native_s_9;
  native_s_10 = native_s_9;
  goto native_l6_6;
native_l6_6: ;
  return native_s_10;
}
native_m0_type_0 native_m0_fn_7(native_m0_type_11 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_24 native_s_1;
  native_m0_type_23 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_9 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_1 native_s_9;
  native_m0_type_1 native_s_10;
  native_m0_type_1 native_s_11;
  native_m0_type_1 native_s_12;
  native_m0_type_6 native_s_13;
  native_m0_type_24 native_s_14;
  native_m0_type_23 native_s_15;
  native_m0_type_0 native_s_16;
  native_m0_type_0 native_s_17;
  native_m0_type_0 native_s_18;
  native_m0_type_0 native_s_19;
  native_m0_type_0 native_s_20;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_1;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_23 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l7_1;
  case INT64_C(1):
    goto native_l7_5;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l7_1: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l7_3;
  case INT64_C(1):
    goto native_l7_2;
  case INT64_C(2):
    goto native_l7_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l7_2: ;
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l7_4;
native_l7_3: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l7_4;
native_l7_4: ;
  native_s_12 = native_s_5;
  goto native_l7_11;
native_l7_5: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = native_s_1.payload.variant_1;
  (void)native_s_6;
  switch (native_s_6.tag) {
  case INT64_C(0):
    goto native_l7_7;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_7 = true;
  (void)native_s_7;
  native_s_9 = native_s_7;
  goto native_l7_8;
native_l7_7: ;
  native_s_8 = false;
  (void)native_s_8;
  native_s_9 = native_s_8;
  goto native_l7_8;
native_l7_8: ;
  native_s_12 = native_s_9;
  goto native_l7_11;
  native_s_10 = true;
  (void)native_s_10;
  native_s_12 = native_s_10;
  goto native_l7_11;
  native_s_11 = false;
  (void)native_s_11;
  native_s_12 = native_s_11;
  goto native_l7_11;
native_l7_11: ;
  if (native_s_12) {
    goto native_l7_12;
  } else {
    goto native_l7_13;
  }
native_l7_12: ;
  native_s_13 = (uint64_t)(uintptr_t)&native_m0_keyword_1;
  (void)native_s_13;
  {
    const void *native_map_hit_14 = native_map_get(native_v_0, &native_s_13, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_14, 0, sizeof native_s_14);
    if (native_map_hit_14 != NULL) {
      native_s_14.tag = INT64_C(0);
      native_s_14.payload.variant_0 = *(const native_m0_type_23 *)native_map_hit_14;
    } else {
      native_s_14.tag = INT64_C(1);
    }
  }
  if (native_s_14.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_15 = native_s_14.payload.variant_0;
  if (native_s_15.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_16 = native_s_15.payload.variant_1;
  native_s_18 = native_s_16;
  goto native_l7_14;
native_l7_13: ;
  native_s_17 = INT64_C(-3);
  (void)native_s_17;
  native_s_19 = native_s_17;
  goto native_l7_15;
native_l7_14: ;
  native_s_20 = native_s_18;
  goto native_l7_16;
native_l7_15: ;
  native_s_20 = native_s_19;
  goto native_l7_16;
native_l7_16: ;
  return native_s_20;
}
native_m0_type_19 native_m0_fn_8(native_m0_type_10 native_v_0) {
  (void)native_v_0;
  native_m0_type_3 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_22 native_s_2;
  native_m0_type_21 native_s_3;
  native_m0_type_3 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_1 native_s_9;
  native_m0_type_9 native_s_10;
  native_m0_type_9 native_s_11;
  native_m0_type_19 native_s_12;
  native_m0_type_10 native_s_13;
  native_m0_type_19 native_s_14;
  native_m0_type_19 native_s_15;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_text_0;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_keyword_2;
  (void)native_s_1;
  {
    const void *native_map_hit_2 = native_map_get(native_v_0, &native_s_1, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_2, 0, sizeof native_s_2);
    if (native_map_hit_2 != NULL) {
      native_s_2.tag = INT64_C(0);
      native_s_2.payload.variant_0 = *(const native_m0_type_21 *)native_map_hit_2;
    } else {
      native_s_2.tag = INT64_C(1);
    }
  }
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l8_1;
  case INT64_C(1):
    goto native_l8_5;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l8_1: ;
  if (native_s_2.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = native_s_2.payload.variant_0;
  switch (native_s_3.tag) {
  case INT64_C(0):
    goto native_l8_2;
  case INT64_C(1):
    goto native_l8_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l8_2: ;
  if (native_s_3.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_4 = native_s_3.payload.variant_0;
  native_s_5 = native_text_eq(native_s_0, native_s_4);
  native_s_7 = native_s_5;
  goto native_l8_4;
native_l8_3: ;
  native_s_6 = false;
  (void)native_s_6;
  native_s_7 = native_s_6;
  goto native_l8_4;
native_l8_4: ;
  native_s_9 = native_s_7;
  goto native_l8_6;
native_l8_5: ;
  native_s_8 = false;
  (void)native_s_8;
  native_s_9 = native_s_8;
  goto native_l8_6;
native_l8_6: ;
  if (native_s_9) {
    goto native_l8_7;
  } else {
    goto native_l8_8;
  }
native_l8_7: ;
  native_s_10 = (native_m0_type_9){ .tag = INT64_C(0) };
  native_s_11 = native_s_10;
  goto native_l8_9;
native_l8_8: ;
  native_s_13 = native_v_0;
  goto native_l8_10;
native_l8_9: ;
  native_s_12 = (native_m0_type_19){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_11 } };
  native_s_15 = native_s_12;
  goto native_l8_11;
native_l8_10: ;
  native_s_14 = (native_m0_type_19){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_13 } };
  native_s_15 = native_s_14;
  goto native_l8_11;
native_l8_11: ;
  return native_s_15;
}
native_m0_type_0 native_m0_fn_9(native_m0_type_14 native_v_0) {
  (void)native_v_0;
  native_m0_type_0 native_s_0;
  native_s_0 = native_vec_length(native_v_0);
  return native_s_0;
}
native_m0_type_0 native_m0_fn_10(native_m0_type_12 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_26 native_s_1;
  native_m0_type_25 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_26 native_s_10;
  native_m0_type_25 native_s_11;
  native_m0_type_14 native_s_12;
  native_m0_type_0 native_s_13;
  native_m0_type_0 native_s_14;
  native_m0_type_0 native_s_15;
  native_m0_type_0 native_s_16;
  native_m0_type_0 native_s_17;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_3;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_25 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l10_1;
  case INT64_C(1):
    goto native_l10_6;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l10_1: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l10_2;
  case INT64_C(1):
    goto native_l10_2;
  case INT64_C(2):
    goto native_l10_2;
  case INT64_C(3):
    goto native_l10_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l10_2: ;
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l10_4;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l10_4;
native_l10_4: ;
  native_s_8 = native_s_5;
  goto native_l10_7;
  native_s_6 = true;
  (void)native_s_6;
  native_s_8 = native_s_6;
  goto native_l10_7;
native_l10_6: ;
  native_s_7 = false;
  (void)native_s_7;
  native_s_8 = native_s_7;
  goto native_l10_7;
native_l10_7: ;
  if (native_s_8) {
    goto native_l10_8;
  } else {
    goto native_l10_9;
  }
native_l10_8: ;
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_keyword_3;
  (void)native_s_9;
  {
    const void *native_map_hit_10 = native_map_get(native_v_0, &native_s_9, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_10, 0, sizeof native_s_10);
    if (native_map_hit_10 != NULL) {
      native_s_10.tag = INT64_C(0);
      native_s_10.payload.variant_0 = *(const native_m0_type_25 *)native_map_hit_10;
    } else {
      native_s_10.tag = INT64_C(1);
    }
  }
  if (native_s_10.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_11 = native_s_10.payload.variant_0;
  if (native_s_11.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_12 = native_s_11.payload.variant_3;
  native_s_13 = native_m0_fn_9(native_s_12);
  native_s_15 = native_s_13;
  goto native_l10_10;
native_l10_9: ;
  native_s_14 = INT64_C(-1);
  (void)native_s_14;
  native_s_16 = native_s_14;
  goto native_l10_11;
native_l10_10: ;
  native_s_17 = native_s_15;
  goto native_l10_12;
native_l10_11: ;
  native_s_17 = native_s_16;
  goto native_l10_12;
native_l10_12: ;
  return native_s_17;
}
native_m0_type_20 native_m0_fn_11(native_m0_type_13 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_9 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_20 native_s_10;
  native_m0_type_6 native_s_11;
  native_m0_type_20 native_s_12;
  native_m0_type_20 native_s_13;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l11_5;
  case INT64_C(1):
    goto native_l11_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l11_1: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_1;
  (void)native_s_2;
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l11_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l11_4;
native_l11_3: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l11_4;
native_l11_4: ;
  native_s_8 = native_s_5;
  goto native_l11_7;
native_l11_5: ;
  native_s_6 = true;
  (void)native_s_6;
  native_s_8 = native_s_6;
  goto native_l11_7;
  native_s_7 = false;
  (void)native_s_7;
  native_s_8 = native_s_7;
  goto native_l11_7;
native_l11_7: ;
  if (native_s_8) {
    goto native_l11_8;
  } else {
    goto native_l11_9;
  }
native_l11_8: ;
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_keyword_4;
  (void)native_s_9;
  {
    const void *native_map_hit_10 = native_map_get(native_v_0, &native_s_9, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_10, 0, sizeof native_s_10);
    if (native_map_hit_10 != NULL) {
      native_s_10.tag = INT64_C(0);
      native_s_10.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_10;
    } else {
      native_s_10.tag = INT64_C(1);
    }
  }
  native_s_13 = native_s_10;
  goto native_l11_10;
native_l11_9: ;
  native_s_11 = (uint64_t)(uintptr_t)&native_m0_keyword_4;
  (void)native_s_11;
  {
    const void *native_map_hit_12 = native_map_get(native_v_0, &native_s_11, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_12, 0, sizeof native_s_12);
    if (native_map_hit_12 != NULL) {
      native_s_12.tag = INT64_C(0);
      native_s_12.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_12;
    } else {
      native_s_12.tag = INT64_C(1);
    }
  }
  native_s_13 = native_s_12;
  goto native_l11_10;
native_l11_10: ;
  return native_s_13;
}
native_m0_type_20 native_m0_fn_12(native_m0_type_13 native_v_0, native_m0_type_13 native_v_1) {
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_9 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_20 native_s_10;
  native_m0_type_6 native_s_11;
  native_m0_type_20 native_s_12;
  native_m0_type_20 native_s_13;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l12_5;
  case INT64_C(1):
    goto native_l12_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l12_1: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_1;
  (void)native_s_2;
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l12_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l12_4;
native_l12_3: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l12_4;
native_l12_4: ;
  native_s_8 = native_s_5;
  goto native_l12_7;
native_l12_5: ;
  native_s_6 = true;
  (void)native_s_6;
  native_s_8 = native_s_6;
  goto native_l12_7;
  native_s_7 = false;
  (void)native_s_7;
  native_s_8 = native_s_7;
  goto native_l12_7;
native_l12_7: ;
  if (native_s_8) {
    goto native_l12_8;
  } else {
    goto native_l12_9;
  }
native_l12_8: ;
  native_s_9 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_9;
  {
    const void *native_map_hit_10 = native_map_get(native_v_1, &native_s_9, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_10, 0, sizeof native_s_10);
    if (native_map_hit_10 != NULL) {
      native_s_10.tag = INT64_C(0);
      native_s_10.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_10;
    } else {
      native_s_10.tag = INT64_C(1);
    }
  }
  native_s_13 = native_s_10;
  goto native_l12_10;
native_l12_9: ;
  native_s_11 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_11;
  {
    const void *native_map_hit_12 = native_map_get(native_v_1, &native_s_11, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_12, 0, sizeof native_s_12);
    if (native_map_hit_12 != NULL) {
      native_s_12.tag = INT64_C(0);
      native_s_12.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_12;
    } else {
      native_s_12.tag = INT64_C(1);
    }
  }
  native_s_13 = native_s_12;
  goto native_l12_10;
native_l12_10: ;
  return native_s_13;
}
native_m0_type_20 native_m0_fn_13(native_m0_type_13 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_20 native_s_1;
  native_m0_type_9 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_0 native_s_9;
  native_m0_type_6 native_s_10;
  native_m0_type_20 native_s_11;
  native_m0_type_0 native_s_12;
  native_m0_type_20 native_s_13;
  native_m0_type_20 native_s_14;
  native_m0_type_20 native_s_15;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  {
    const void *native_map_hit_1 = native_map_get(native_v_0, &native_s_0, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_1, 0, sizeof native_s_1);
    if (native_map_hit_1 != NULL) {
      native_s_1.tag = INT64_C(0);
      native_s_1.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_1;
    } else {
      native_s_1.tag = INT64_C(1);
    }
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l13_5;
  case INT64_C(1):
    goto native_l13_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l13_1: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_1;
  (void)native_s_2;
  switch (native_s_2.tag) {
  case INT64_C(0):
    goto native_l13_3;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l13_4;
native_l13_3: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l13_4;
native_l13_4: ;
  native_s_8 = native_s_5;
  goto native_l13_7;
native_l13_5: ;
  native_s_6 = true;
  (void)native_s_6;
  native_s_8 = native_s_6;
  goto native_l13_7;
  native_s_7 = false;
  (void)native_s_7;
  native_s_8 = native_s_7;
  goto native_l13_7;
native_l13_7: ;
  if (native_s_8) {
    goto native_l13_8;
  } else {
    goto native_l13_9;
  }
native_l13_8: ;
  native_s_9 = INT64_C(-1);
  (void)native_s_9;
  native_s_12 = native_s_9;
  goto native_l13_10;
native_l13_9: ;
  native_s_10 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_10;
  {
    const void *native_map_hit_11 = native_map_get(native_v_0, &native_s_10, NATIVE_COLLECTION_EQ_KEYWORD);
    memset(&native_s_11, 0, sizeof native_s_11);
    if (native_map_hit_11 != NULL) {
      native_s_11.tag = INT64_C(0);
      native_s_11.payload.variant_0 = *(const native_m0_type_0 *)native_map_hit_11;
    } else {
      native_s_11.tag = INT64_C(1);
    }
  }
  native_s_14 = native_s_11;
  goto native_l13_11;
native_l13_10: ;
  native_s_13 = (native_m0_type_20){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_12 } };
  native_s_15 = native_s_13;
  goto native_l13_12;
native_l13_11: ;
  native_s_15 = native_s_14;
  goto native_l13_12;
native_l13_12: ;
  return native_s_15;
}
native_m0_type_3 native_m0_fn_14(native_m0_type_5 native_v_0) {
  (void)native_v_0;
  native_m0_type_3 native_s_0;
  native_s_0 = native_v_0.field_0;
  return native_s_0;
}
native_m0_type_3 native_m0_fn_15(native_m0_type_3 native_v_0) {
  (void)native_v_0;
  native_m0_type_5 native_s_0;
  native_m0_type_3 native_s_1;
  native_s_0 = (native_m0_type_5){ .field_0 = native_v_0 };
  native_s_1 = native_s_0.field_0;
  return native_s_1;
}
native_m0_type_27 native_m0_fn_16(native_m0_type_17 native_v_0) {
  (void)native_v_0;
  native_m0_type_1 native_s_0;
  native_m0_type_16 native_s_1;
  native_m0_type_5 native_s_2;
  native_m0_type_3 native_s_3;
  native_m0_type_9 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_27 native_s_6;
  native_m0_type_9 native_s_7;
  native_m0_type_27 native_s_8;
  native_m0_type_27 native_s_9;
  native_s_0 = native_m0_fn_18(native_v_0);
  if (native_s_0) {
    goto native_l16_1;
  } else {
    goto native_l16_2;
  }
native_l16_1: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_1 = native_v_0.payload.variant_7;
  if (native_s_1 == NULL) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = *((const native_m0_type_5 *)native_s_1);
  native_s_3 = native_s_2.field_0;
  native_s_5 = native_s_3;
  goto native_l16_3;
native_l16_2: ;
  native_s_4 = (native_m0_type_9){ .tag = INT64_C(0) };
  native_s_7 = native_s_4;
  goto native_l16_4;
native_l16_3: ;
  native_s_6 = (native_m0_type_27){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_5 } };
  native_s_9 = native_s_6;
  goto native_l16_5;
native_l16_4: ;
  native_s_8 = (native_m0_type_27){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_7 } };
  native_s_9 = native_s_8;
  goto native_l16_5;
native_l16_5: ;
  return native_s_9;
}
native_m0_type_27 native_m0_fn_17(native_m0_type_18 native_v_0) {
  (void)native_v_0;
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_9 native_s_3;
  native_m0_type_9 native_s_4;
  native_m0_type_16 native_s_5;
  native_m0_type_5 native_s_6;
  native_m0_type_3 native_s_7;
  native_m0_type_9 native_s_8;
  native_m0_type_27 native_s_9;
  native_m0_type_3 native_s_10;
  native_m0_type_27 native_s_11;
  native_m0_type_27 native_s_12;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l17_2;
  case INT64_C(1):
    goto native_l17_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l17_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l17_3;
native_l17_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l17_3;
native_l17_3: ;
  if (native_s_2) {
    goto native_l17_4;
  } else {
    goto native_l17_5;
  }
native_l17_4: ;
  native_s_3 = (native_m0_type_9){ .tag = INT64_C(0) };
  (void)native_s_3;
  native_s_4 = (native_m0_type_9){ .tag = INT64_C(0) };
  native_s_8 = native_s_4;
  goto native_l17_6;
native_l17_5: ;
  if (native_v_0.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_5 = native_v_0.payload.variant_0;
  if (native_s_5 == NULL) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = *((const native_m0_type_5 *)native_s_5);
  native_s_7 = native_s_6.field_0;
  native_s_10 = native_s_7;
  goto native_l17_7;
native_l17_6: ;
  native_s_9 = (native_m0_type_27){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_8 } };
  native_s_12 = native_s_9;
  goto native_l17_8;
native_l17_7: ;
  native_s_11 = (native_m0_type_27){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_10 } };
  native_s_12 = native_s_11;
  goto native_l17_8;
native_l17_8: ;
  return native_s_12;
}
native_m0_type_1 native_m0_fn_18(native_m0_type_17 native_v_0) {
  (void)native_v_0;
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l18_2;
  case INT64_C(1):
    goto native_l18_2;
  case INT64_C(2):
    goto native_l18_2;
  case INT64_C(3):
    goto native_l18_2;
  case INT64_C(4):
    goto native_l18_2;
  case INT64_C(5):
    goto native_l18_2;
  case INT64_C(6):
    goto native_l18_2;
  case INT64_C(7):
    goto native_l18_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l18_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l18_3;
native_l18_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l18_3;
native_l18_3: ;
  return native_s_2;
}
