/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

native_m0_type_3 native_m0_fn_0(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l0_2;
  case INT64_C(1):
    goto native_l0_2;
  case INT64_C(2):
    goto native_l0_2;
  case INT64_C(3):
    goto native_l0_2;
  case INT64_C(4):
    goto native_l0_2;
  case INT64_C(5):
    goto native_l0_2;
  case INT64_C(6):
    goto native_l0_1;
  case INT64_C(7):
    goto native_l0_2;
  case INT64_C(8):
    goto native_l0_2;
  case INT64_C(9):
    goto native_l0_2;
  case INT64_C(10):
    goto native_l0_2;
  case INT64_C(11):
    goto native_l0_2;
  case INT64_C(12):
    goto native_l0_2;
  case INT64_C(13):
    goto native_l0_2;
  case INT64_C(14):
    goto native_l0_2;
  case INT64_C(15):
    goto native_l0_2;
  case INT64_C(16):
    goto native_l0_2;
  case INT64_C(17):
    goto native_l0_2;
  case INT64_C(18):
    goto native_l0_2;
  case INT64_C(19):
    goto native_l0_2;
  case INT64_C(20):
    goto native_l0_2;
  case INT64_C(21):
    goto native_l0_2;
  case INT64_C(22):
    goto native_l0_2;
  case INT64_C(23):
    goto native_l0_2;
  case INT64_C(24):
    goto native_l0_2;
  case INT64_C(25):
    goto native_l0_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l0_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l0_3;
native_l0_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l0_3;
native_l0_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_1(native_m0_type_0 native_v_0, native_m0_type_0 native_v_1) {
  native_m0_type_0 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_0 native_s_3;
  native_m0_type_3 native_s_4;
  native_m0_type_3 native_s_5;
  native_m0_type_6 native_s_6;
  native_m0_type_0 native_s_7;
  native_m0_type_6 native_s_8;
  native_s_0 = INT64_C(0);
  native_s_1 = (native_s_0 <= native_v_1);
  if (native_s_1) {
    goto native_l1_2;
  } else {
    goto native_l1_1;
  }
native_l1_1: ;
  native_s_2 = false;
  native_s_5 = native_s_2;
  goto native_l1_3;
native_l1_2: ;
  native_s_3 = INT64_C(1000000000);
  native_s_4 = (native_v_1 < native_s_3);
  native_s_5 = native_s_4;
  goto native_l1_3;
native_l1_3: ;
  if (native_s_5) {
    goto native_l1_4;
  } else {
    goto native_l1_5;
  }
native_l1_4: ;
  native_s_6 = (native_m0_type_6){ .field_0 = native_v_0, .field_1 = native_v_1 };
  native_s_8 = native_s_6;
  goto native_l1_6;
native_l1_5: ;
  native_s_7 = INT64_C(1);
  native_trap((uint32_t)native_s_7);
native_l1_6: ;
  return native_s_8;
}
native_m0_type_3 native_m0_fn_2(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l2_2;
  case INT64_C(1):
    goto native_l2_2;
  case INT64_C(2):
    goto native_l2_2;
  case INT64_C(3):
    goto native_l2_2;
  case INT64_C(4):
    goto native_l2_2;
  case INT64_C(5):
    goto native_l2_2;
  case INT64_C(6):
    goto native_l2_2;
  case INT64_C(7):
    goto native_l2_1;
  case INT64_C(8):
    goto native_l2_2;
  case INT64_C(9):
    goto native_l2_2;
  case INT64_C(10):
    goto native_l2_2;
  case INT64_C(11):
    goto native_l2_2;
  case INT64_C(12):
    goto native_l2_2;
  case INT64_C(13):
    goto native_l2_2;
  case INT64_C(14):
    goto native_l2_2;
  case INT64_C(15):
    goto native_l2_2;
  case INT64_C(16):
    goto native_l2_2;
  case INT64_C(17):
    goto native_l2_2;
  case INT64_C(18):
    goto native_l2_2;
  case INT64_C(19):
    goto native_l2_2;
  case INT64_C(20):
    goto native_l2_2;
  case INT64_C(21):
    goto native_l2_2;
  case INT64_C(22):
    goto native_l2_2;
  case INT64_C(23):
    goto native_l2_2;
  case INT64_C(24):
    goto native_l2_2;
  case INT64_C(25):
    goto native_l2_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l2_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l2_3;
native_l2_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l2_3;
native_l2_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_3(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l3_2;
  case INT64_C(1):
    goto native_l3_2;
  case INT64_C(2):
    goto native_l3_2;
  case INT64_C(3):
    goto native_l3_2;
  case INT64_C(4):
    goto native_l3_2;
  case INT64_C(5):
    goto native_l3_2;
  case INT64_C(6):
    goto native_l3_2;
  case INT64_C(7):
    goto native_l3_2;
  case INT64_C(8):
    goto native_l3_1;
  case INT64_C(9):
    goto native_l3_2;
  case INT64_C(10):
    goto native_l3_2;
  case INT64_C(11):
    goto native_l3_2;
  case INT64_C(12):
    goto native_l3_2;
  case INT64_C(13):
    goto native_l3_2;
  case INT64_C(14):
    goto native_l3_2;
  case INT64_C(15):
    goto native_l3_2;
  case INT64_C(16):
    goto native_l3_2;
  case INT64_C(17):
    goto native_l3_2;
  case INT64_C(18):
    goto native_l3_2;
  case INT64_C(19):
    goto native_l3_2;
  case INT64_C(20):
    goto native_l3_2;
  case INT64_C(21):
    goto native_l3_2;
  case INT64_C(22):
    goto native_l3_2;
  case INT64_C(23):
    goto native_l3_2;
  case INT64_C(24):
    goto native_l3_2;
  case INT64_C(25):
    goto native_l3_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l3_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l3_3;
native_l3_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l3_3;
native_l3_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_4(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l4_2;
  case INT64_C(1):
    goto native_l4_2;
  case INT64_C(2):
    goto native_l4_2;
  case INT64_C(3):
    goto native_l4_2;
  case INT64_C(4):
    goto native_l4_2;
  case INT64_C(5):
    goto native_l4_2;
  case INT64_C(6):
    goto native_l4_2;
  case INT64_C(7):
    goto native_l4_2;
  case INT64_C(8):
    goto native_l4_2;
  case INT64_C(9):
    goto native_l4_1;
  case INT64_C(10):
    goto native_l4_2;
  case INT64_C(11):
    goto native_l4_2;
  case INT64_C(12):
    goto native_l4_2;
  case INT64_C(13):
    goto native_l4_2;
  case INT64_C(14):
    goto native_l4_2;
  case INT64_C(15):
    goto native_l4_2;
  case INT64_C(16):
    goto native_l4_2;
  case INT64_C(17):
    goto native_l4_2;
  case INT64_C(18):
    goto native_l4_2;
  case INT64_C(19):
    goto native_l4_2;
  case INT64_C(20):
    goto native_l4_2;
  case INT64_C(21):
    goto native_l4_2;
  case INT64_C(22):
    goto native_l4_2;
  case INT64_C(23):
    goto native_l4_2;
  case INT64_C(24):
    goto native_l4_2;
  case INT64_C(25):
    goto native_l4_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l4_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l4_3;
native_l4_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l4_3;
native_l4_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_5(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l5_2;
  case INT64_C(1):
    goto native_l5_2;
  case INT64_C(2):
    goto native_l5_2;
  case INT64_C(3):
    goto native_l5_2;
  case INT64_C(4):
    goto native_l5_2;
  case INT64_C(5):
    goto native_l5_2;
  case INT64_C(6):
    goto native_l5_2;
  case INT64_C(7):
    goto native_l5_2;
  case INT64_C(8):
    goto native_l5_2;
  case INT64_C(9):
    goto native_l5_2;
  case INT64_C(10):
    goto native_l5_1;
  case INT64_C(11):
    goto native_l5_2;
  case INT64_C(12):
    goto native_l5_2;
  case INT64_C(13):
    goto native_l5_2;
  case INT64_C(14):
    goto native_l5_2;
  case INT64_C(15):
    goto native_l5_2;
  case INT64_C(16):
    goto native_l5_2;
  case INT64_C(17):
    goto native_l5_2;
  case INT64_C(18):
    goto native_l5_2;
  case INT64_C(19):
    goto native_l5_2;
  case INT64_C(20):
    goto native_l5_2;
  case INT64_C(21):
    goto native_l5_2;
  case INT64_C(22):
    goto native_l5_2;
  case INT64_C(23):
    goto native_l5_2;
  case INT64_C(24):
    goto native_l5_2;
  case INT64_C(25):
    goto native_l5_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l5_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l5_3;
native_l5_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l5_3;
native_l5_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_6(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l6_2;
  case INT64_C(1):
    goto native_l6_2;
  case INT64_C(2):
    goto native_l6_2;
  case INT64_C(3):
    goto native_l6_2;
  case INT64_C(4):
    goto native_l6_2;
  case INT64_C(5):
    goto native_l6_2;
  case INT64_C(6):
    goto native_l6_2;
  case INT64_C(7):
    goto native_l6_2;
  case INT64_C(8):
    goto native_l6_2;
  case INT64_C(9):
    goto native_l6_2;
  case INT64_C(10):
    goto native_l6_2;
  case INT64_C(11):
    goto native_l6_1;
  case INT64_C(12):
    goto native_l6_2;
  case INT64_C(13):
    goto native_l6_2;
  case INT64_C(14):
    goto native_l6_2;
  case INT64_C(15):
    goto native_l6_2;
  case INT64_C(16):
    goto native_l6_2;
  case INT64_C(17):
    goto native_l6_2;
  case INT64_C(18):
    goto native_l6_2;
  case INT64_C(19):
    goto native_l6_2;
  case INT64_C(20):
    goto native_l6_2;
  case INT64_C(21):
    goto native_l6_2;
  case INT64_C(22):
    goto native_l6_2;
  case INT64_C(23):
    goto native_l6_2;
  case INT64_C(24):
    goto native_l6_2;
  case INT64_C(25):
    goto native_l6_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l6_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l6_3;
native_l6_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l6_3;
native_l6_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_7(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l7_2;
  case INT64_C(1):
    goto native_l7_2;
  case INT64_C(2):
    goto native_l7_2;
  case INT64_C(3):
    goto native_l7_2;
  case INT64_C(4):
    goto native_l7_2;
  case INT64_C(5):
    goto native_l7_2;
  case INT64_C(6):
    goto native_l7_2;
  case INT64_C(7):
    goto native_l7_2;
  case INT64_C(8):
    goto native_l7_2;
  case INT64_C(9):
    goto native_l7_2;
  case INT64_C(10):
    goto native_l7_2;
  case INT64_C(11):
    goto native_l7_2;
  case INT64_C(12):
    goto native_l7_1;
  case INT64_C(13):
    goto native_l7_2;
  case INT64_C(14):
    goto native_l7_2;
  case INT64_C(15):
    goto native_l7_2;
  case INT64_C(16):
    goto native_l7_2;
  case INT64_C(17):
    goto native_l7_2;
  case INT64_C(18):
    goto native_l7_2;
  case INT64_C(19):
    goto native_l7_2;
  case INT64_C(20):
    goto native_l7_2;
  case INT64_C(21):
    goto native_l7_2;
  case INT64_C(22):
    goto native_l7_2;
  case INT64_C(23):
    goto native_l7_2;
  case INT64_C(24):
    goto native_l7_2;
  case INT64_C(25):
    goto native_l7_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l7_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l7_3;
native_l7_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l7_3;
native_l7_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_8(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l8_2;
  case INT64_C(1):
    goto native_l8_2;
  case INT64_C(2):
    goto native_l8_2;
  case INT64_C(3):
    goto native_l8_2;
  case INT64_C(4):
    goto native_l8_2;
  case INT64_C(5):
    goto native_l8_2;
  case INT64_C(6):
    goto native_l8_2;
  case INT64_C(7):
    goto native_l8_2;
  case INT64_C(8):
    goto native_l8_2;
  case INT64_C(9):
    goto native_l8_2;
  case INT64_C(10):
    goto native_l8_2;
  case INT64_C(11):
    goto native_l8_2;
  case INT64_C(12):
    goto native_l8_2;
  case INT64_C(13):
    goto native_l8_1;
  case INT64_C(14):
    goto native_l8_2;
  case INT64_C(15):
    goto native_l8_2;
  case INT64_C(16):
    goto native_l8_2;
  case INT64_C(17):
    goto native_l8_2;
  case INT64_C(18):
    goto native_l8_2;
  case INT64_C(19):
    goto native_l8_2;
  case INT64_C(20):
    goto native_l8_2;
  case INT64_C(21):
    goto native_l8_2;
  case INT64_C(22):
    goto native_l8_2;
  case INT64_C(23):
    goto native_l8_2;
  case INT64_C(24):
    goto native_l8_2;
  case INT64_C(25):
    goto native_l8_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l8_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l8_3;
native_l8_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l8_3;
native_l8_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_9(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l9_2;
  case INT64_C(1):
    goto native_l9_2;
  case INT64_C(2):
    goto native_l9_2;
  case INT64_C(3):
    goto native_l9_2;
  case INT64_C(4):
    goto native_l9_2;
  case INT64_C(5):
    goto native_l9_2;
  case INT64_C(6):
    goto native_l9_2;
  case INT64_C(7):
    goto native_l9_2;
  case INT64_C(8):
    goto native_l9_2;
  case INT64_C(9):
    goto native_l9_2;
  case INT64_C(10):
    goto native_l9_2;
  case INT64_C(11):
    goto native_l9_2;
  case INT64_C(12):
    goto native_l9_2;
  case INT64_C(13):
    goto native_l9_2;
  case INT64_C(14):
    goto native_l9_2;
  case INT64_C(15):
    goto native_l9_2;
  case INT64_C(16):
    goto native_l9_2;
  case INT64_C(17):
    goto native_l9_2;
  case INT64_C(18):
    goto native_l9_2;
  case INT64_C(19):
    goto native_l9_2;
  case INT64_C(20):
    goto native_l9_2;
  case INT64_C(21):
    goto native_l9_2;
  case INT64_C(22):
    goto native_l9_1;
  case INT64_C(23):
    goto native_l9_2;
  case INT64_C(24):
    goto native_l9_2;
  case INT64_C(25):
    goto native_l9_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l9_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l9_3;
native_l9_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l9_3;
native_l9_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_10(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l10_2;
  case INT64_C(1):
    goto native_l10_2;
  case INT64_C(2):
    goto native_l10_2;
  case INT64_C(3):
    goto native_l10_2;
  case INT64_C(4):
    goto native_l10_2;
  case INT64_C(5):
    goto native_l10_2;
  case INT64_C(6):
    goto native_l10_2;
  case INT64_C(7):
    goto native_l10_2;
  case INT64_C(8):
    goto native_l10_2;
  case INT64_C(9):
    goto native_l10_2;
  case INT64_C(10):
    goto native_l10_2;
  case INT64_C(11):
    goto native_l10_2;
  case INT64_C(12):
    goto native_l10_2;
  case INT64_C(13):
    goto native_l10_2;
  case INT64_C(14):
    goto native_l10_2;
  case INT64_C(15):
    goto native_l10_2;
  case INT64_C(16):
    goto native_l10_2;
  case INT64_C(17):
    goto native_l10_2;
  case INT64_C(18):
    goto native_l10_2;
  case INT64_C(19):
    goto native_l10_2;
  case INT64_C(20):
    goto native_l10_2;
  case INT64_C(21):
    goto native_l10_2;
  case INT64_C(22):
    goto native_l10_2;
  case INT64_C(23):
    goto native_l10_1;
  case INT64_C(24):
    goto native_l10_2;
  case INT64_C(25):
    goto native_l10_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l10_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l10_3;
native_l10_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l10_3;
native_l10_3: ;
  return native_s_2;
}
native_m0_type_3 native_m0_fn_11(native_m0_type_47 native_v_0) {
  native_m0_type_3 native_s_0;
  native_m0_type_3 native_s_1;
  native_m0_type_3 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l11_2;
  case INT64_C(1):
    goto native_l11_2;
  case INT64_C(2):
    goto native_l11_2;
  case INT64_C(3):
    goto native_l11_2;
  case INT64_C(4):
    goto native_l11_2;
  case INT64_C(5):
    goto native_l11_2;
  case INT64_C(6):
    goto native_l11_2;
  case INT64_C(7):
    goto native_l11_2;
  case INT64_C(8):
    goto native_l11_2;
  case INT64_C(9):
    goto native_l11_2;
  case INT64_C(10):
    goto native_l11_2;
  case INT64_C(11):
    goto native_l11_2;
  case INT64_C(12):
    goto native_l11_2;
  case INT64_C(13):
    goto native_l11_2;
  case INT64_C(14):
    goto native_l11_2;
  case INT64_C(15):
    goto native_l11_2;
  case INT64_C(16):
    goto native_l11_2;
  case INT64_C(17):
    goto native_l11_2;
  case INT64_C(18):
    goto native_l11_2;
  case INT64_C(19):
    goto native_l11_2;
  case INT64_C(20):
    goto native_l11_2;
  case INT64_C(21):
    goto native_l11_2;
  case INT64_C(22):
    goto native_l11_2;
  case INT64_C(23):
    goto native_l11_2;
  case INT64_C(24):
    goto native_l11_2;
  case INT64_C(25):
    goto native_l11_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l11_1: ;
  native_s_0 = true;
  native_s_2 = native_s_0;
  goto native_l11_3;
native_l11_2: ;
  native_s_1 = false;
  native_s_2 = native_s_1;
  goto native_l11_3;
native_l11_3: ;
  return native_s_2;
}
