/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

struct native_m0_keyword_0_blob { uint64_t length; uint8_t bytes[sizeof "kernel/tx-sequence"]; };
static const struct native_m0_keyword_0_blob native_m0_keyword_0 = { (uint64_t)(sizeof "kernel/tx-sequence" - 1U), "kernel/tx-sequence" };
_Static_assert(offsetof(struct native_m0_keyword_0_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_1_blob { uint64_t length; uint8_t bytes[sizeof "kernel/op-ordinal"]; };
static const struct native_m0_keyword_1_blob native_m0_keyword_1 = { (uint64_t)(sizeof "kernel/op-ordinal" - 1U), "kernel/op-ordinal" };
_Static_assert(offsetof(struct native_m0_keyword_1_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_2_blob { uint64_t length; uint8_t bytes[sizeof "kernel/asserts"]; };
static const struct native_m0_keyword_2_blob native_m0_keyword_2 = { (uint64_t)(sizeof "kernel/asserts" - 1U), "kernel/asserts" };
_Static_assert(offsetof(struct native_m0_keyword_2_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_3_blob { uint64_t length; uint8_t bytes[sizeof "kernel/retracts"]; };
static const struct native_m0_keyword_3_blob native_m0_keyword_3 = { (uint64_t)(sizeof "kernel/retracts" - 1U), "kernel/retracts" };
_Static_assert(offsetof(struct native_m0_keyword_3_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_4_blob { uint64_t length; uint8_t bytes[sizeof "kernel/withdraws"]; };
static const struct native_m0_keyword_4_blob native_m0_keyword_4 = { (uint64_t)(sizeof "kernel/withdraws" - 1U), "kernel/withdraws" };
_Static_assert(offsetof(struct native_m0_keyword_4_blob, bytes) == 8, "keyword blob is length-prefixed");
struct native_m0_keyword_5_blob { uint64_t length; uint8_t bytes[sizeof "kernel/recorded-at"]; };
static const struct native_m0_keyword_5_blob native_m0_keyword_5 = { (uint64_t)(sizeof "kernel/recorded-at" - 1U), "kernel/recorded-at" };
_Static_assert(offsetof(struct native_m0_keyword_5_blob, bytes) == 8, "keyword blob is length-prefixed");

native_m0_type_6 native_m0_fn_0(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l0_2;
  case INT64_C(1):
    goto native_l0_2;
  case INT64_C(2):
    goto native_l0_2;
  case INT64_C(3):
    goto native_l0_2;
  case INT64_C(4):
    goto native_l0_2;
  case INT64_C(5):
    goto native_l0_2;
  case INT64_C(6):
    goto native_l0_1;
  case INT64_C(7):
    goto native_l0_2;
  case INT64_C(8):
    goto native_l0_2;
  case INT64_C(9):
    goto native_l0_2;
  case INT64_C(10):
    goto native_l0_2;
  case INT64_C(11):
    goto native_l0_2;
  case INT64_C(12):
    goto native_l0_2;
  case INT64_C(13):
    goto native_l0_2;
  case INT64_C(14):
    goto native_l0_2;
  case INT64_C(15):
    goto native_l0_2;
  case INT64_C(16):
    goto native_l0_2;
  case INT64_C(17):
    goto native_l0_2;
  case INT64_C(18):
    goto native_l0_2;
  case INT64_C(19):
    goto native_l0_2;
  case INT64_C(20):
    goto native_l0_2;
  case INT64_C(21):
    goto native_l0_2;
  case INT64_C(22):
    goto native_l0_2;
  case INT64_C(23):
    goto native_l0_2;
  case INT64_C(24):
    goto native_l0_2;
  case INT64_C(25):
    goto native_l0_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l0_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l0_3;
native_l0_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l0_3;
native_l0_3: ;
  return native_s_2;
}
native_m0_type_2 native_m0_fn_1(native_m0_type_1 native_v_0, native_m0_type_1 native_v_1) {
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_1 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_2 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_2 native_s_8;
  native_s_0 = INT64_C(0);
  (void)native_s_0;
  native_s_1 = (native_s_0 <= native_v_1);
  if (native_s_1) {
    goto native_l1_2;
  } else {
    goto native_l1_1;
  }
native_l1_1: ;
  native_s_2 = false;
  (void)native_s_2;
  native_s_5 = native_s_2;
  goto native_l1_3;
native_l1_2: ;
  native_s_3 = INT64_C(1000000000);
  (void)native_s_3;
  native_s_4 = (native_v_1 < native_s_3);
  native_s_5 = native_s_4;
  goto native_l1_3;
native_l1_3: ;
  if (native_s_5) {
    goto native_l1_4;
  } else {
    goto native_l1_5;
  }
native_l1_4: ;
  native_s_6 = (native_m0_type_2){ .field_0 = native_v_0, .field_1 = native_v_1 };
  native_s_8 = native_s_6;
  goto native_l1_6;
native_l1_5: ;
  native_s_7 = INT64_C(1);
  (void)native_s_7;
  native_trap((uint32_t)native_s_7);
native_l1_6: ;
  return native_s_8;
}
native_m0_type_2 native_m0_fn_2(native_m0_type_2 native_v_0, native_m0_type_1 native_v_1) {
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_1 native_s_0;
  native_m0_type_14 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_14 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_2 native_s_6;
  native_s_0 = native_v_0.field_0;
  if (__builtin_add_overflow(native_s_0, native_v_1, &native_s_1.payload.variant_0)) {
    native_s_1.tag = INT64_C(1);
  } else {
    native_s_1.tag = INT64_C(0);
  }
  switch (native_s_1.tag) {
  case INT64_C(0):
    native_s_3 = native_s_1;
  goto native_l2_2;
  case INT64_C(1):
    goto native_l2_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l2_1: ;
  native_s_2 = INT64_C(2);
  (void)native_s_2;
  native_trap((uint32_t)native_s_2);
native_l2_2: ;
  native_s_4 = native_s_3.payload.variant_0;
  native_s_5 = native_v_0.field_1;
  native_s_6 = (native_m0_type_2){ .field_0 = native_s_4, .field_1 = native_s_5 };
  return native_s_6;
}
native_m0_type_1 native_m0_fn_3(native_m0_type_2 native_v_0, native_m0_type_2 native_v_1) {
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_14 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_14 native_s_4;
  native_m0_type_1 native_s_5;
  native_s_0 = native_v_1.field_0;
  native_s_1 = native_v_0.field_0;
  if (__builtin_sub_overflow(native_s_0, native_s_1, &native_s_2.payload.variant_0)) {
    native_s_2.tag = INT64_C(1);
  } else {
    native_s_2.tag = INT64_C(0);
  }
  switch (native_s_2.tag) {
  case INT64_C(0):
    native_s_4 = native_s_2;
  goto native_l3_2;
  case INT64_C(1):
    goto native_l3_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l3_1: ;
  native_s_3 = INT64_C(2);
  (void)native_s_3;
  native_trap((uint32_t)native_s_3);
native_l3_2: ;
  native_s_5 = native_s_4.payload.variant_0;
  return native_s_5;
}
native_m0_type_6 native_m0_fn_4(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l4_2;
  case INT64_C(1):
    goto native_l4_2;
  case INT64_C(2):
    goto native_l4_2;
  case INT64_C(3):
    goto native_l4_2;
  case INT64_C(4):
    goto native_l4_2;
  case INT64_C(5):
    goto native_l4_2;
  case INT64_C(6):
    goto native_l4_2;
  case INT64_C(7):
    goto native_l4_1;
  case INT64_C(8):
    goto native_l4_2;
  case INT64_C(9):
    goto native_l4_2;
  case INT64_C(10):
    goto native_l4_2;
  case INT64_C(11):
    goto native_l4_2;
  case INT64_C(12):
    goto native_l4_2;
  case INT64_C(13):
    goto native_l4_2;
  case INT64_C(14):
    goto native_l4_2;
  case INT64_C(15):
    goto native_l4_2;
  case INT64_C(16):
    goto native_l4_2;
  case INT64_C(17):
    goto native_l4_2;
  case INT64_C(18):
    goto native_l4_2;
  case INT64_C(19):
    goto native_l4_2;
  case INT64_C(20):
    goto native_l4_2;
  case INT64_C(21):
    goto native_l4_2;
  case INT64_C(22):
    goto native_l4_2;
  case INT64_C(23):
    goto native_l4_2;
  case INT64_C(24):
    goto native_l4_2;
  case INT64_C(25):
    goto native_l4_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l4_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l4_3;
native_l4_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l4_3;
native_l4_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_5(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l5_2;
  case INT64_C(1):
    goto native_l5_2;
  case INT64_C(2):
    goto native_l5_2;
  case INT64_C(3):
    goto native_l5_2;
  case INT64_C(4):
    goto native_l5_2;
  case INT64_C(5):
    goto native_l5_2;
  case INT64_C(6):
    goto native_l5_2;
  case INT64_C(7):
    goto native_l5_2;
  case INT64_C(8):
    goto native_l5_1;
  case INT64_C(9):
    goto native_l5_2;
  case INT64_C(10):
    goto native_l5_2;
  case INT64_C(11):
    goto native_l5_2;
  case INT64_C(12):
    goto native_l5_2;
  case INT64_C(13):
    goto native_l5_2;
  case INT64_C(14):
    goto native_l5_2;
  case INT64_C(15):
    goto native_l5_2;
  case INT64_C(16):
    goto native_l5_2;
  case INT64_C(17):
    goto native_l5_2;
  case INT64_C(18):
    goto native_l5_2;
  case INT64_C(19):
    goto native_l5_2;
  case INT64_C(20):
    goto native_l5_2;
  case INT64_C(21):
    goto native_l5_2;
  case INT64_C(22):
    goto native_l5_2;
  case INT64_C(23):
    goto native_l5_2;
  case INT64_C(24):
    goto native_l5_2;
  case INT64_C(25):
    goto native_l5_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l5_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l5_3;
native_l5_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l5_3;
native_l5_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_6(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l6_2;
  case INT64_C(1):
    goto native_l6_2;
  case INT64_C(2):
    goto native_l6_2;
  case INT64_C(3):
    goto native_l6_2;
  case INT64_C(4):
    goto native_l6_2;
  case INT64_C(5):
    goto native_l6_2;
  case INT64_C(6):
    goto native_l6_2;
  case INT64_C(7):
    goto native_l6_2;
  case INT64_C(8):
    goto native_l6_2;
  case INT64_C(9):
    goto native_l6_1;
  case INT64_C(10):
    goto native_l6_2;
  case INT64_C(11):
    goto native_l6_2;
  case INT64_C(12):
    goto native_l6_2;
  case INT64_C(13):
    goto native_l6_2;
  case INT64_C(14):
    goto native_l6_2;
  case INT64_C(15):
    goto native_l6_2;
  case INT64_C(16):
    goto native_l6_2;
  case INT64_C(17):
    goto native_l6_2;
  case INT64_C(18):
    goto native_l6_2;
  case INT64_C(19):
    goto native_l6_2;
  case INT64_C(20):
    goto native_l6_2;
  case INT64_C(21):
    goto native_l6_2;
  case INT64_C(22):
    goto native_l6_2;
  case INT64_C(23):
    goto native_l6_2;
  case INT64_C(24):
    goto native_l6_2;
  case INT64_C(25):
    goto native_l6_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l6_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l6_3;
native_l6_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l6_3;
native_l6_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_7(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l7_2;
  case INT64_C(1):
    goto native_l7_2;
  case INT64_C(2):
    goto native_l7_2;
  case INT64_C(3):
    goto native_l7_2;
  case INT64_C(4):
    goto native_l7_2;
  case INT64_C(5):
    goto native_l7_2;
  case INT64_C(6):
    goto native_l7_2;
  case INT64_C(7):
    goto native_l7_2;
  case INT64_C(8):
    goto native_l7_2;
  case INT64_C(9):
    goto native_l7_2;
  case INT64_C(10):
    goto native_l7_1;
  case INT64_C(11):
    goto native_l7_2;
  case INT64_C(12):
    goto native_l7_2;
  case INT64_C(13):
    goto native_l7_2;
  case INT64_C(14):
    goto native_l7_2;
  case INT64_C(15):
    goto native_l7_2;
  case INT64_C(16):
    goto native_l7_2;
  case INT64_C(17):
    goto native_l7_2;
  case INT64_C(18):
    goto native_l7_2;
  case INT64_C(19):
    goto native_l7_2;
  case INT64_C(20):
    goto native_l7_2;
  case INT64_C(21):
    goto native_l7_2;
  case INT64_C(22):
    goto native_l7_2;
  case INT64_C(23):
    goto native_l7_2;
  case INT64_C(24):
    goto native_l7_2;
  case INT64_C(25):
    goto native_l7_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l7_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l7_3;
native_l7_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l7_3;
native_l7_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_8(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l8_2;
  case INT64_C(1):
    goto native_l8_2;
  case INT64_C(2):
    goto native_l8_2;
  case INT64_C(3):
    goto native_l8_2;
  case INT64_C(4):
    goto native_l8_2;
  case INT64_C(5):
    goto native_l8_2;
  case INT64_C(6):
    goto native_l8_2;
  case INT64_C(7):
    goto native_l8_2;
  case INT64_C(8):
    goto native_l8_2;
  case INT64_C(9):
    goto native_l8_2;
  case INT64_C(10):
    goto native_l8_2;
  case INT64_C(11):
    goto native_l8_1;
  case INT64_C(12):
    goto native_l8_2;
  case INT64_C(13):
    goto native_l8_2;
  case INT64_C(14):
    goto native_l8_2;
  case INT64_C(15):
    goto native_l8_2;
  case INT64_C(16):
    goto native_l8_2;
  case INT64_C(17):
    goto native_l8_2;
  case INT64_C(18):
    goto native_l8_2;
  case INT64_C(19):
    goto native_l8_2;
  case INT64_C(20):
    goto native_l8_2;
  case INT64_C(21):
    goto native_l8_2;
  case INT64_C(22):
    goto native_l8_2;
  case INT64_C(23):
    goto native_l8_2;
  case INT64_C(24):
    goto native_l8_2;
  case INT64_C(25):
    goto native_l8_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l8_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l8_3;
native_l8_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l8_3;
native_l8_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_9(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l9_2;
  case INT64_C(1):
    goto native_l9_2;
  case INT64_C(2):
    goto native_l9_2;
  case INT64_C(3):
    goto native_l9_2;
  case INT64_C(4):
    goto native_l9_2;
  case INT64_C(5):
    goto native_l9_2;
  case INT64_C(6):
    goto native_l9_2;
  case INT64_C(7):
    goto native_l9_2;
  case INT64_C(8):
    goto native_l9_2;
  case INT64_C(9):
    goto native_l9_2;
  case INT64_C(10):
    goto native_l9_2;
  case INT64_C(11):
    goto native_l9_2;
  case INT64_C(12):
    goto native_l9_1;
  case INT64_C(13):
    goto native_l9_2;
  case INT64_C(14):
    goto native_l9_2;
  case INT64_C(15):
    goto native_l9_2;
  case INT64_C(16):
    goto native_l9_2;
  case INT64_C(17):
    goto native_l9_2;
  case INT64_C(18):
    goto native_l9_2;
  case INT64_C(19):
    goto native_l9_2;
  case INT64_C(20):
    goto native_l9_2;
  case INT64_C(21):
    goto native_l9_2;
  case INT64_C(22):
    goto native_l9_2;
  case INT64_C(23):
    goto native_l9_2;
  case INT64_C(24):
    goto native_l9_2;
  case INT64_C(25):
    goto native_l9_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l9_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l9_3;
native_l9_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l9_3;
native_l9_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_10(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l10_2;
  case INT64_C(1):
    goto native_l10_2;
  case INT64_C(2):
    goto native_l10_2;
  case INT64_C(3):
    goto native_l10_2;
  case INT64_C(4):
    goto native_l10_2;
  case INT64_C(5):
    goto native_l10_2;
  case INT64_C(6):
    goto native_l10_2;
  case INT64_C(7):
    goto native_l10_2;
  case INT64_C(8):
    goto native_l10_2;
  case INT64_C(9):
    goto native_l10_2;
  case INT64_C(10):
    goto native_l10_2;
  case INT64_C(11):
    goto native_l10_2;
  case INT64_C(12):
    goto native_l10_2;
  case INT64_C(13):
    goto native_l10_1;
  case INT64_C(14):
    goto native_l10_2;
  case INT64_C(15):
    goto native_l10_2;
  case INT64_C(16):
    goto native_l10_2;
  case INT64_C(17):
    goto native_l10_2;
  case INT64_C(18):
    goto native_l10_2;
  case INT64_C(19):
    goto native_l10_2;
  case INT64_C(20):
    goto native_l10_2;
  case INT64_C(21):
    goto native_l10_2;
  case INT64_C(22):
    goto native_l10_2;
  case INT64_C(23):
    goto native_l10_2;
  case INT64_C(24):
    goto native_l10_2;
  case INT64_C(25):
    goto native_l10_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l10_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l10_3;
native_l10_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l10_3;
native_l10_3: ;
  return native_s_2;
}
native_m0_type_50 native_m0_fn_11(native_m0_type_72 native_v_0) {
  (void)native_v_0;
  native_m0_type_69 native_s_0;
  native_m0_type_64 native_s_1;
  native_m0_type_8 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_50 native_s_5;
  native_m0_type_7 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_50 native_s_9;
  native_m0_type_9 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_32 native_s_12;
  native_m0_type_50 native_s_13;
  native_m0_type_30 native_s_14;
  native_m0_type_50 native_s_15;
  native_m0_type_50 native_s_16;
  native_m0_type_13 native_s_17;
  native_m0_type_50 native_s_18;
  native_m0_type_50 native_s_19;
  native_s_0 = native_v_0.field_1;
  switch (native_s_0.tag) {
  case INT64_C(0):
    goto native_l11_1;
  case INT64_C(1):
    goto native_l11_10;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l11_1: ;
  if (native_s_0.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_1 = native_s_0.payload.variant_0;
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l11_2;
  case INT64_C(1):
    goto native_l11_3;
  case INT64_C(2):
    goto native_l11_4;
  case INT64_C(3):
    goto native_l11_5;
  case INT64_C(4):
    goto native_l11_6;
  case INT64_C(5):
    goto native_l11_7;
  case INT64_C(6):
    goto native_l11_8;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l11_2: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(3), .payload = { .variant_3 = native_s_2 } };
  native_s_16 = native_s_3;
  goto native_l11_9;
native_l11_3: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_4 = native_s_1.payload.variant_1;
  native_s_5 = (native_m0_type_50){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_4 } };
  native_s_16 = native_s_5;
  goto native_l11_9;
native_l11_4: ;
  if (native_s_1.tag != INT64_C(2)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = native_s_1.payload.variant_2;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(2), .payload = { .variant_2 = native_s_6 } };
  native_s_16 = native_s_7;
  goto native_l11_9;
native_l11_5: ;
  if (native_s_1.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_8 = native_s_1.payload.variant_3;
  native_s_9 = (native_m0_type_50){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_8 } };
  native_s_16 = native_s_9;
  goto native_l11_9;
native_l11_6: ;
  if (native_s_1.tag != INT64_C(4)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_10 = native_s_1.payload.variant_4;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_10 } };
  native_s_16 = native_s_11;
  goto native_l11_9;
native_l11_7: ;
  if (native_s_1.tag != INT64_C(5)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_12 = native_s_1.payload.variant_5;
  native_s_13 = (native_m0_type_50){ .tag = INT64_C(6), .payload = { .variant_6 = native_s_12 } };
  native_s_16 = native_s_13;
  goto native_l11_9;
native_l11_8: ;
  if (native_s_1.tag != INT64_C(6)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_14 = native_s_1.payload.variant_6;
  native_s_15 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_14 } };
  native_s_16 = native_s_15;
  goto native_l11_9;
native_l11_9: ;
  native_s_19 = native_s_16;
  goto native_l11_11;
native_l11_10: ;
  if (native_s_0.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_17 = native_s_0.payload.variant_1;
  (void)native_s_17;
  native_s_18 = (native_m0_type_50){ .tag = INT64_C(5) };
  native_s_19 = native_s_18;
  goto native_l11_11;
native_l11_11: ;
  return native_s_19;
}
native_m0_type_50 native_m0_fn_12(native_m0_type_73 native_v_0) {
  (void)native_v_0;
  native_m0_type_69 native_s_0;
  native_m0_type_64 native_s_1;
  native_m0_type_8 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_50 native_s_5;
  native_m0_type_7 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_50 native_s_9;
  native_m0_type_9 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_32 native_s_12;
  native_m0_type_50 native_s_13;
  native_m0_type_30 native_s_14;
  native_m0_type_50 native_s_15;
  native_m0_type_50 native_s_16;
  native_m0_type_13 native_s_17;
  native_m0_type_50 native_s_18;
  native_m0_type_50 native_s_19;
  native_s_0 = native_v_0.field_1;
  switch (native_s_0.tag) {
  case INT64_C(0):
    goto native_l12_1;
  case INT64_C(1):
    goto native_l12_10;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l12_1: ;
  if (native_s_0.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_1 = native_s_0.payload.variant_0;
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l12_2;
  case INT64_C(1):
    goto native_l12_3;
  case INT64_C(2):
    goto native_l12_4;
  case INT64_C(3):
    goto native_l12_5;
  case INT64_C(4):
    goto native_l12_6;
  case INT64_C(5):
    goto native_l12_7;
  case INT64_C(6):
    goto native_l12_8;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l12_2: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(3), .payload = { .variant_3 = native_s_2 } };
  native_s_16 = native_s_3;
  goto native_l12_9;
native_l12_3: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_4 = native_s_1.payload.variant_1;
  native_s_5 = (native_m0_type_50){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_4 } };
  native_s_16 = native_s_5;
  goto native_l12_9;
native_l12_4: ;
  if (native_s_1.tag != INT64_C(2)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = native_s_1.payload.variant_2;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(2), .payload = { .variant_2 = native_s_6 } };
  native_s_16 = native_s_7;
  goto native_l12_9;
native_l12_5: ;
  if (native_s_1.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_8 = native_s_1.payload.variant_3;
  native_s_9 = (native_m0_type_50){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_8 } };
  native_s_16 = native_s_9;
  goto native_l12_9;
native_l12_6: ;
  if (native_s_1.tag != INT64_C(4)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_10 = native_s_1.payload.variant_4;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_10 } };
  native_s_16 = native_s_11;
  goto native_l12_9;
native_l12_7: ;
  if (native_s_1.tag != INT64_C(5)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_12 = native_s_1.payload.variant_5;
  native_s_13 = (native_m0_type_50){ .tag = INT64_C(6), .payload = { .variant_6 = native_s_12 } };
  native_s_16 = native_s_13;
  goto native_l12_9;
native_l12_8: ;
  if (native_s_1.tag != INT64_C(6)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_14 = native_s_1.payload.variant_6;
  native_s_15 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_14 } };
  native_s_16 = native_s_15;
  goto native_l12_9;
native_l12_9: ;
  native_s_19 = native_s_16;
  goto native_l12_11;
native_l12_10: ;
  if (native_s_0.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_17 = native_s_0.payload.variant_1;
  (void)native_s_17;
  native_s_18 = (native_m0_type_50){ .tag = INT64_C(5) };
  native_s_19 = native_s_18;
  goto native_l12_11;
native_l12_11: ;
  return native_s_19;
}
native_m0_type_50 native_m0_fn_13(native_m0_type_70 native_v_0) {
  (void)native_v_0;
  native_m0_type_69 native_s_0;
  native_m0_type_64 native_s_1;
  native_m0_type_8 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_50 native_s_5;
  native_m0_type_7 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_50 native_s_9;
  native_m0_type_9 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_32 native_s_12;
  native_m0_type_50 native_s_13;
  native_m0_type_30 native_s_14;
  native_m0_type_50 native_s_15;
  native_m0_type_50 native_s_16;
  native_m0_type_13 native_s_17;
  native_m0_type_50 native_s_18;
  native_m0_type_50 native_s_19;
  native_s_0 = native_v_0.field_3;
  switch (native_s_0.tag) {
  case INT64_C(0):
    goto native_l13_1;
  case INT64_C(1):
    goto native_l13_10;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l13_1: ;
  if (native_s_0.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_1 = native_s_0.payload.variant_0;
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l13_2;
  case INT64_C(1):
    goto native_l13_3;
  case INT64_C(2):
    goto native_l13_4;
  case INT64_C(3):
    goto native_l13_5;
  case INT64_C(4):
    goto native_l13_6;
  case INT64_C(5):
    goto native_l13_7;
  case INT64_C(6):
    goto native_l13_8;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l13_2: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(3), .payload = { .variant_3 = native_s_2 } };
  native_s_16 = native_s_3;
  goto native_l13_9;
native_l13_3: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_4 = native_s_1.payload.variant_1;
  native_s_5 = (native_m0_type_50){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_4 } };
  native_s_16 = native_s_5;
  goto native_l13_9;
native_l13_4: ;
  if (native_s_1.tag != INT64_C(2)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = native_s_1.payload.variant_2;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(2), .payload = { .variant_2 = native_s_6 } };
  native_s_16 = native_s_7;
  goto native_l13_9;
native_l13_5: ;
  if (native_s_1.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_8 = native_s_1.payload.variant_3;
  native_s_9 = (native_m0_type_50){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_8 } };
  native_s_16 = native_s_9;
  goto native_l13_9;
native_l13_6: ;
  if (native_s_1.tag != INT64_C(4)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_10 = native_s_1.payload.variant_4;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_10 } };
  native_s_16 = native_s_11;
  goto native_l13_9;
native_l13_7: ;
  if (native_s_1.tag != INT64_C(5)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_12 = native_s_1.payload.variant_5;
  native_s_13 = (native_m0_type_50){ .tag = INT64_C(6), .payload = { .variant_6 = native_s_12 } };
  native_s_16 = native_s_13;
  goto native_l13_9;
native_l13_8: ;
  if (native_s_1.tag != INT64_C(6)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_14 = native_s_1.payload.variant_6;
  native_s_15 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_14 } };
  native_s_16 = native_s_15;
  goto native_l13_9;
native_l13_9: ;
  native_s_19 = native_s_16;
  goto native_l13_11;
native_l13_10: ;
  if (native_s_0.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_17 = native_s_0.payload.variant_1;
  (void)native_s_17;
  native_s_18 = (native_m0_type_50){ .tag = INT64_C(5) };
  native_s_19 = native_s_18;
  goto native_l13_11;
native_l13_11: ;
  return native_s_19;
}
native_m0_type_50 native_m0_fn_14(native_m0_type_65 native_v_0) {
  (void)native_v_0;
  native_m0_type_64 native_s_0;
  native_m0_type_8 native_s_1;
  native_m0_type_50 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_50 native_s_4;
  native_m0_type_7 native_s_5;
  native_m0_type_50 native_s_6;
  native_m0_type_6 native_s_7;
  native_m0_type_50 native_s_8;
  native_m0_type_9 native_s_9;
  native_m0_type_50 native_s_10;
  native_m0_type_32 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_30 native_s_13;
  native_m0_type_50 native_s_14;
  native_m0_type_50 native_s_15;
  native_s_0 = native_v_0.field_5;
  switch (native_s_0.tag) {
  case INT64_C(0):
    goto native_l14_1;
  case INT64_C(1):
    goto native_l14_2;
  case INT64_C(2):
    goto native_l14_3;
  case INT64_C(3):
    goto native_l14_4;
  case INT64_C(4):
    goto native_l14_5;
  case INT64_C(5):
    goto native_l14_6;
  case INT64_C(6):
    goto native_l14_7;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l14_1: ;
  if (native_s_0.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_1 = native_s_0.payload.variant_0;
  native_s_2 = (native_m0_type_50){ .tag = INT64_C(3), .payload = { .variant_3 = native_s_1 } };
  native_s_15 = native_s_2;
  goto native_l14_8;
native_l14_2: ;
  if (native_s_0.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_3 = native_s_0.payload.variant_1;
  native_s_4 = (native_m0_type_50){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_3 } };
  native_s_15 = native_s_4;
  goto native_l14_8;
native_l14_3: ;
  if (native_s_0.tag != INT64_C(2)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_5 = native_s_0.payload.variant_2;
  native_s_6 = (native_m0_type_50){ .tag = INT64_C(2), .payload = { .variant_2 = native_s_5 } };
  native_s_15 = native_s_6;
  goto native_l14_8;
native_l14_4: ;
  if (native_s_0.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_7 = native_s_0.payload.variant_3;
  native_s_8 = (native_m0_type_50){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_7 } };
  native_s_15 = native_s_8;
  goto native_l14_8;
native_l14_5: ;
  if (native_s_0.tag != INT64_C(4)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_9 = native_s_0.payload.variant_4;
  native_s_10 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_9 } };
  native_s_15 = native_s_10;
  goto native_l14_8;
native_l14_6: ;
  if (native_s_0.tag != INT64_C(5)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_11 = native_s_0.payload.variant_5;
  native_s_12 = (native_m0_type_50){ .tag = INT64_C(6), .payload = { .variant_6 = native_s_11 } };
  native_s_15 = native_s_12;
  goto native_l14_8;
native_l14_7: ;
  if (native_s_0.tag != INT64_C(6)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_13 = native_s_0.payload.variant_6;
  native_s_14 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_13 } };
  native_s_15 = native_s_14;
  goto native_l14_8;
native_l14_8: ;
  return native_s_15;
}
native_m0_type_50 native_m0_fn_15(native_m0_type_71 native_v_0) {
  (void)native_v_0;
  native_m0_type_69 native_s_0;
  native_m0_type_64 native_s_1;
  native_m0_type_8 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_50 native_s_5;
  native_m0_type_7 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_50 native_s_9;
  native_m0_type_9 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_32 native_s_12;
  native_m0_type_50 native_s_13;
  native_m0_type_30 native_s_14;
  native_m0_type_50 native_s_15;
  native_m0_type_50 native_s_16;
  native_m0_type_13 native_s_17;
  native_m0_type_50 native_s_18;
  native_m0_type_50 native_s_19;
  native_s_0 = native_v_0.field_5;
  switch (native_s_0.tag) {
  case INT64_C(0):
    goto native_l15_1;
  case INT64_C(1):
    goto native_l15_10;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l15_1: ;
  if (native_s_0.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_1 = native_s_0.payload.variant_0;
  switch (native_s_1.tag) {
  case INT64_C(0):
    goto native_l15_2;
  case INT64_C(1):
    goto native_l15_3;
  case INT64_C(2):
    goto native_l15_4;
  case INT64_C(3):
    goto native_l15_5;
  case INT64_C(4):
    goto native_l15_6;
  case INT64_C(5):
    goto native_l15_7;
  case INT64_C(6):
    goto native_l15_8;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l15_2: ;
  if (native_s_1.tag != INT64_C(0)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_s_1.payload.variant_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(3), .payload = { .variant_3 = native_s_2 } };
  native_s_16 = native_s_3;
  goto native_l15_9;
native_l15_3: ;
  if (native_s_1.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_4 = native_s_1.payload.variant_1;
  native_s_5 = (native_m0_type_50){ .tag = INT64_C(1), .payload = { .variant_1 = native_s_4 } };
  native_s_16 = native_s_5;
  goto native_l15_9;
native_l15_4: ;
  if (native_s_1.tag != INT64_C(2)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_6 = native_s_1.payload.variant_2;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(2), .payload = { .variant_2 = native_s_6 } };
  native_s_16 = native_s_7;
  goto native_l15_9;
native_l15_5: ;
  if (native_s_1.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_8 = native_s_1.payload.variant_3;
  native_s_9 = (native_m0_type_50){ .tag = INT64_C(0), .payload = { .variant_0 = native_s_8 } };
  native_s_16 = native_s_9;
  goto native_l15_9;
native_l15_6: ;
  if (native_s_1.tag != INT64_C(4)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_10 = native_s_1.payload.variant_4;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_10 } };
  native_s_16 = native_s_11;
  goto native_l15_9;
native_l15_7: ;
  if (native_s_1.tag != INT64_C(5)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_12 = native_s_1.payload.variant_5;
  native_s_13 = (native_m0_type_50){ .tag = INT64_C(6), .payload = { .variant_6 = native_s_12 } };
  native_s_16 = native_s_13;
  goto native_l15_9;
native_l15_8: ;
  if (native_s_1.tag != INT64_C(6)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_14 = native_s_1.payload.variant_6;
  native_s_15 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_14 } };
  native_s_16 = native_s_15;
  goto native_l15_9;
native_l15_9: ;
  native_s_19 = native_s_16;
  goto native_l15_11;
native_l15_10: ;
  if (native_s_0.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_17 = native_s_0.payload.variant_1;
  (void)native_s_17;
  native_s_18 = (native_m0_type_50){ .tag = INT64_C(5) };
  native_s_19 = native_s_18;
  goto native_l15_11;
native_l15_11: ;
  return native_s_19;
}
native_m0_type_6 native_m0_fn_16(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l16_2;
  case INT64_C(1):
    goto native_l16_2;
  case INT64_C(2):
    goto native_l16_2;
  case INT64_C(3):
    goto native_l16_2;
  case INT64_C(4):
    goto native_l16_2;
  case INT64_C(5):
    goto native_l16_2;
  case INT64_C(6):
    goto native_l16_2;
  case INT64_C(7):
    goto native_l16_2;
  case INT64_C(8):
    goto native_l16_2;
  case INT64_C(9):
    goto native_l16_2;
  case INT64_C(10):
    goto native_l16_2;
  case INT64_C(11):
    goto native_l16_2;
  case INT64_C(12):
    goto native_l16_2;
  case INT64_C(13):
    goto native_l16_2;
  case INT64_C(14):
    goto native_l16_2;
  case INT64_C(15):
    goto native_l16_2;
  case INT64_C(16):
    goto native_l16_2;
  case INT64_C(17):
    goto native_l16_2;
  case INT64_C(18):
    goto native_l16_2;
  case INT64_C(19):
    goto native_l16_2;
  case INT64_C(20):
    goto native_l16_2;
  case INT64_C(21):
    goto native_l16_2;
  case INT64_C(22):
    goto native_l16_1;
  case INT64_C(23):
    goto native_l16_2;
  case INT64_C(24):
    goto native_l16_2;
  case INT64_C(25):
    goto native_l16_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l16_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l16_3;
native_l16_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l16_3;
native_l16_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_17(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l17_2;
  case INT64_C(1):
    goto native_l17_2;
  case INT64_C(2):
    goto native_l17_2;
  case INT64_C(3):
    goto native_l17_2;
  case INT64_C(4):
    goto native_l17_2;
  case INT64_C(5):
    goto native_l17_2;
  case INT64_C(6):
    goto native_l17_2;
  case INT64_C(7):
    goto native_l17_2;
  case INT64_C(8):
    goto native_l17_2;
  case INT64_C(9):
    goto native_l17_2;
  case INT64_C(10):
    goto native_l17_2;
  case INT64_C(11):
    goto native_l17_2;
  case INT64_C(12):
    goto native_l17_2;
  case INT64_C(13):
    goto native_l17_2;
  case INT64_C(14):
    goto native_l17_2;
  case INT64_C(15):
    goto native_l17_2;
  case INT64_C(16):
    goto native_l17_2;
  case INT64_C(17):
    goto native_l17_2;
  case INT64_C(18):
    goto native_l17_2;
  case INT64_C(19):
    goto native_l17_2;
  case INT64_C(20):
    goto native_l17_2;
  case INT64_C(21):
    goto native_l17_2;
  case INT64_C(22):
    goto native_l17_2;
  case INT64_C(23):
    goto native_l17_1;
  case INT64_C(24):
    goto native_l17_2;
  case INT64_C(25):
    goto native_l17_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l17_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l17_3;
native_l17_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l17_3;
native_l17_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_18(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l18_2;
  case INT64_C(1):
    goto native_l18_2;
  case INT64_C(2):
    goto native_l18_2;
  case INT64_C(3):
    goto native_l18_2;
  case INT64_C(4):
    goto native_l18_2;
  case INT64_C(5):
    goto native_l18_2;
  case INT64_C(6):
    goto native_l18_2;
  case INT64_C(7):
    goto native_l18_2;
  case INT64_C(8):
    goto native_l18_2;
  case INT64_C(9):
    goto native_l18_2;
  case INT64_C(10):
    goto native_l18_2;
  case INT64_C(11):
    goto native_l18_2;
  case INT64_C(12):
    goto native_l18_2;
  case INT64_C(13):
    goto native_l18_2;
  case INT64_C(14):
    goto native_l18_2;
  case INT64_C(15):
    goto native_l18_2;
  case INT64_C(16):
    goto native_l18_2;
  case INT64_C(17):
    goto native_l18_2;
  case INT64_C(18):
    goto native_l18_2;
  case INT64_C(19):
    goto native_l18_2;
  case INT64_C(20):
    goto native_l18_2;
  case INT64_C(21):
    goto native_l18_2;
  case INT64_C(22):
    goto native_l18_2;
  case INT64_C(23):
    goto native_l18_2;
  case INT64_C(24):
    goto native_l18_2;
  case INT64_C(25):
    goto native_l18_1;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l18_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l18_3;
native_l18_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l18_3;
native_l18_3: ;
  return native_s_2;
}
native_m0_type_6 native_m0_fn_19(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_6 native_s_2;
  native_m0_type_6 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_6 native_s_6;
  native_m0_type_6 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_6 native_s_10;
  native_m0_type_6 native_s_11;
  native_m0_type_6 native_s_12;
  native_m0_type_6 native_s_13;
  native_m0_type_6 native_s_14;
  native_m0_type_6 native_s_15;
  native_m0_type_6 native_s_16;
  native_m0_type_6 native_s_17;
  native_m0_type_6 native_s_18;
  native_m0_type_6 native_s_19;
  native_m0_type_6 native_s_20;
  native_m0_type_6 native_s_21;
  native_m0_type_6 native_s_22;
  native_m0_type_6 native_s_23;
  native_m0_type_6 native_s_24;
  native_m0_type_6 native_s_25;
  native_m0_type_6 native_s_26;
  native_m0_type_6 native_s_27;
  native_m0_type_6 native_s_28;
  native_m0_type_6 native_s_29;
  native_m0_type_6 native_s_30;
  native_m0_type_6 native_s_31;
  native_m0_type_6 native_s_32;
  native_m0_type_6 native_s_33;
  native_m0_type_6 native_s_34;
  native_m0_type_6 native_s_35;
  native_m0_type_6 native_s_36;
  native_m0_type_6 native_s_37;
  native_m0_type_6 native_s_38;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l19_2;
  case INT64_C(1):
    goto native_l19_2;
  case INT64_C(2):
    goto native_l19_2;
  case INT64_C(3):
    goto native_l19_1;
  case INT64_C(4):
    goto native_l19_2;
  case INT64_C(5):
    goto native_l19_2;
  case INT64_C(6):
    goto native_l19_2;
  case INT64_C(7):
    goto native_l19_2;
  case INT64_C(8):
    goto native_l19_2;
  case INT64_C(9):
    goto native_l19_2;
  case INT64_C(10):
    goto native_l19_2;
  case INT64_C(11):
    goto native_l19_2;
  case INT64_C(12):
    goto native_l19_2;
  case INT64_C(13):
    goto native_l19_2;
  case INT64_C(14):
    goto native_l19_2;
  case INT64_C(15):
    goto native_l19_2;
  case INT64_C(16):
    goto native_l19_2;
  case INT64_C(17):
    goto native_l19_2;
  case INT64_C(18):
    goto native_l19_2;
  case INT64_C(19):
    goto native_l19_2;
  case INT64_C(20):
    goto native_l19_2;
  case INT64_C(21):
    goto native_l19_2;
  case INT64_C(22):
    goto native_l19_2;
  case INT64_C(23):
    goto native_l19_2;
  case INT64_C(24):
    goto native_l19_2;
  case INT64_C(25):
    goto native_l19_2;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l19_1: ;
  native_s_0 = true;
  (void)native_s_0;
  native_s_2 = native_s_0;
  goto native_l19_3;
native_l19_2: ;
  native_s_1 = false;
  (void)native_s_1;
  native_s_2 = native_s_1;
  goto native_l19_3;
native_l19_3: ;
  if (native_s_2) {
    goto native_l19_4;
  } else {
    goto native_l19_5;
  }
native_l19_4: ;
  native_s_36 = native_s_2;
  goto native_l19_46;
native_l19_5: ;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l19_7;
  case INT64_C(1):
    goto native_l19_6;
  case INT64_C(2):
    goto native_l19_7;
  case INT64_C(3):
    goto native_l19_7;
  case INT64_C(4):
    goto native_l19_7;
  case INT64_C(5):
    goto native_l19_7;
  case INT64_C(6):
    goto native_l19_7;
  case INT64_C(7):
    goto native_l19_7;
  case INT64_C(8):
    goto native_l19_7;
  case INT64_C(9):
    goto native_l19_7;
  case INT64_C(10):
    goto native_l19_7;
  case INT64_C(11):
    goto native_l19_7;
  case INT64_C(12):
    goto native_l19_7;
  case INT64_C(13):
    goto native_l19_7;
  case INT64_C(14):
    goto native_l19_7;
  case INT64_C(15):
    goto native_l19_7;
  case INT64_C(16):
    goto native_l19_7;
  case INT64_C(17):
    goto native_l19_7;
  case INT64_C(18):
    goto native_l19_7;
  case INT64_C(19):
    goto native_l19_7;
  case INT64_C(20):
    goto native_l19_7;
  case INT64_C(21):
    goto native_l19_7;
  case INT64_C(22):
    goto native_l19_7;
  case INT64_C(23):
    goto native_l19_7;
  case INT64_C(24):
    goto native_l19_7;
  case INT64_C(25):
    goto native_l19_7;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l19_6: ;
  native_s_3 = true;
  (void)native_s_3;
  native_s_5 = native_s_3;
  goto native_l19_8;
native_l19_7: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_5 = native_s_4;
  goto native_l19_8;
native_l19_8: ;
  if (native_s_5) {
    goto native_l19_9;
  } else {
    goto native_l19_10;
  }
native_l19_9: ;
  native_s_33 = native_s_5;
  goto native_l19_43;
native_l19_10: ;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l19_12;
  case INT64_C(1):
    goto native_l19_11;
  case INT64_C(2):
    goto native_l19_11;
  case INT64_C(3):
    goto native_l19_12;
  case INT64_C(4):
    goto native_l19_12;
  case INT64_C(5):
    goto native_l19_12;
  case INT64_C(6):
    goto native_l19_12;
  case INT64_C(7):
    goto native_l19_12;
  case INT64_C(8):
    goto native_l19_12;
  case INT64_C(9):
    goto native_l19_12;
  case INT64_C(10):
    goto native_l19_12;
  case INT64_C(11):
    goto native_l19_12;
  case INT64_C(12):
    goto native_l19_12;
  case INT64_C(13):
    goto native_l19_12;
  case INT64_C(14):
    goto native_l19_12;
  case INT64_C(15):
    goto native_l19_12;
  case INT64_C(16):
    goto native_l19_12;
  case INT64_C(17):
    goto native_l19_12;
  case INT64_C(18):
    goto native_l19_12;
  case INT64_C(19):
    goto native_l19_12;
  case INT64_C(20):
    goto native_l19_12;
  case INT64_C(21):
    goto native_l19_12;
  case INT64_C(22):
    goto native_l19_12;
  case INT64_C(23):
    goto native_l19_12;
  case INT64_C(24):
    goto native_l19_12;
  case INT64_C(25):
    goto native_l19_12;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l19_11: ;
  native_s_6 = true;
  (void)native_s_6;
  native_s_8 = native_s_6;
  goto native_l19_13;
native_l19_12: ;
  native_s_7 = false;
  (void)native_s_7;
  native_s_8 = native_s_7;
  goto native_l19_13;
native_l19_13: ;
  if (native_s_8) {
    goto native_l19_15;
  } else {
    goto native_l19_14;
  }
native_l19_14: ;
  native_s_14 = native_s_8;
  goto native_l19_19;
native_l19_15: ;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l19_17;
  case INT64_C(1):
    goto native_l19_16;
  case INT64_C(2):
    goto native_l19_17;
  case INT64_C(3):
    goto native_l19_17;
  case INT64_C(4):
    goto native_l19_17;
  case INT64_C(5):
    goto native_l19_17;
  case INT64_C(6):
    goto native_l19_17;
  case INT64_C(7):
    goto native_l19_17;
  case INT64_C(8):
    goto native_l19_17;
  case INT64_C(9):
    goto native_l19_17;
  case INT64_C(10):
    goto native_l19_17;
  case INT64_C(11):
    goto native_l19_17;
  case INT64_C(12):
    goto native_l19_17;
  case INT64_C(13):
    goto native_l19_17;
  case INT64_C(14):
    goto native_l19_17;
  case INT64_C(15):
    goto native_l19_17;
  case INT64_C(16):
    goto native_l19_17;
  case INT64_C(17):
    goto native_l19_17;
  case INT64_C(18):
    goto native_l19_17;
  case INT64_C(19):
    goto native_l19_17;
  case INT64_C(20):
    goto native_l19_17;
  case INT64_C(21):
    goto native_l19_17;
  case INT64_C(22):
    goto native_l19_17;
  case INT64_C(23):
    goto native_l19_17;
  case INT64_C(24):
    goto native_l19_17;
  case INT64_C(25):
    goto native_l19_17;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l19_16: ;
  native_s_9 = true;
  (void)native_s_9;
  native_s_11 = native_s_9;
  goto native_l19_18;
native_l19_17: ;
  native_s_10 = false;
  (void)native_s_10;
  native_s_11 = native_s_10;
  goto native_l19_18;
native_l19_18: ;
  native_s_12 = false;
  (void)native_s_12;
  native_s_13 = (native_s_11 == native_s_12);
  native_s_15 = native_s_13;
  goto native_l19_20;
native_l19_19: ;
  native_s_16 = native_s_14;
  goto native_l19_21;
native_l19_20: ;
  native_s_16 = native_s_15;
  goto native_l19_21;
native_l19_21: ;
  if (native_s_16) {
    goto native_l19_22;
  } else {
    goto native_l19_23;
  }
native_l19_22: ;
  native_s_30 = native_s_16;
  goto native_l19_40;
native_l19_23: ;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l19_24;
  case INT64_C(1):
    goto native_l19_25;
  case INT64_C(2):
    goto native_l19_25;
  case INT64_C(3):
    goto native_l19_25;
  case INT64_C(4):
    goto native_l19_25;
  case INT64_C(5):
    goto native_l19_25;
  case INT64_C(6):
    goto native_l19_25;
  case INT64_C(7):
    goto native_l19_25;
  case INT64_C(8):
    goto native_l19_25;
  case INT64_C(9):
    goto native_l19_25;
  case INT64_C(10):
    goto native_l19_25;
  case INT64_C(11):
    goto native_l19_25;
  case INT64_C(12):
    goto native_l19_25;
  case INT64_C(13):
    goto native_l19_25;
  case INT64_C(14):
    goto native_l19_25;
  case INT64_C(15):
    goto native_l19_25;
  case INT64_C(16):
    goto native_l19_25;
  case INT64_C(17):
    goto native_l19_25;
  case INT64_C(18):
    goto native_l19_25;
  case INT64_C(19):
    goto native_l19_25;
  case INT64_C(20):
    goto native_l19_25;
  case INT64_C(21):
    goto native_l19_25;
  case INT64_C(22):
    goto native_l19_25;
  case INT64_C(23):
    goto native_l19_25;
  case INT64_C(24):
    goto native_l19_25;
  case INT64_C(25):
    goto native_l19_25;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l19_24: ;
  native_s_17 = true;
  (void)native_s_17;
  native_s_19 = native_s_17;
  goto native_l19_26;
native_l19_25: ;
  native_s_18 = false;
  (void)native_s_18;
  native_s_19 = native_s_18;
  goto native_l19_26;
native_l19_26: ;
  if (native_s_19) {
    goto native_l19_27;
  } else {
    goto native_l19_28;
  }
native_l19_27: ;
  native_s_27 = native_s_19;
  goto native_l19_37;
native_l19_28: ;
  switch (native_v_0.tag) {
  case INT64_C(0):
    goto native_l19_30;
  case INT64_C(1):
    goto native_l19_30;
  case INT64_C(2):
    goto native_l19_30;
  case INT64_C(3):
    goto native_l19_30;
  case INT64_C(4):
    goto native_l19_29;
  case INT64_C(5):
    goto native_l19_30;
  case INT64_C(6):
    goto native_l19_30;
  case INT64_C(7):
    goto native_l19_30;
  case INT64_C(8):
    goto native_l19_30;
  case INT64_C(9):
    goto native_l19_30;
  case INT64_C(10):
    goto native_l19_30;
  case INT64_C(11):
    goto native_l19_30;
  case INT64_C(12):
    goto native_l19_30;
  case INT64_C(13):
    goto native_l19_30;
  case INT64_C(14):
    goto native_l19_30;
  case INT64_C(15):
    goto native_l19_30;
  case INT64_C(16):
    goto native_l19_30;
  case INT64_C(17):
    goto native_l19_30;
  case INT64_C(18):
    goto native_l19_30;
  case INT64_C(19):
    goto native_l19_30;
  case INT64_C(20):
    goto native_l19_30;
  case INT64_C(21):
    goto native_l19_30;
  case INT64_C(22):
    goto native_l19_30;
  case INT64_C(23):
    goto native_l19_30;
  case INT64_C(24):
    goto native_l19_30;
  case INT64_C(25):
    goto native_l19_30;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l19_29: ;
  native_s_20 = true;
  (void)native_s_20;
  native_s_22 = native_s_20;
  goto native_l19_31;
native_l19_30: ;
  native_s_21 = false;
  (void)native_s_21;
  native_s_22 = native_s_21;
  goto native_l19_31;
native_l19_31: ;
  if (native_s_22) {
    goto native_l19_32;
  } else {
    goto native_l19_33;
  }
native_l19_32: ;
  native_s_24 = native_s_22;
  goto native_l19_34;
native_l19_33: ;
  native_s_23 = native_m0_fn_0(native_v_0);
  native_s_25 = native_s_23;
  goto native_l19_35;
native_l19_34: ;
  native_s_26 = native_s_24;
  goto native_l19_36;
native_l19_35: ;
  native_s_26 = native_s_25;
  goto native_l19_36;
native_l19_36: ;
  native_s_28 = native_s_26;
  goto native_l19_38;
native_l19_37: ;
  native_s_29 = native_s_27;
  goto native_l19_39;
native_l19_38: ;
  native_s_29 = native_s_28;
  goto native_l19_39;
native_l19_39: ;
  native_s_31 = native_s_29;
  goto native_l19_41;
native_l19_40: ;
  native_s_32 = native_s_30;
  goto native_l19_42;
native_l19_41: ;
  native_s_32 = native_s_31;
  goto native_l19_42;
native_l19_42: ;
  native_s_34 = native_s_32;
  goto native_l19_44;
native_l19_43: ;
  native_s_35 = native_s_33;
  goto native_l19_45;
native_l19_44: ;
  native_s_35 = native_s_34;
  goto native_l19_45;
native_l19_45: ;
  native_s_37 = native_s_35;
  goto native_l19_47;
native_l19_46: ;
  native_s_38 = native_s_36;
  goto native_l19_48;
native_l19_47: ;
  native_s_38 = native_s_37;
  goto native_l19_48;
native_l19_48: ;
  return native_s_38;
}
native_m0_type_6 native_m0_fn_20(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_6 native_s_0;
  native_m0_type_30 native_s_1;
  native_m0_type_51 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_50 native_s_5;
  native_m0_type_6 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_6 native_s_10;
  native_m0_type_6 native_s_11;
  native_m0_type_6 native_s_12;
  native_m0_type_6 native_s_13;
  native_m0_type_6 native_s_14;
  native_m0_type_6 native_s_15;
  native_m0_type_6 native_s_16;
  native_s_0 = native_m0_fn_4(native_v_0);
  if (native_s_0) {
    goto native_l20_1;
  } else {
    goto native_l20_12;
  }
native_l20_1: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_1 = native_v_0.payload.variant_7;
  if (native_s_1 == NULL) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = *((const native_m0_type_51 *)native_s_1);
  native_s_3 = native_s_2.field_0;
  native_s_4 = native_m0_fn_20(native_s_3);
  if (native_s_4) {
    goto native_l20_3;
  } else {
    goto native_l20_2;
  }
native_l20_2: ;
  native_s_12 = native_s_4;
  goto native_l20_9;
native_l20_3: ;
  native_s_5 = native_s_2.field_1;
  native_s_6 = native_m0_fn_20(native_s_5);
  if (native_s_6) {
    goto native_l20_5;
  } else {
    goto native_l20_4;
  }
native_l20_4: ;
  native_s_9 = native_s_6;
  goto native_l20_6;
native_l20_5: ;
  native_s_7 = native_s_2.field_2;
  native_s_8 = native_m0_fn_20(native_s_7);
  native_s_10 = native_s_8;
  goto native_l20_7;
native_l20_6: ;
  native_s_11 = native_s_9;
  goto native_l20_8;
native_l20_7: ;
  native_s_11 = native_s_10;
  goto native_l20_8;
native_l20_8: ;
  native_s_13 = native_s_11;
  goto native_l20_10;
native_l20_9: ;
  native_s_14 = native_s_12;
  goto native_l20_11;
native_l20_10: ;
  native_s_14 = native_s_13;
  goto native_l20_11;
native_l20_11: ;
  native_s_16 = native_s_14;
  goto native_l20_13;
native_l20_12: ;
  native_s_15 = native_m0_fn_19(native_v_0);
  native_s_16 = native_s_15;
  goto native_l20_13;
native_l20_13: ;
  return native_s_16;
}
native_m0_type_51 native_m0_fn_21(native_arena *arena, const native_capability *capability, native_m0_type_50 native_v_0, native_m0_type_50 native_v_1, native_m0_type_50 native_v_2) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  (void)native_v_2;
  native_m0_type_0 native_s_0;
  native_m0_type_51 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_51 native_s_6;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (native_m0_type_51){ .field_0 = native_v_0, .field_1 = native_v_1, .field_2 = native_v_2 };
  native_s_2 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_2 = native_s_1;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_2 } };
  native_s_4 = native_m0_fn_20(native_s_3);
  if (native_s_4) {
    goto native_l21_1;
  } else {
    goto native_l21_2;
  }
native_l21_1: ;
  native_s_6 = native_s_1;
  goto native_l21_3;
native_l21_2: ;
  native_s_5 = INT64_C(1);
  (void)native_s_5;
  native_trap((uint32_t)native_s_5);
native_l21_3: ;
  return native_s_6;
}
native_m0_type_51 native_m0_fn_22(native_arena *arena, const native_capability *capability, native_m0_type_8 native_v_0, native_m0_type_1 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_0 native_s_0;
  native_m0_type_9 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_6 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_50 native_s_9;
  native_m0_type_50 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_51 native_s_12;
  native_m0_type_1 native_s_13;
  native_m0_type_51 native_s_14;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_1;
  native_s_2 = (int64_t)native_text_length(native_v_0);
  native_s_3 = INT64_C(0);
  (void)native_s_3;
  native_s_4 = (native_s_3 < native_s_2);
  if (native_s_4) {
    goto native_l22_2;
  } else {
    goto native_l22_1;
  }
native_l22_1: ;
  native_s_5 = false;
  (void)native_s_5;
  native_s_8 = native_s_5;
  goto native_l22_3;
native_l22_2: ;
  native_s_6 = INT64_C(0);
  (void)native_s_6;
  native_s_7 = (native_s_6 <= native_v_1);
  native_s_8 = native_s_7;
  goto native_l22_3;
native_l22_3: ;
  if (native_s_8) {
    goto native_l22_4;
  } else {
    goto native_l22_5;
  }
native_l22_4: ;
  native_s_9 = (native_m0_type_50){ .tag = INT64_C(3), .payload = { .variant_3 = native_v_0 } };
  native_s_10 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_1 } };
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(1), .payload = { .variant_1 = native_v_1 } };
  native_s_12 = native_m0_fn_21((native_arena *)native_s_0, capability, native_s_9, native_s_10, native_s_11);
  native_s_14 = native_s_12;
  goto native_l22_6;
native_l22_5: ;
  native_s_13 = INT64_C(1);
  (void)native_s_13;
  native_trap((uint32_t)native_s_13);
native_l22_6: ;
  return native_s_14;
}
native_m0_type_6 native_m0_fn_23(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_9 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_6 native_s_6;
  native_m0_type_30 native_s_7;
  native_m0_type_50 native_s_8;
  native_m0_type_8 native_s_9;
  native_m0_type_1 native_s_10;
  native_m0_type_1 native_s_11;
  native_m0_type_6 native_s_12;
  native_m0_type_30 native_s_13;
  native_m0_type_50 native_s_14;
  native_m0_type_9 native_s_15;
  native_m0_type_6 native_s_16;
  native_m0_type_6 native_s_17;
  native_m0_type_6 native_s_18;
  native_m0_type_30 native_s_19;
  native_m0_type_50 native_s_20;
  native_m0_type_6 native_s_21;
  native_m0_type_6 native_s_22;
  native_m0_type_6 native_s_23;
  native_m0_type_30 native_s_24;
  native_m0_type_50 native_s_25;
  native_m0_type_1 native_s_26;
  native_m0_type_1 native_s_27;
  native_m0_type_6 native_s_28;
  native_m0_type_6 native_s_29;
  native_m0_type_6 native_s_30;
  native_m0_type_6 native_s_31;
  native_m0_type_6 native_s_32;
  native_m0_type_6 native_s_33;
  native_m0_type_6 native_s_34;
  native_m0_type_6 native_s_35;
  native_m0_type_6 native_s_36;
  native_m0_type_6 native_s_37;
  native_m0_type_6 native_s_38;
  native_m0_type_6 native_s_39;
  native_m0_type_6 native_s_40;
  native_m0_type_6 native_s_41;
  native_m0_type_6 native_s_42;
  native_m0_type_6 native_s_43;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_0;
  (void)native_s_0;
  native_s_1 = native_m0_fn_4(native_v_0);
  if (native_s_1) {
    goto native_l23_2;
  } else {
    goto native_l23_1;
  }
native_l23_1: ;
  native_s_41 = native_s_1;
  goto native_l23_32;
native_l23_2: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_v_0.payload.variant_7;
  native_s_3 = ((native_m0_type_51 *)native_s_2)->field_0;
  switch (native_s_3.tag) {
  case INT64_C(0):
    goto native_l23_4;
  case INT64_C(1):
    goto native_l23_4;
  case INT64_C(2):
    goto native_l23_4;
  case INT64_C(3):
    goto native_l23_3;
  case INT64_C(4):
    goto native_l23_4;
  case INT64_C(5):
    goto native_l23_4;
  case INT64_C(6):
    goto native_l23_4;
  case INT64_C(7):
    goto native_l23_4;
  case INT64_C(8):
    goto native_l23_4;
  case INT64_C(9):
    goto native_l23_4;
  case INT64_C(10):
    goto native_l23_4;
  case INT64_C(11):
    goto native_l23_4;
  case INT64_C(12):
    goto native_l23_4;
  case INT64_C(13):
    goto native_l23_4;
  case INT64_C(14):
    goto native_l23_4;
  case INT64_C(15):
    goto native_l23_4;
  case INT64_C(16):
    goto native_l23_4;
  case INT64_C(17):
    goto native_l23_4;
  case INT64_C(18):
    goto native_l23_4;
  case INT64_C(19):
    goto native_l23_4;
  case INT64_C(20):
    goto native_l23_4;
  case INT64_C(21):
    goto native_l23_4;
  case INT64_C(22):
    goto native_l23_4;
  case INT64_C(23):
    goto native_l23_4;
  case INT64_C(24):
    goto native_l23_4;
  case INT64_C(25):
    goto native_l23_4;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l23_3: ;
  native_s_4 = true;
  (void)native_s_4;
  native_s_6 = native_s_4;
  goto native_l23_5;
native_l23_4: ;
  native_s_5 = false;
  (void)native_s_5;
  native_s_6 = native_s_5;
  goto native_l23_5;
native_l23_5: ;
  if (native_s_6) {
    goto native_l23_7;
  } else {
    goto native_l23_6;
  }
native_l23_6: ;
  native_s_38 = native_s_6;
  goto native_l23_29;
native_l23_7: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_7 = native_v_0.payload.variant_7;
  native_s_8 = ((native_m0_type_51 *)native_s_7)->field_0;
  if (native_s_8.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_9 = native_s_8.payload.variant_3;
  native_s_10 = (int64_t)native_text_length(native_s_9);
  native_s_11 = INT64_C(0);
  (void)native_s_11;
  native_s_12 = (native_s_11 < native_s_10);
  if (native_s_12) {
    goto native_l23_9;
  } else {
    goto native_l23_8;
  }
native_l23_8: ;
  native_s_35 = native_s_12;
  goto native_l23_26;
native_l23_9: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_13 = native_v_0.payload.variant_7;
  native_s_14 = ((native_m0_type_51 *)native_s_13)->field_1;
  switch (native_s_14.tag) {
  case INT64_C(0):
    goto native_l23_11;
  case INT64_C(1):
    goto native_l23_11;
  case INT64_C(2):
    goto native_l23_11;
  case INT64_C(3):
    goto native_l23_11;
  case INT64_C(4):
    goto native_l23_10;
  case INT64_C(5):
    goto native_l23_11;
  case INT64_C(6):
    goto native_l23_11;
  case INT64_C(7):
    goto native_l23_11;
  case INT64_C(8):
    goto native_l23_11;
  case INT64_C(9):
    goto native_l23_11;
  case INT64_C(10):
    goto native_l23_11;
  case INT64_C(11):
    goto native_l23_11;
  case INT64_C(12):
    goto native_l23_11;
  case INT64_C(13):
    goto native_l23_11;
  case INT64_C(14):
    goto native_l23_11;
  case INT64_C(15):
    goto native_l23_11;
  case INT64_C(16):
    goto native_l23_11;
  case INT64_C(17):
    goto native_l23_11;
  case INT64_C(18):
    goto native_l23_11;
  case INT64_C(19):
    goto native_l23_11;
  case INT64_C(20):
    goto native_l23_11;
  case INT64_C(21):
    goto native_l23_11;
  case INT64_C(22):
    goto native_l23_11;
  case INT64_C(23):
    goto native_l23_11;
  case INT64_C(24):
    goto native_l23_11;
  case INT64_C(25):
    goto native_l23_11;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l23_10: ;
  if (native_s_14.tag != INT64_C(4)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_15 = native_s_14.payload.variant_4;
  native_s_16 = native_text_eq(native_s_0, native_s_15);
  native_s_18 = native_s_16;
  goto native_l23_12;
native_l23_11: ;
  native_s_17 = false;
  (void)native_s_17;
  native_s_18 = native_s_17;
  goto native_l23_12;
native_l23_12: ;
  if (native_s_18) {
    goto native_l23_14;
  } else {
    goto native_l23_13;
  }
native_l23_13: ;
  native_s_32 = native_s_18;
  goto native_l23_23;
native_l23_14: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_19 = native_v_0.payload.variant_7;
  native_s_20 = ((native_m0_type_51 *)native_s_19)->field_2;
  switch (native_s_20.tag) {
  case INT64_C(0):
    goto native_l23_16;
  case INT64_C(1):
    goto native_l23_15;
  case INT64_C(2):
    goto native_l23_16;
  case INT64_C(3):
    goto native_l23_16;
  case INT64_C(4):
    goto native_l23_16;
  case INT64_C(5):
    goto native_l23_16;
  case INT64_C(6):
    goto native_l23_16;
  case INT64_C(7):
    goto native_l23_16;
  case INT64_C(8):
    goto native_l23_16;
  case INT64_C(9):
    goto native_l23_16;
  case INT64_C(10):
    goto native_l23_16;
  case INT64_C(11):
    goto native_l23_16;
  case INT64_C(12):
    goto native_l23_16;
  case INT64_C(13):
    goto native_l23_16;
  case INT64_C(14):
    goto native_l23_16;
  case INT64_C(15):
    goto native_l23_16;
  case INT64_C(16):
    goto native_l23_16;
  case INT64_C(17):
    goto native_l23_16;
  case INT64_C(18):
    goto native_l23_16;
  case INT64_C(19):
    goto native_l23_16;
  case INT64_C(20):
    goto native_l23_16;
  case INT64_C(21):
    goto native_l23_16;
  case INT64_C(22):
    goto native_l23_16;
  case INT64_C(23):
    goto native_l23_16;
  case INT64_C(24):
    goto native_l23_16;
  case INT64_C(25):
    goto native_l23_16;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l23_15: ;
  native_s_21 = true;
  (void)native_s_21;
  native_s_23 = native_s_21;
  goto native_l23_17;
native_l23_16: ;
  native_s_22 = false;
  (void)native_s_22;
  native_s_23 = native_s_22;
  goto native_l23_17;
native_l23_17: ;
  if (native_s_23) {
    goto native_l23_19;
  } else {
    goto native_l23_18;
  }
native_l23_18: ;
  native_s_29 = native_s_23;
  goto native_l23_20;
native_l23_19: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_24 = native_v_0.payload.variant_7;
  native_s_25 = ((native_m0_type_51 *)native_s_24)->field_2;
  native_s_26 = INT64_C(0);
  (void)native_s_26;
  if (native_s_25.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_27 = native_s_25.payload.variant_1;
  native_s_28 = (native_s_26 <= native_s_27);
  native_s_30 = native_s_28;
  goto native_l23_21;
native_l23_20: ;
  native_s_31 = native_s_29;
  goto native_l23_22;
native_l23_21: ;
  native_s_31 = native_s_30;
  goto native_l23_22;
native_l23_22: ;
  native_s_33 = native_s_31;
  goto native_l23_24;
native_l23_23: ;
  native_s_34 = native_s_32;
  goto native_l23_25;
native_l23_24: ;
  native_s_34 = native_s_33;
  goto native_l23_25;
native_l23_25: ;
  native_s_36 = native_s_34;
  goto native_l23_27;
native_l23_26: ;
  native_s_37 = native_s_35;
  goto native_l23_28;
native_l23_27: ;
  native_s_37 = native_s_36;
  goto native_l23_28;
native_l23_28: ;
  native_s_39 = native_s_37;
  goto native_l23_30;
native_l23_29: ;
  native_s_40 = native_s_38;
  goto native_l23_31;
native_l23_30: ;
  native_s_40 = native_s_39;
  goto native_l23_31;
native_l23_31: ;
  native_s_42 = native_s_40;
  goto native_l23_33;
native_l23_32: ;
  native_s_43 = native_s_41;
  goto native_l23_34;
native_l23_33: ;
  native_s_43 = native_s_42;
  goto native_l23_34;
native_l23_34: ;
  return native_s_43;
}
native_m0_type_51 native_m0_fn_24(native_arena *arena, const native_capability *capability, native_m0_type_51 native_v_0, native_m0_type_1 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_0 native_s_0;
  native_m0_type_9 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_6 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_30 native_s_9;
  native_m0_type_50 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_51 native_s_13;
  native_m0_type_1 native_s_14;
  native_m0_type_51 native_s_15;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_keyword_1;
  (void)native_s_1;
  native_s_2 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_2 = native_v_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_2 } };
  native_s_4 = native_m0_fn_23(native_s_3);
  if (native_s_4) {
    goto native_l24_2;
  } else {
    goto native_l24_1;
  }
native_l24_1: ;
  native_s_5 = false;
  (void)native_s_5;
  native_s_8 = native_s_5;
  goto native_l24_3;
native_l24_2: ;
  native_s_6 = INT64_C(0);
  (void)native_s_6;
  native_s_7 = (native_s_6 <= native_v_1);
  native_s_8 = native_s_7;
  goto native_l24_3;
native_l24_3: ;
  if (native_s_8) {
    goto native_l24_4;
  } else {
    goto native_l24_5;
  }
native_l24_4: ;
  native_s_9 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_9 = native_v_0;
  native_s_10 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_9 } };
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_1 } };
  native_s_12 = (native_m0_type_50){ .tag = INT64_C(1), .payload = { .variant_1 = native_v_1 } };
  native_s_13 = native_m0_fn_21((native_arena *)native_s_0, capability, native_s_10, native_s_11, native_s_12);
  native_s_15 = native_s_13;
  goto native_l24_6;
native_l24_5: ;
  native_s_14 = INT64_C(1);
  (void)native_s_14;
  native_trap((uint32_t)native_s_14);
native_l24_6: ;
  return native_s_15;
}
native_m0_type_6 native_m0_fn_25(native_m0_type_50 native_v_0) {
  (void)native_v_0;
  native_m0_type_9 native_s_0;
  native_m0_type_6 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_30 native_s_5;
  native_m0_type_50 native_s_6;
  native_m0_type_9 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_6 native_s_10;
  native_m0_type_30 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_6 native_s_13;
  native_m0_type_6 native_s_14;
  native_m0_type_6 native_s_15;
  native_m0_type_30 native_s_16;
  native_m0_type_50 native_s_17;
  native_m0_type_1 native_s_18;
  native_m0_type_1 native_s_19;
  native_m0_type_6 native_s_20;
  native_m0_type_6 native_s_21;
  native_m0_type_6 native_s_22;
  native_m0_type_6 native_s_23;
  native_m0_type_6 native_s_24;
  native_m0_type_6 native_s_25;
  native_m0_type_6 native_s_26;
  native_m0_type_6 native_s_27;
  native_m0_type_6 native_s_28;
  native_m0_type_6 native_s_29;
  native_m0_type_6 native_s_30;
  native_m0_type_6 native_s_31;
  native_m0_type_6 native_s_32;
  native_s_0 = (uint64_t)(uintptr_t)&native_m0_keyword_1;
  (void)native_s_0;
  native_s_1 = native_m0_fn_4(native_v_0);
  if (native_s_1) {
    goto native_l25_2;
  } else {
    goto native_l25_1;
  }
native_l25_1: ;
  native_s_30 = native_s_1;
  goto native_l25_24;
native_l25_2: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_2 = native_v_0.payload.variant_7;
  native_s_3 = ((native_m0_type_51 *)native_s_2)->field_0;
  native_s_4 = native_m0_fn_23(native_s_3);
  if (native_s_4) {
    goto native_l25_4;
  } else {
    goto native_l25_3;
  }
native_l25_3: ;
  native_s_27 = native_s_4;
  goto native_l25_21;
native_l25_4: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_5 = native_v_0.payload.variant_7;
  native_s_6 = ((native_m0_type_51 *)native_s_5)->field_1;
  switch (native_s_6.tag) {
  case INT64_C(0):
    goto native_l25_6;
  case INT64_C(1):
    goto native_l25_6;
  case INT64_C(2):
    goto native_l25_6;
  case INT64_C(3):
    goto native_l25_6;
  case INT64_C(4):
    goto native_l25_5;
  case INT64_C(5):
    goto native_l25_6;
  case INT64_C(6):
    goto native_l25_6;
  case INT64_C(7):
    goto native_l25_6;
  case INT64_C(8):
    goto native_l25_6;
  case INT64_C(9):
    goto native_l25_6;
  case INT64_C(10):
    goto native_l25_6;
  case INT64_C(11):
    goto native_l25_6;
  case INT64_C(12):
    goto native_l25_6;
  case INT64_C(13):
    goto native_l25_6;
  case INT64_C(14):
    goto native_l25_6;
  case INT64_C(15):
    goto native_l25_6;
  case INT64_C(16):
    goto native_l25_6;
  case INT64_C(17):
    goto native_l25_6;
  case INT64_C(18):
    goto native_l25_6;
  case INT64_C(19):
    goto native_l25_6;
  case INT64_C(20):
    goto native_l25_6;
  case INT64_C(21):
    goto native_l25_6;
  case INT64_C(22):
    goto native_l25_6;
  case INT64_C(23):
    goto native_l25_6;
  case INT64_C(24):
    goto native_l25_6;
  case INT64_C(25):
    goto native_l25_6;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l25_5: ;
  if (native_s_6.tag != INT64_C(4)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_7 = native_s_6.payload.variant_4;
  native_s_8 = native_text_eq(native_s_0, native_s_7);
  native_s_10 = native_s_8;
  goto native_l25_7;
native_l25_6: ;
  native_s_9 = false;
  (void)native_s_9;
  native_s_10 = native_s_9;
  goto native_l25_7;
native_l25_7: ;
  if (native_s_10) {
    goto native_l25_9;
  } else {
    goto native_l25_8;
  }
native_l25_8: ;
  native_s_24 = native_s_10;
  goto native_l25_18;
native_l25_9: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_11 = native_v_0.payload.variant_7;
  native_s_12 = ((native_m0_type_51 *)native_s_11)->field_2;
  switch (native_s_12.tag) {
  case INT64_C(0):
    goto native_l25_11;
  case INT64_C(1):
    goto native_l25_10;
  case INT64_C(2):
    goto native_l25_11;
  case INT64_C(3):
    goto native_l25_11;
  case INT64_C(4):
    goto native_l25_11;
  case INT64_C(5):
    goto native_l25_11;
  case INT64_C(6):
    goto native_l25_11;
  case INT64_C(7):
    goto native_l25_11;
  case INT64_C(8):
    goto native_l25_11;
  case INT64_C(9):
    goto native_l25_11;
  case INT64_C(10):
    goto native_l25_11;
  case INT64_C(11):
    goto native_l25_11;
  case INT64_C(12):
    goto native_l25_11;
  case INT64_C(13):
    goto native_l25_11;
  case INT64_C(14):
    goto native_l25_11;
  case INT64_C(15):
    goto native_l25_11;
  case INT64_C(16):
    goto native_l25_11;
  case INT64_C(17):
    goto native_l25_11;
  case INT64_C(18):
    goto native_l25_11;
  case INT64_C(19):
    goto native_l25_11;
  case INT64_C(20):
    goto native_l25_11;
  case INT64_C(21):
    goto native_l25_11;
  case INT64_C(22):
    goto native_l25_11;
  case INT64_C(23):
    goto native_l25_11;
  case INT64_C(24):
    goto native_l25_11;
  case INT64_C(25):
    goto native_l25_11;
  default:
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
native_l25_10: ;
  native_s_13 = true;
  (void)native_s_13;
  native_s_15 = native_s_13;
  goto native_l25_12;
native_l25_11: ;
  native_s_14 = false;
  (void)native_s_14;
  native_s_15 = native_s_14;
  goto native_l25_12;
native_l25_12: ;
  if (native_s_15) {
    goto native_l25_14;
  } else {
    goto native_l25_13;
  }
native_l25_13: ;
  native_s_21 = native_s_15;
  goto native_l25_15;
native_l25_14: ;
  if (native_v_0.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_16 = native_v_0.payload.variant_7;
  native_s_17 = ((native_m0_type_51 *)native_s_16)->field_2;
  native_s_18 = INT64_C(0);
  (void)native_s_18;
  if (native_s_17.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_19 = native_s_17.payload.variant_1;
  native_s_20 = (native_s_18 <= native_s_19);
  native_s_22 = native_s_20;
  goto native_l25_16;
native_l25_15: ;
  native_s_23 = native_s_21;
  goto native_l25_17;
native_l25_16: ;
  native_s_23 = native_s_22;
  goto native_l25_17;
native_l25_17: ;
  native_s_25 = native_s_23;
  goto native_l25_19;
native_l25_18: ;
  native_s_26 = native_s_24;
  goto native_l25_20;
native_l25_19: ;
  native_s_26 = native_s_25;
  goto native_l25_20;
native_l25_20: ;
  native_s_28 = native_s_26;
  goto native_l25_22;
native_l25_21: ;
  native_s_29 = native_s_27;
  goto native_l25_23;
native_l25_22: ;
  native_s_29 = native_s_28;
  goto native_l25_23;
native_l25_23: ;
  native_s_31 = native_s_29;
  goto native_l25_25;
native_l25_24: ;
  native_s_32 = native_s_30;
  goto native_l25_26;
native_l25_25: ;
  native_s_32 = native_s_31;
  goto native_l25_26;
native_l25_26: ;
  return native_s_32;
}
native_m0_type_51 native_m0_fn_26(native_arena *arena, const native_capability *capability, native_m0_type_51 native_v_0, native_m0_type_51 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_0 native_s_0;
  native_m0_type_9 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_30 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_30 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_30 native_s_13;
  native_m0_type_50 native_s_14;
  native_m0_type_51 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_51 native_s_17;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_keyword_2;
  (void)native_s_1;
  native_s_2 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_2 = native_v_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_2 } };
  native_s_4 = native_m0_fn_25(native_s_3);
  if (native_s_4) {
    goto native_l26_2;
  } else {
    goto native_l26_1;
  }
native_l26_1: ;
  native_s_5 = false;
  (void)native_s_5;
  native_s_9 = native_s_5;
  goto native_l26_3;
native_l26_2: ;
  native_s_6 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_6 = native_v_1;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_6 } };
  native_s_8 = native_m0_fn_4(native_s_7);
  native_s_9 = native_s_8;
  goto native_l26_3;
native_l26_3: ;
  if (native_s_9) {
    goto native_l26_4;
  } else {
    goto native_l26_5;
  }
native_l26_4: ;
  native_s_10 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_10 = native_v_0;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_10 } };
  native_s_12 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_1 } };
  native_s_13 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_13 = native_v_1;
  native_s_14 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_13 } };
  native_s_15 = native_m0_fn_21((native_arena *)native_s_0, capability, native_s_11, native_s_12, native_s_14);
  native_s_17 = native_s_15;
  goto native_l26_6;
native_l26_5: ;
  native_s_16 = INT64_C(1);
  (void)native_s_16;
  native_trap((uint32_t)native_s_16);
native_l26_6: ;
  return native_s_17;
}
native_m0_type_51 native_m0_fn_27(native_arena *arena, const native_capability *capability, native_m0_type_51 native_v_0, native_m0_type_51 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_0 native_s_0;
  native_m0_type_9 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_30 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_30 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_30 native_s_13;
  native_m0_type_50 native_s_14;
  native_m0_type_51 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_51 native_s_17;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_keyword_3;
  (void)native_s_1;
  native_s_2 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_2 = native_v_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_2 } };
  native_s_4 = native_m0_fn_25(native_s_3);
  if (native_s_4) {
    goto native_l27_2;
  } else {
    goto native_l27_1;
  }
native_l27_1: ;
  native_s_5 = false;
  (void)native_s_5;
  native_s_9 = native_s_5;
  goto native_l27_3;
native_l27_2: ;
  native_s_6 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_6 = native_v_1;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_6 } };
  native_s_8 = native_m0_fn_4(native_s_7);
  native_s_9 = native_s_8;
  goto native_l27_3;
native_l27_3: ;
  if (native_s_9) {
    goto native_l27_4;
  } else {
    goto native_l27_5;
  }
native_l27_4: ;
  native_s_10 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_10 = native_v_0;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_10 } };
  native_s_12 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_1 } };
  native_s_13 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_13 = native_v_1;
  native_s_14 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_13 } };
  native_s_15 = native_m0_fn_21((native_arena *)native_s_0, capability, native_s_11, native_s_12, native_s_14);
  native_s_17 = native_s_15;
  goto native_l27_6;
native_l27_5: ;
  native_s_16 = INT64_C(1);
  (void)native_s_16;
  native_trap((uint32_t)native_s_16);
native_l27_6: ;
  return native_s_17;
}
native_m0_type_51 native_m0_fn_28(native_arena *arena, const native_capability *capability, native_m0_type_51 native_v_0, native_m0_type_51 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_0 native_s_0;
  native_m0_type_9 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_30 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_30 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_30 native_s_13;
  native_m0_type_50 native_s_14;
  native_m0_type_51 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_51 native_s_17;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_keyword_4;
  (void)native_s_1;
  native_s_2 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_2 = native_v_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_2 } };
  native_s_4 = native_m0_fn_25(native_s_3);
  if (native_s_4) {
    goto native_l28_2;
  } else {
    goto native_l28_1;
  }
native_l28_1: ;
  native_s_5 = false;
  (void)native_s_5;
  native_s_9 = native_s_5;
  goto native_l28_3;
native_l28_2: ;
  native_s_6 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_6 = native_v_1;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_6 } };
  native_s_8 = native_m0_fn_25(native_s_7);
  native_s_9 = native_s_8;
  goto native_l28_3;
native_l28_3: ;
  if (native_s_9) {
    goto native_l28_4;
  } else {
    goto native_l28_5;
  }
native_l28_4: ;
  native_s_10 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_10 = native_v_0;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_10 } };
  native_s_12 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_1 } };
  native_s_13 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_13 = native_v_1;
  native_s_14 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_13 } };
  native_s_15 = native_m0_fn_21((native_arena *)native_s_0, capability, native_s_11, native_s_12, native_s_14);
  native_s_17 = native_s_15;
  goto native_l28_6;
native_l28_5: ;
  native_s_16 = INT64_C(1);
  (void)native_s_16;
  native_trap((uint32_t)native_s_16);
native_l28_6: ;
  return native_s_17;
}
native_m0_type_51 native_m0_fn_29(native_arena *arena, const native_capability *capability, native_m0_type_51 native_v_0, native_m0_type_2 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_0 native_s_0;
  native_m0_type_9 native_s_1;
  native_m0_type_30 native_s_2;
  native_m0_type_50 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_6 native_s_5;
  native_m0_type_32 native_s_6;
  native_m0_type_50 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_6 native_s_9;
  native_m0_type_30 native_s_10;
  native_m0_type_50 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_32 native_s_13;
  native_m0_type_50 native_s_14;
  native_m0_type_51 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_51 native_s_17;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m0_keyword_5;
  (void)native_s_1;
  native_s_2 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_2 = native_v_0;
  native_s_3 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_2 } };
  native_s_4 = native_m0_fn_4(native_s_3);
  if (native_s_4) {
    goto native_l29_2;
  } else {
    goto native_l29_1;
  }
native_l29_1: ;
  native_s_5 = false;
  (void)native_s_5;
  native_s_9 = native_s_5;
  goto native_l29_3;
native_l29_2: ;
  native_s_6 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_2), _Alignof(native_m0_type_2));
  *(native_m0_type_2 *)native_s_6 = native_v_1;
  native_s_7 = (native_m0_type_50){ .tag = INT64_C(6), .payload = { .variant_6 = native_s_6 } };
  native_s_8 = native_m0_fn_0(native_s_7);
  native_s_9 = native_s_8;
  goto native_l29_3;
native_l29_3: ;
  if (native_s_9) {
    goto native_l29_4;
  } else {
    goto native_l29_5;
  }
native_l29_4: ;
  native_s_10 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_10 = native_v_0;
  native_s_11 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_10 } };
  native_s_12 = (native_m0_type_50){ .tag = INT64_C(4), .payload = { .variant_4 = native_s_1 } };
  native_s_13 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_2), _Alignof(native_m0_type_2));
  *(native_m0_type_2 *)native_s_13 = native_v_1;
  native_s_14 = (native_m0_type_50){ .tag = INT64_C(6), .payload = { .variant_6 = native_s_13 } };
  native_s_15 = native_m0_fn_21((native_arena *)native_s_0, capability, native_s_11, native_s_12, native_s_14);
  native_s_17 = native_s_15;
  goto native_l29_6;
native_l29_5: ;
  native_s_16 = INT64_C(1);
  (void)native_s_16;
  native_trap((uint32_t)native_s_16);
native_l29_6: ;
  return native_s_17;
}
native_m0_type_6 native_m0_fn_30(native_arena *arena, const native_capability *capability, native_m0_type_51 native_v_0, native_m0_type_51 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m0_type_0 native_s_0;
  native_m0_type_30 native_s_1;
  native_m0_type_50 native_s_2;
  native_m0_type_6 native_s_3;
  native_m0_type_6 native_s_4;
  native_m0_type_30 native_s_5;
  native_m0_type_50 native_s_6;
  native_m0_type_6 native_s_7;
  native_m0_type_6 native_s_8;
  native_m0_type_50 native_s_9;
  native_m0_type_30 native_s_10;
  native_m0_type_51 native_s_11;
  native_m0_type_50 native_s_12;
  native_m0_type_30 native_s_13;
  native_m0_type_51 native_s_14;
  native_m0_type_50 native_s_15;
  native_m0_type_8 native_s_16;
  native_m0_type_50 native_s_17;
  native_m0_type_8 native_s_18;
  native_m0_type_50 native_s_19;
  native_m0_type_1 native_s_20;
  native_m0_type_50 native_s_21;
  native_m0_type_1 native_s_22;
  native_m0_type_50 native_s_23;
  native_m0_type_1 native_s_24;
  native_m0_type_50 native_s_25;
  native_m0_type_1 native_s_26;
  native_m0_type_6 native_s_27;
  native_m0_type_6 native_s_28;
  native_m0_type_6 native_s_29;
  native_m0_type_6 native_s_30;
  native_m0_type_6 native_s_31;
  native_m0_type_6 native_s_32;
  native_m0_type_6 native_s_33;
  native_m0_type_6 native_s_34;
  native_m0_type_6 native_s_35;
  native_m0_type_6 native_s_36;
  native_m0_type_1 native_s_37;
  native_m0_type_6 native_s_38;
  native_m0_type_1 native_s_39;
  native_m0_type_6 native_s_40;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_1 = native_v_0;
  native_s_2 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_1 } };
  native_s_3 = native_m0_fn_25(native_s_2);
  if (native_s_3) {
    goto native_l30_2;
  } else {
    goto native_l30_1;
  }
native_l30_1: ;
  native_s_4 = false;
  (void)native_s_4;
  native_s_8 = native_s_4;
  goto native_l30_3;
native_l30_2: ;
  native_s_5 = native_arena_alloc((native_arena *)native_s_0, sizeof(native_m0_type_51), _Alignof(native_m0_type_51));
  *(native_m0_type_51 *)native_s_5 = native_v_1;
  native_s_6 = (native_m0_type_50){ .tag = INT64_C(7), .payload = { .variant_7 = native_s_5 } };
  native_s_7 = native_m0_fn_25(native_s_6);
  native_s_8 = native_s_7;
  goto native_l30_3;
native_l30_3: ;
  if (native_s_8) {
    goto native_l30_4;
  } else {
    goto native_l30_18;
  }
native_l30_4: ;
  native_s_9 = native_v_0.field_0;
  if (native_s_9.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_10 = native_s_9.payload.variant_7;
  if (native_s_10 == NULL) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_11 = *((const native_m0_type_51 *)native_s_10);
  native_s_12 = native_v_1.field_0;
  if (native_s_12.tag != INT64_C(7)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_13 = native_s_12.payload.variant_7;
  if (native_s_13 == NULL) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_14 = *((const native_m0_type_51 *)native_s_13);
  native_s_15 = native_s_11.field_0;
  if (native_s_15.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_16 = native_s_15.payload.variant_3;
  native_s_17 = native_s_14.field_0;
  if (native_s_17.tag != INT64_C(3)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_18 = native_s_17.payload.variant_3;
  native_s_19 = native_s_11.field_2;
  if (native_s_19.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_20 = native_s_19.payload.variant_1;
  native_s_21 = native_s_14.field_2;
  if (native_s_21.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_22 = native_s_21.payload.variant_1;
  native_s_23 = native_v_0.field_2;
  if (native_s_23.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_24 = native_s_23.payload.variant_1;
  native_s_25 = native_v_1.field_2;
  if (native_s_25.tag != INT64_C(1)) {
    native_trap(NATIVE_TRAP_INVALID_ARGUMENT);
  }
  native_s_26 = native_s_25.payload.variant_1;
  native_s_27 = native_text_eq(native_s_16, native_s_18);
  if (native_s_27) {
    goto native_l30_5;
  } else {
    goto native_l30_16;
  }
native_l30_5: ;
  native_s_28 = (native_s_20 < native_s_22);
  if (native_s_28) {
    goto native_l30_6;
  } else {
    goto native_l30_7;
  }
native_l30_6: ;
  native_s_34 = native_s_28;
  goto native_l30_13;
native_l30_7: ;
  native_s_29 = (native_s_20 == native_s_22);
  if (native_s_29) {
    goto native_l30_9;
  } else {
    goto native_l30_8;
  }
native_l30_8: ;
  native_s_31 = native_s_29;
  goto native_l30_10;
native_l30_9: ;
  native_s_30 = (native_s_24 < native_s_26);
  native_s_32 = native_s_30;
  goto native_l30_11;
native_l30_10: ;
  native_s_33 = native_s_31;
  goto native_l30_12;
native_l30_11: ;
  native_s_33 = native_s_32;
  goto native_l30_12;
native_l30_12: ;
  native_s_35 = native_s_33;
  goto native_l30_14;
native_l30_13: ;
  native_s_36 = native_s_34;
  goto native_l30_15;
native_l30_14: ;
  native_s_36 = native_s_35;
  goto native_l30_15;
native_l30_15: ;
  native_s_38 = native_s_36;
  goto native_l30_17;
native_l30_16: ;
  native_s_37 = INT64_C(1);
  (void)native_s_37;
  native_trap((uint32_t)native_s_37);
native_l30_17: ;
  native_s_40 = native_s_38;
  goto native_l30_19;
native_l30_18: ;
  native_s_39 = INT64_C(1);
  (void)native_s_39;
  native_trap((uint32_t)native_s_39);
native_l30_19: ;
  return native_s_40;
}
