#lang racket/base

;; Pre-typed catalog of common Clojure stdlib functions.
;;
;; This exists to give the type checker something to work with when beagle
;; programs call stdlib functions. Without this, every call to `first`, `map`,
;; `seq` etc. returns `Any` and the checker is mostly useless. With it, simple
;; programs get real type checking on the most common Clojure operations.
;;
;; Coverage is intentionally conservative — only functions whose types are
;; easy to express in beagle's v0 type system. Polymorphic functions like
;; `map`, `filter`, `reduce` use `Any` for their parametric positions until
;; we have proper parametric function types.

(require "types.rkt" racket/set)

(define (p x) (type-prim x))
(define (tv x) (type-var x))

(define (fn-of args ret #:rest [rest #f])
  (type-fn (map p args)
           (and rest (p rest))
           (p ret)))

(define (poly-fn vars param-types ret-type #:rest [rest-type #f])
  (type-poly vars
    (type-fn param-types rest-type ret-type)))

(define STDLIB-TYPES
  (hash
   ;; --- collection access (parametric → Any in v0) --------------------------
   'first      (fn-of '(Any) 'Any)
   'second     (fn-of '(Any) 'Any)
   'last       (fn-of '(Any) 'Any)
   'rest       (fn-of '(Any) 'Any)
   'next       (fn-of '(Any) 'Any)
   'nth        (fn-of '(Any Long) 'Any #:rest 'Any)
   'get        (fn-of '(Any Any) 'Any #:rest 'Any)
   'get-in     (fn-of '(Any Any) 'Any #:rest 'Any)
   'count      (fn-of '(Any) 'Long)
   'empty?     (fn-of '(Any) 'Boolean)
   'seq        (fn-of '(Any) 'Any)
   'into       (fn-of '(Any Any) 'Any)
   'conj       (fn-of '(Any) 'Any #:rest 'Any)
   'cons       (fn-of '(Any Any) 'Any)
   'concat     (fn-of '() 'Any #:rest 'Any)
   'reverse    (fn-of '(Any) 'Any)
   'distinct   (fn-of '(Any) 'Any)
   'sort       (fn-of '(Any) 'Any #:rest 'Any)
   'sort-by    (fn-of '(Any Any) 'Any #:rest 'Any)
   'ffirst     (fn-of '(Any) 'Any)
   ;; --- higher-order (polymorphic where useful) -----------------------------
   'map        (poly-fn '(A B)
                 (list (type-fn (list (tv 'A)) #f (tv 'B)))
                 (p 'Any)
                 #:rest (p 'Any))
   'mapv       (poly-fn '(A B)
                 (list (type-fn (list (tv 'A)) #f (tv 'B))
                       (p 'Any))
                 (type-app 'Vec (list (tv 'B))))
   'filter     (poly-fn '(A)
                 (list (type-fn (list (tv 'A)) #f (p 'Any))
                       (p 'Any))
                 (p 'Any))
   'filterv    (poly-fn '(A)
                 (list (type-fn (list (tv 'A)) #f (p 'Any))
                       (p 'Any))
                 (type-app 'Vec (list (tv 'A))))
   'remove     (poly-fn '(A)
                 (list (type-fn (list (tv 'A)) #f (p 'Any))
                       (p 'Any))
                 (p 'Any))
   'mapcat     (fn-of '(Any Any) 'Any #:rest 'Any)
   'reduce     (fn-of '(Any Any) 'Any #:rest 'Any)
   'apply      (fn-of '(Any Any) 'Any #:rest 'Any)
   'comp       (fn-of '() 'Any #:rest 'Any)
   'partial    (fn-of '(Any) 'Any #:rest 'Any)
   ;; --- string ops ---------------------------------------------------------
   'str        (fn-of '() 'String #:rest 'Any)
   'name       (fn-of '(Any) 'String)
   'keyword    (fn-of '(String) 'Keyword)
   'symbol     (fn-of '(String) 'Symbol)
   ;; --- math (variadic on Long; Clojure's are polymorphic, v0 narrows) -----
   ;; Math operators are polymorphic in real Clojure (Long/Double/Ratio).
   ;; v0 types them as variadic Any to avoid spurious type errors on FP work.
   '+          (fn-of '() 'Any #:rest 'Any)
   '-          (fn-of '(Any) 'Any #:rest 'Any)
   '*          (fn-of '() 'Any #:rest 'Any)
   '/          (fn-of '(Any) 'Any #:rest 'Any)
   'mod        (fn-of '(Long Long) 'Long)
   'quot       (fn-of '(Long Long) 'Long)
   'rem        (fn-of '(Long Long) 'Long)
   'inc        (fn-of '(Long) 'Long)
   'dec        (fn-of '(Long) 'Long)
   'min        (fn-of '(Long) 'Long #:rest 'Long)
   'max        (fn-of '(Long) 'Long #:rest 'Long)
   'abs        (fn-of '(Long) 'Long)
   'zero?      (fn-of '(Long) 'Boolean)
   'pos?       (fn-of '(Long) 'Boolean)
   'neg?       (fn-of '(Long) 'Boolean)
   'even?      (fn-of '(Long) 'Boolean)
   'odd?       (fn-of '(Long) 'Boolean)
   ;; --- equality / ordering ------------------------------------------------
   '=          (fn-of '(Any Any) 'Boolean)
   'not=       (fn-of '(Any Any) 'Boolean)
   '<          (fn-of '(Long Long) 'Boolean)
   '>          (fn-of '(Long Long) 'Boolean)
   '<=         (fn-of '(Long Long) 'Boolean)
   '>=         (fn-of '(Long Long) 'Boolean)
   'identical? (fn-of '(Any Any) 'Boolean)
   'compare    (fn-of '(Any Any) 'Long)
   'boolean    (fn-of '(Any) 'Boolean)
   ;; --- boolean ------------------------------------------------------------
   'not        (fn-of '(Boolean) 'Boolean)
   'and        (fn-of '() 'Any #:rest 'Any)
   'or         (fn-of '() 'Any #:rest 'Any)
   'true?      (fn-of '(Any) 'Boolean)
   'false?     (fn-of '(Any) 'Boolean)
   'nil?       (fn-of '(Any) 'Boolean)
   'some?      (fn-of '(Any) 'Boolean)
   'parse-long   (fn-of '(String) 'Any)
   'parse-double (fn-of '(String) 'Any)
   ;; --- io -----------------------------------------------------------------
   'println    (fn-of '() 'Nil #:rest 'Any)
   'print      (fn-of '() 'Nil #:rest 'Any)
   'pr         (fn-of '() 'Nil #:rest 'Any)
   'pr-str     (fn-of '() 'String #:rest 'Any)
   'newline    (fn-of '() 'Nil)
   'prn        (fn-of '() 'Nil #:rest 'Any)
   'slurp      (fn-of '(Any) 'String)
   'spit       (fn-of '(Any Any) 'Nil #:rest 'Any)
   'read-string (fn-of '(String) 'Any)
   ;; --- identity / value ---------------------------------------------------
   'identity   (poly-fn '(A) (list (tv 'A)) (tv 'A))
   'constantly (fn-of '(Any) 'Any)
   ;; --- sequence generators / iteration ------------------------------------
   'range      (fn-of '() 'Any #:rest 'Any)    ; (range), (range n), (range a b), (range a b step)
   'repeat     (fn-of '(Any) 'Any #:rest 'Any) ; (repeat x), (repeat n x)
   'iterate    (fn-of '(Any Any) 'Any)
   'take       (fn-of '(Long Any) 'Any)
   'drop       (fn-of '(Long Any) 'Any)
   'take-while (fn-of '(Any Any) 'Any)
   'drop-while (fn-of '(Any Any) 'Any)
   'partition  (fn-of '(Long Any) 'Any #:rest 'Any)
   'interpose  (fn-of '(Any Any) 'Any)
   ;; --- predicates over collections ----------------------------------------
   'some       (fn-of '(Any Any) 'Any)        ; (some pred coll) — first truthy or nil
   'every?     (fn-of '(Any Any) 'Boolean)    ; (every? pred coll)
   ;; --- collection construction --------------------------------------------
   'vec        (fn-of '(Any) 'Any)
   'vector     (fn-of '() 'Any #:rest 'Any)
   'list       (fn-of '() 'Any #:rest 'Any)
   'hash-map   (fn-of '() 'Any #:rest 'Any)
   'sorted-map (fn-of '() 'Any #:rest 'Any)
   'set        (fn-of '(Any) 'Any)
   'hash-set   (fn-of '() 'Any #:rest 'Any)
   ;; --- map / set operations -----------------------------------------------
   'keys       (fn-of '(Any) 'Any)
   'vals       (fn-of '(Any) 'Any)
   'assoc      (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'dissoc     (fn-of '(Any) 'Any #:rest 'Any)
   'update     (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'update-in  (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'merge      (fn-of '() 'Any #:rest 'Any)
   'select-keys (fn-of '(Any Any) 'Any)
   'contains?  (fn-of '(Any Any) 'Boolean)
   'find       (fn-of '(Any Any) 'Any)
   'key        (fn-of '(Any) 'Any)
   'val        (fn-of '(Any) 'Any)
   'merge-with (fn-of '(Any) 'Any #:rest 'Any)
   ;; --- string / type predicates -------------------------------------------
   'subs       (fn-of '(String Long) 'String #:rest 'Long)
   'string?    (fn-of '(Any) 'Boolean)
   'number?    (fn-of '(Any) 'Boolean)
   'integer?   (fn-of '(Any) 'Boolean)
   'keyword?   (fn-of '(Any) 'Boolean)
   'symbol?    (fn-of '(Any) 'Boolean)
   'map?       (fn-of '(Any) 'Boolean)
   'vector?    (fn-of '(Any) 'Boolean)
   'list?      (fn-of '(Any) 'Boolean)
   'set?       (fn-of '(Any) 'Boolean)
   'coll?      (fn-of '(Any) 'Boolean)
   'sequential? (fn-of '(Any) 'Boolean)
   'fn?        (fn-of '(Any) 'Boolean)
   ;; --- error / control ----------------------------------------------------
   'ex-info    (fn-of '(String Any) 'Any)
   'ex-data    (fn-of '(Any) 'Any)
   'ex-message (fn-of '(Any) 'String)
   'throw      (fn-of '(Any) 'Any)
   ;; --- collection: more access / manipulation -----------------------------
   'nfirst     (fn-of '(Any) 'Any)
   'nnext      (fn-of '(Any) 'Any)
   'fnext      (fn-of '(Any) 'Any)
   'peek       (fn-of '(Any) 'Any)
   'pop        (fn-of '(Any) 'Any)
   'rand-nth   (fn-of '(Any) 'Any)
   'shuffle    (fn-of '(Any) 'Any)
   'flatten    (fn-of '(Any) 'Any)
   'frequencies (fn-of '(Any) 'Any)
   'group-by   (fn-of '(Any Any) 'Any)
   'zipmap     (fn-of '(Any Any) 'Any)
   'not-empty  (fn-of '(Any) 'Any)
   'butlast    (fn-of '(Any) 'Any)
   'nthrest    (fn-of '(Any Long) 'Any)
   'nthnext    (fn-of '(Any Long) 'Any)
   'subvec     (fn-of '(Any Long) 'Any #:rest 'Long)
   'assoc-in   (fn-of '(Any Any Any) 'Any)
   ;; --- higher-order: more -------------------------------------------------
   'map-indexed (fn-of '(Any Any) 'Any)
   'keep       (fn-of '(Any Any) 'Any)
   'keep-indexed (fn-of '(Any Any) 'Any)
   'run!       (fn-of '(Any Any) 'Nil)
   'juxt       (fn-of '(Any) 'Any #:rest 'Any)
   'complement (fn-of '(Any) 'Any)
   'fnil       (fn-of '(Any) 'Any #:rest 'Any)
   'memoize    (fn-of '(Any) 'Any)
   'trampoline (fn-of '(Any) 'Any #:rest 'Any)
   'reductions (fn-of '(Any Any) 'Any #:rest 'Any)
   ;; --- sequence: more generation / transformation -------------------------
   'cycle      (fn-of '(Any) 'Any)
   'interleave (fn-of '(Any Any) 'Any #:rest 'Any)
   'partition-by (fn-of '(Any Any) 'Any)
   'partition-all (fn-of '(Long Any) 'Any)
   'split-at   (fn-of '(Long Any) 'Any)
   'split-with (fn-of '(Any Any) 'Any)
   'take-last  (fn-of '(Long Any) 'Any)
   'drop-last  (fn-of '(Any) 'Any #:rest 'Any)
   'dedupe     (fn-of '(Any) 'Any)
   'replace    (fn-of '(Any Any) 'Any)
   'repeatedly (fn-of '(Any) 'Any #:rest 'Any)
   ;; --- transducers --------------------------------------------------------
   'transduce  (fn-of '(Any Any Any Any) 'Any)
   'sequence   (fn-of '(Any Any) 'Any)
   'eduction   (fn-of '() 'Any #:rest 'Any)
   'completing (fn-of '(Any) 'Any #:rest 'Any)
   'halt-when  (fn-of '(Any) 'Any #:rest 'Any)
   'cat        (fn-of '(Any) 'Any)
   ;; --- map / set: more operations -----------------------------------------
   'rename-keys (fn-of '(Any Any) 'Any)
   'map-keys   (fn-of '(Any Any) 'Any)
   'map-vals   (fn-of '(Any Any) 'Any)
   ;; --- atom / ref ---------------------------------------------------------
   'atom       (fn-of '(Any) 'Any)
   'deref      (fn-of '(Any) 'Any)
   'reset!     (fn-of '(Any Any) 'Any)
   'swap!      (fn-of '(Any Any) 'Any #:rest 'Any)
   'compare-and-set! (fn-of '(Any Any Any) 'Boolean)
   'add-watch  (fn-of '(Any Any Any) 'Any)
   'remove-watch (fn-of '(Any Any) 'Any)
   'volatile!  (fn-of '(Any) 'Any)
   'vreset!    (fn-of '(Any Any) 'Any)
   'vswap!     (fn-of '(Any Any) 'Any #:rest 'Any)
   ;; --- delay / promise / future -------------------------------------------
   'delay      (fn-of '(Any) 'Any)
   'force      (fn-of '(Any) 'Any)
   'realized?  (fn-of '(Any) 'Boolean)
   'deliver    (fn-of '(Any Any) 'Any)
   'promise    (fn-of '() 'Any)
   ;; --- type coercion / casting -------------------------------------------
   'int        (fn-of '(Any) 'Long)
   'long       (fn-of '(Any) 'Long)
   'float      (fn-of '(Any) 'Double)
   'double     (fn-of '(Any) 'Double)
   'short      (fn-of '(Any) 'Long)
   'byte       (fn-of '(Any) 'Long)
   'char       (fn-of '(Any) 'Any)
   'bigint     (fn-of '(Any) 'Any)
   'biginteger (fn-of '(Any) 'Any)
   'bigdec     (fn-of '(Any) 'Any)
   'num        (fn-of '(Any) 'Any)
   'rationalize (fn-of '(Any) 'Any)
   ;; --- type predicates: more ---------------------------------------------
   'char?      (fn-of '(Any) 'Boolean)
   'float?     (fn-of '(Any) 'Boolean)
   'double?    (fn-of '(Any) 'Boolean)
   'int?       (fn-of '(Any) 'Boolean)
   'nat-int?   (fn-of '(Any) 'Boolean)
   'pos-int?   (fn-of '(Any) 'Boolean)
   'neg-int?   (fn-of '(Any) 'Boolean)
   'decimal?   (fn-of '(Any) 'Boolean)
   'ratio?     (fn-of '(Any) 'Boolean)
   'rational?  (fn-of '(Any) 'Boolean)
   'associative? (fn-of '(Any) 'Boolean)
   'sorted?    (fn-of '(Any) 'Boolean)
   'counted?   (fn-of '(Any) 'Boolean)
   'reversible? (fn-of '(Any) 'Boolean)
   'seqable?   (fn-of '(Any) 'Boolean)
   'indexed?   (fn-of '(Any) 'Boolean)
   'ifn?       (fn-of '(Any) 'Boolean)
   'ident?     (fn-of '(Any) 'Boolean)
   'qualified-ident? (fn-of '(Any) 'Boolean)
   'simple-ident? (fn-of '(Any) 'Boolean)
   'qualified-keyword? (fn-of '(Any) 'Boolean)
   'simple-keyword? (fn-of '(Any) 'Boolean)
   'qualified-symbol? (fn-of '(Any) 'Boolean)
   'simple-symbol? (fn-of '(Any) 'Boolean)
   'uri?       (fn-of '(Any) 'Boolean)
   'uuid?      (fn-of '(Any) 'Boolean)
   'inst?      (fn-of '(Any) 'Boolean)
   'bytes?     (fn-of '(Any) 'Boolean)
   'class?     (fn-of '(Any) 'Boolean)
   'record?    (fn-of '(Any) 'Boolean)
   'satisfies? (fn-of '(Any Any) 'Boolean)
   'instance?  (fn-of '(Any Any) 'Boolean)
   'extends?   (fn-of '(Any Any) 'Boolean)
   ;; --- string: more -------------------------------------------------------
   'format     (fn-of '(String) 'String #:rest 'Any)
   'char-escape-string (fn-of '(Any) 'Any)
   'clojure.string/join     (fn-of '(Any) 'String #:rest 'Any)
   'clojure.string/split    (fn-of '(String Any) 'Any)
   'clojure.string/replace  (fn-of '(String Any Any) 'String)
   'clojure.string/trim     (fn-of '(String) 'String)
   'clojure.string/triml    (fn-of '(String) 'String)
   'clojure.string/trimr    (fn-of '(String) 'String)
   'clojure.string/upper-case (fn-of '(String) 'String)
   'clojure.string/lower-case (fn-of '(String) 'String)
   'clojure.string/capitalize (fn-of '(String) 'String)
   'clojure.string/blank?   (fn-of '(Any) 'Boolean)
   'clojure.string/includes? (fn-of '(String String) 'Boolean)
   'clojure.string/starts-with? (fn-of '(String String) 'Boolean)
   'clojure.string/ends-with? (fn-of '(String String) 'Boolean)
   'clojure.string/reverse  (fn-of '(String) 'String)
   'clojure.string/escape   (fn-of '(String Any) 'String)
   'clojure.string/re-quote-replacement (fn-of '(String) 'String)
   'clojure.string/index-of (fn-of '(String Any) 'Any)
   'clojure.string/last-index-of (fn-of '(String Any) 'Any)
   ;; --- clojure.set -------------------------------------------------------
   'clojure.set/union       (fn-of '() 'Any #:rest 'Any)
   'clojure.set/intersection (fn-of '(Any) 'Any #:rest 'Any)
   'clojure.set/difference  (fn-of '(Any) 'Any #:rest 'Any)
   'clojure.set/select      (fn-of '(Any Any) 'Any)
   'clojure.set/project     (fn-of '(Any Any) 'Any)
   'clojure.set/rename       (fn-of '(Any Any) 'Any)
   'clojure.set/join        (fn-of '(Any Any) 'Any #:rest 'Any)
   'clojure.set/map-invert  (fn-of '(Any) 'Any)
   'clojure.set/index       (fn-of '(Any Any) 'Any)
   'clojure.set/subset?     (fn-of '(Any Any) 'Boolean)
   'clojure.set/superset?   (fn-of '(Any Any) 'Boolean)
   ;; --- clojure.walk -------------------------------------------------------
   'clojure.walk/walk       (fn-of '(Any Any Any) 'Any)
   'clojure.walk/postwalk   (fn-of '(Any Any) 'Any)
   'clojure.walk/prewalk    (fn-of '(Any Any) 'Any)
   'clojure.walk/postwalk-replace (fn-of '(Any Any) 'Any)
   'clojure.walk/prewalk-replace  (fn-of '(Any Any) 'Any)
   'clojure.walk/stringify-keys   (fn-of '(Any) 'Any)
   'clojure.walk/keywordize-keys  (fn-of '(Any) 'Any)
   ;; --- clojure.java.io ----------------------------------------------------
   'clojure.java.io/file          (fn-of '(String) 'Any #:rest 'String)
   'clojure.java.io/reader        (fn-of '(Any) 'Any)
   'clojure.java.io/writer        (fn-of '(Any) 'Any)
   'clojure.java.io/input-stream  (fn-of '(Any) 'Any)
   'clojure.java.io/output-stream (fn-of '(Any) 'Any)
   'clojure.java.io/resource      (fn-of '(String) 'Any)
   'clojure.java.io/copy          (fn-of '(Any Any) 'Any)
   'clojure.java.io/delete-file   (fn-of '(Any) 'Boolean #:rest 'Any)
   'clojure.java.io/make-parents  (fn-of '(Any) 'Boolean)
   ;; --- clojure.pprint ------------------------------------------------------
   'clojure.pprint/pprint       (fn-of '(Any) 'Nil #:rest 'Any)
   'clojure.pprint/cl-format    (fn-of '(Any String) 'Any #:rest 'Any)
   'clojure.pprint/print-table  (fn-of '(Any) 'Nil #:rest 'Any)
   ;; --- clojure.edn -------------------------------------------------------
   'clojure.edn/read-string (fn-of '(String) 'Any)
   ;; --- regex / matching ---------------------------------------------------
   're-pattern (fn-of '(String) 'Any)
   're-matches (fn-of '(Any String) 'Any)
   're-find    (fn-of '(Any) 'Any #:rest 'Any)
   're-seq     (fn-of '(Any String) 'Any)
   're-groups  (fn-of '(Any) 'Any)
   ;; --- namespace / var inspection ----------------------------------------
   'namespace  (fn-of '(Any) 'Any)
   'type       (fn-of '(Any) 'Any)
   'class      (fn-of '(Any) 'Any)
   'supers     (fn-of '(Any) 'Any)
   'bases      (fn-of '(Any) 'Any)
   'meta       (fn-of '(Any) 'Any)
   'with-meta  (fn-of '(Any Any) 'Any)
   'vary-meta  (fn-of '(Any Any) 'Any #:rest 'Any)
   'alter-meta! (fn-of '(Any Any) 'Any #:rest 'Any)
   ;; --- misc core ----------------------------------------------------------
   'rand       (fn-of '() 'Double #:rest 'Any)
   'rand-int   (fn-of '(Long) 'Long)
   'gensym     (fn-of '() 'Symbol #:rest 'Any)
   'hash       (fn-of '(Any) 'Long)
   'max-key    (fn-of '(Any Any) 'Any #:rest 'Any)
   'min-key    (fn-of '(Any Any) 'Any #:rest 'Any)
   'not-any?   (fn-of '(Any Any) 'Boolean)
   'not-every? (fn-of '(Any Any) 'Boolean)
   'bounded-count (fn-of '(Long Any) 'Long)
   'tagged-literal (fn-of '(Symbol Any) 'Any)
   'tagged-literal? (fn-of '(Any) 'Boolean)
   'inst-ms    (fn-of '(Any) 'Long)
   'uuid       (fn-of '(String) 'Any)
   'random-uuid (fn-of '() 'Any)
   'parse-uuid (fn-of '(String) 'Any)
   'parse-boolean (fn-of '(String) 'Any)
   ;; --- printing / formatting ----------------------------------------------
   'with-out-str (fn-of '() 'String #:rest 'Any)
   'print-str  (fn-of '() 'String #:rest 'Any)
   'println-str (fn-of '() 'String #:rest 'Any)
   'printf     (fn-of '(String) 'Nil #:rest 'Any)
   ;; --- array ops ----------------------------------------------------------
   'aget       (fn-of '(Any Long) 'Any)
   'aset       (fn-of '(Any Long Any) 'Any)
   'alength    (fn-of '(Any) 'Long)
   'aclone     (fn-of '(Any) 'Any)
   'to-array   (fn-of '(Any) 'Any)
   'into-array (fn-of '(Any) 'Any #:rest 'Any)
   'make-array (fn-of '(Any Long) 'Any)
   ;; --- Java interop: more instance methods --------------------------------
   '.getMessage  (fn-of '(Any) 'String)
   '.getCause    (fn-of '(Any) 'Any)
   '.getClass    (fn-of '(Any) 'Any)
   '.hashCode    (fn-of '(Any) 'Long)
   '.equals      (fn-of '(Any Any) 'Boolean)
   '.compareTo   (fn-of '(Any Any) 'Long)
   '.indexOf     (fn-of '(String String) 'Long)
   '.lastIndexOf (fn-of '(String String) 'Long)
   '.charAt      (fn-of '(String Long) 'Any)
   '.substring   (fn-of '(String Long) 'String #:rest 'Long)
   '.replace     (fn-of '(String Any Any) 'String)
   '.replaceAll  (fn-of '(String String String) 'String)
   '.replaceFirst (fn-of '(String String String) 'String)
   '.matches     (fn-of '(String String) 'Boolean)
   '.split       (fn-of '(String String) 'Any)
   '.isEmpty     (fn-of '(Any) 'Boolean)
   '.toCharArray (fn-of '(String) 'Any)
   '.getBytes    (fn-of '(String) 'Any #:rest 'Any)
   '.intern      (fn-of '(String) 'String)
   '.format      (fn-of '(Any String) 'String #:rest 'Any)
   '.size        (fn-of '(Any) 'Long)
   '.get         (fn-of '(Any Any) 'Any)
   '.put         (fn-of '(Any Any Any) 'Any)
   '.add         (fn-of '(Any Any) 'Boolean)
   '.remove      (fn-of '(Any Any) 'Any)
   '.clear       (fn-of '(Any) 'Nil)
   '.containsKey (fn-of '(Any Any) 'Boolean)
   '.containsValue (fn-of '(Any Any) 'Boolean)
   '.keySet      (fn-of '(Any) 'Any)
   '.values      (fn-of '(Any) 'Any)
   '.entrySet    (fn-of '(Any) 'Any)
   '.iterator    (fn-of '(Any) 'Any)
   '.hasNext     (fn-of '(Any) 'Boolean)
   '.next        (fn-of '(Any) 'Any)
   ;; --- Java interop: more static methods ----------------------------------
   'Boolean/parseBoolean (fn-of '(String) 'Boolean)
   'Boolean/valueOf      (fn-of '(Any) 'Boolean)
   'Integer/valueOf      (fn-of '(Any) 'Long)
   'Long/valueOf         (fn-of '(Any) 'Long)
   'Double/valueOf       (fn-of '(Any) 'Double)
   'Float/parseFloat     (fn-of '(String) 'Double)
   'String/valueOf       (fn-of '(Any) 'String)
   'String/format        (fn-of '(String) 'String #:rest 'Any)
   'Math/PI              (p 'Double)
   'Math/E               (p 'Double)
   'Math/sin             (fn-of '(Double) 'Double)
   'Math/cos             (fn-of '(Double) 'Double)
   'Math/tan             (fn-of '(Double) 'Double)
   'Math/asin            (fn-of '(Double) 'Double)
   'Math/acos            (fn-of '(Double) 'Double)
   'Math/atan            (fn-of '(Double) 'Double)
   'Math/atan2           (fn-of '(Double Double) 'Double)
   'Math/log             (fn-of '(Double) 'Double)
   'Math/log10           (fn-of '(Double) 'Double)
   'Math/exp             (fn-of '(Double) 'Double)
   'Math/random          (fn-of '() 'Double)
   'Math/signum          (fn-of '(Double) 'Double)
   'Math/toRadians       (fn-of '(Double) 'Double)
   'Math/toDegrees       (fn-of '(Double) 'Double)
   'Math/cbrt            (fn-of '(Double) 'Double)
   'Math/hypot           (fn-of '(Double Double) 'Double)
   'Math/IEEEremainder   (fn-of '(Double Double) 'Double)
   'Math/floorMod        (fn-of '(Long Long) 'Long)
   'Math/floorDiv        (fn-of '(Long Long) 'Long)
   'Math/addExact        (fn-of '(Long Long) 'Long)
   'Math/subtractExact   (fn-of '(Long Long) 'Long)
   'Math/multiplyExact   (fn-of '(Long Long) 'Long)
   'Math/incrementExact  (fn-of '(Long) 'Long)
   'Math/decrementExact  (fn-of '(Long) 'Long)
   'Math/negateExact     (fn-of '(Long) 'Long)
   'Math/toIntExact      (fn-of '(Long) 'Long)
   'Collections/unmodifiableList (fn-of '(Any) 'Any)
   'Collections/unmodifiableMap  (fn-of '(Any) 'Any)
   'Collections/sort     (fn-of '(Any) 'Nil #:rest 'Any)
   'Arrays/asList        (fn-of '(Any) 'Any)
   'Arrays/sort          (fn-of '(Any) 'Nil #:rest 'Any)
   'Objects/requireNonNull (fn-of '(Any) 'Any #:rest 'Any)
   'Thread/sleep         (fn-of '(Long) 'Nil)
   'Instant/now          (fn-of '() 'Any)
   'Instant/parse        (fn-of '(Any) 'Any)
   'UUID/randomUUID      (fn-of '() 'Any)
   'UUID/fromString      (fn-of '(String) 'Any)

   ;; --- Java interop: instance methods (receiver is first param) ----------
   '.exists        (fn-of '(Any) 'Boolean)
   '.toString      (fn-of '(Any) 'String)
   '.length        (fn-of '(String) 'Long)
   '.trim          (fn-of '(String) 'String)
   '.startsWith    (fn-of '(String String) 'Boolean)
   '.endsWith      (fn-of '(String String) 'Boolean)
   '.contains      (fn-of '(String String) 'Boolean)
   '.toLowerCase   (fn-of '(String) 'String)
   '.toUpperCase   (fn-of '(String) 'String)
   '.getPath       (fn-of '(Any) 'String)
   '.getName       (fn-of '(Any) 'String)
   '.getParent     (fn-of '(Any) 'String)
   '.getParentFile (fn-of '(Any) 'Any)
   '.mkdirs        (fn-of '(Any) 'Boolean)
   '.mkdir         (fn-of '(Any) 'Boolean)
   '.isDirectory   (fn-of '(Any) 'Boolean)
   '.isFile        (fn-of '(Any) 'Boolean)
   '.delete        (fn-of '(Any) 'Boolean)
   '.canRead       (fn-of '(Any) 'Boolean)
   '.canWrite      (fn-of '(Any) 'Boolean)
   '.lastModified  (fn-of '(Any) 'Long)
   '.toPath        (fn-of '(Any) 'Any)
   '.close         (fn-of '(Any) 'Nil)

   ;; --- Java interop: static methods --------------------------------------
   'System/getProperty       (fn-of '(String) 'String)
   'System/getenv            (fn-of '(String) 'Any)
   'System/currentTimeMillis (fn-of '() 'Long)
   'System/exit              (fn-of '(Long) 'Nil)
   'Math/abs      (fn-of '(Long) 'Long)
   'Math/max      (fn-of '(Long Long) 'Long)
   'Math/min      (fn-of '(Long Long) 'Long)
   'Math/round    (fn-of '(Double) 'Long)
   'Math/floor    (fn-of '(Double) 'Double)
   'Math/ceil     (fn-of '(Double) 'Double)
   'Math/pow      (fn-of '(Double Double) 'Double)
   'Math/sqrt     (fn-of '(Double) 'Double)
   'Integer/parseInt   (fn-of '(String) 'Long)
   'Long/parseLong     (fn-of '(String) 'Long)
   'Double/parseDouble (fn-of '(String) 'Double)

   ;; --- Java interop: dynamic vars ----------------------------------------
   '*command-line-args* (type-app 'Vec (list (p 'String)))

   ;; =========================================================================
   ;; AUTO-GENERATED from clojure.core metadata (172 entries)
   ;; Arity-correct, types conservative (Any → Any) except where obvious
   ;; (predicates → Boolean, bit-ops → Long). Hand-tune above as needed.
   ;; Generated by bin/gen-stdlib-types.
   ;; =========================================================================
   '==             (fn-of '(Any Any) 'Any #:rest 'Any)
   'add-tap        (fn-of '(Any) 'Any)
   'all-ns         (fn-of '() 'Any)
   'ancestors      (fn-of '(Any) 'Any #:rest 'Any)
   'any?           (fn-of '(Any) 'Boolean)
   'array-map      (fn-of '() 'Any #:rest 'Any)
   'aset-boolean   (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'aset-byte      (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'aset-char      (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'aset-double    (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'aset-float     (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'aset-int       (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'aset-long      (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'aset-short     (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'assoc!         (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'bean           (fn-of '(Any) 'Any)
   'binding-conveyor-fn (fn-of '(Any) 'Any)
   'bit-and        (fn-of '(Long Long) 'Long #:rest 'Long)
   'bit-and-not    (fn-of '(Long Long) 'Long #:rest 'Long)
   'bit-clear      (fn-of '(Long Long) 'Long)
   'bit-flip       (fn-of '(Long Long) 'Long)
   'bit-not        (fn-of '(Long) 'Long)
   'bit-or         (fn-of '(Long Long) 'Long #:rest 'Long)
   'bit-set        (fn-of '(Long Long) 'Long)
   'bit-shift-left (fn-of '(Long Long) 'Long)
   'bit-shift-right (fn-of '(Long Long) 'Long)
   'bit-test       (fn-of '(Long Long) 'Boolean)
   'bit-xor        (fn-of '(Long Long) 'Long #:rest 'Long)
   'boolean-array  (fn-of '(Any) 'Any #:rest 'Any)
   'boolean?       (fn-of '(Any) 'Boolean)
   'booleans       (fn-of '(Any) 'Any)
   'byte-array     (fn-of '(Any) 'Any #:rest 'Any)
   'bytes          (fn-of '(Any) 'Any)
   'char-array     (fn-of '(Any) 'Any #:rest 'Any)
   'chars          (fn-of '(Any) 'Any)
   'chunk          (fn-of '(Any) 'Any)
   'chunk-append   (fn-of '(Any Any) 'Any)
   'chunk-buffer   (fn-of '(Any) 'Any)
   'chunk-cons     (fn-of '(Any Any) 'Any)
   'chunk-first    (fn-of '(Any) 'Any)
   'chunk-next     (fn-of '(Any) 'Any)
   'chunk-rest     (fn-of '(Any) 'Any)
   'chunked-seq?   (fn-of '(Any) 'Boolean)
   'clojure-version (fn-of '() 'String)
   'comparator     (fn-of '(Any) 'Any)
   'conj!          (fn-of '() 'Any #:rest 'Any)
   'delay?         (fn-of '(Any) 'Boolean)
   'denominator    (fn-of '(Any) 'Long)
   'derive         (fn-of '(Any Any) 'Any #:rest 'Any)
   'descendants    (fn-of '(Any) 'Any #:rest 'Any)
   'destructure    (fn-of '(Any) 'Any #:rest 'Any)
   'disj           (fn-of '(Any Any) 'Any #:rest 'Any)
   'disj!          (fn-of '(Any Any) 'Any #:rest 'Any)
   'dissoc!        (fn-of '(Any Any) 'Any #:rest 'Any)
   'distinct?      (fn-of '(Any Any) 'Boolean #:rest 'Any)
   'doall          (fn-of '(Any) 'Any #:rest 'Any)
   'dorun          (fn-of '(Any) 'Any #:rest 'Any)
   'double-array   (fn-of '(Any) 'Any #:rest 'Any)
   'doubles        (fn-of '(Any) 'Any)
   'empty          (fn-of '(Any) 'Any)
   'ensure-reduced (fn-of '(Any) 'Any)
   'enumeration-seq (fn-of '(Any) 'Any)
   'every-pred     (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'ex-cause       (fn-of '(Any) 'Any)
   'extend         (fn-of '(Any) 'Any #:rest 'Any)
   'file-seq       (fn-of '(Any) 'Any)
   'find-var       (fn-of '(Any) 'Any)
   'float-array    (fn-of '(Any) 'Any #:rest 'Any)
   'floats         (fn-of '(Any) 'Any)
   'flush          (fn-of '() 'Nil)
   'future-call    (fn-of '(Any) 'Any)
   'future-cancel  (fn-of '(Any) 'Any)
   'future-cancelled? (fn-of '(Any) 'Boolean)
   'future-done?   (fn-of '(Any) 'Boolean)
   'future?        (fn-of '(Any) 'Boolean)
   'get-method     (fn-of '(Any Any) 'Any)
   'hash-combine   (fn-of '(Long Any) 'Long)
   'hash-ordered-coll (fn-of '(Any) 'Long)
   'hash-unordered-coll (fn-of '(Any) 'Long)
   'infinite?      (fn-of '(Any) 'Boolean)
   'int-array      (fn-of '(Any) 'Any #:rest 'Any)
   'ints           (fn-of '(Any) 'Any)
   'isa?           (fn-of '(Any Any) 'Boolean #:rest 'Any)
   'iteration      (fn-of '(Any) 'Any #:rest 'Any)
   'iterator-seq   (fn-of '(Any) 'Any)
   'line-seq       (fn-of '(Any) 'Any)
   'list*          (fn-of '(Any Any Any Any) 'Any #:rest 'Any)
   'long-array     (fn-of '(Any) 'Any #:rest 'Any)
   'longs          (fn-of '(Any) 'Any)
   'make-hierarchy (fn-of '() 'Any)
   'map-entry?     (fn-of '(Any) 'Boolean)
   'methods        (fn-of '(Any) 'Any)
   'munge          (fn-of '(Any) 'Any)
   'namespace-munge (fn-of '(Any) 'Any)
   'numerator      (fn-of '(Any) 'Long)
   'object-array   (fn-of '(Any) 'Any)
   'parents        (fn-of '(Any) 'Any #:rest 'Any)
   'partitionv     (fn-of '(Any Any) 'Any #:rest 'Any)
   'partitionv-all (fn-of '(Any) 'Any #:rest 'Any)
   'persistent!    (fn-of '(Any) 'Any)
   'pop!           (fn-of '(Any) 'Any)
   'prefer-method  (fn-of '(Any Any Any) 'Any)
   'prefers        (fn-of '(Any) 'Any)
   'print-simple   (fn-of '(Any Any) 'Any)
   'prn-str        (fn-of '() 'String #:rest 'Any)
   'random-sample  (fn-of '(Any) 'Any #:rest 'Any)
   're-matcher     (fn-of '(Any Any) 'Any)
   'read-line      (fn-of '() 'String)
   'reader-conditional (fn-of '(Any Any) 'Any)
   'reader-conditional? (fn-of '(Any) 'Boolean)
   'reduce-kv      (fn-of '(Any Any Any) 'Any)
   'reduced        (fn-of '(Any) 'Any)
   'reduced?       (fn-of '(Any) 'Boolean)
   'remove-all-methods (fn-of '(Any) 'Any)
   'remove-method  (fn-of '(Any Any) 'Any)
   'remove-tap     (fn-of '(Any) 'Any)
   'replicate      (fn-of '(Any Any) 'Any)
   'requiring-resolve (fn-of '(Any) 'Any)
   'reset-meta!    (fn-of '(Any Any) 'Any)
   'reset-vals!    (fn-of '(Any Any) 'Any)
   'rseq           (fn-of '(Any) 'Any)
   'rsubseq        (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'seq-to-map-for-destructuring (fn-of '(Any) 'Any)
   'seq?           (fn-of '(Any) 'Boolean)
   'short-array    (fn-of '(Any) 'Any #:rest 'Any)
   'shorts         (fn-of '(Any) 'Any)
   'some-fn        (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'sorted-map-by  (fn-of '(Any) 'Any #:rest 'Any)
   'sorted-set     (fn-of '() 'Any #:rest 'Any)
   'sorted-set-by  (fn-of '(Any) 'Any #:rest 'Any)
   'splitv-at      (fn-of '(Any Any) 'Any)
   'stream-into!   (fn-of '(Any Any) 'Any #:rest 'Any)
   'stream-reduce! (fn-of '(Any Any) 'Any #:rest 'Any)
   'stream-seq!    (fn-of '(Any) 'Any)
   'stream-transduce! (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'subseq         (fn-of '(Any Any Any) 'Any #:rest 'Any)
   'swap-vals!     (fn-of '(Any Any Any Any) 'Any #:rest 'Any)
   'take-nth       (fn-of '(Any) 'Any #:rest 'Any)
   'tap>           (fn-of '(Any) 'Boolean)
   'test           (fn-of '(Any) 'Any)
   'to-array-2d    (fn-of '(Any) 'Any)
   'transient      (fn-of '(Any) 'Any)
   'tree-seq       (fn-of '(Any Any Any) 'Any)
   'unchecked-add  (fn-of '(Any Any) 'Any)
   'unchecked-add-int (fn-of '(Any Any) 'Any)
   'unchecked-byte (fn-of '(Any) 'Any)
   'unchecked-char (fn-of '(Any) 'Any)
   'unchecked-dec  (fn-of '(Any) 'Any)
   'unchecked-dec-int (fn-of '(Any) 'Any)
   'unchecked-divide-int (fn-of '(Any Any) 'Any)
   'unchecked-double (fn-of '(Any) 'Any)
   'unchecked-float (fn-of '(Any) 'Any)
   'unchecked-inc  (fn-of '(Any) 'Any)
   'unchecked-inc-int (fn-of '(Any) 'Any)
   'unchecked-int  (fn-of '(Any) 'Any)
   'unchecked-long (fn-of '(Any) 'Any)
   'unchecked-multiply (fn-of '(Any Any) 'Any)
   'unchecked-multiply-int (fn-of '(Any Any) 'Any)
   'unchecked-negate (fn-of '(Any) 'Any)
   'unchecked-negate-int (fn-of '(Any) 'Any)
   'unchecked-remainder-int (fn-of '(Any Any) 'Any)
   'unchecked-short (fn-of '(Any) 'Any)
   'unchecked-subtract (fn-of '(Any Any) 'Any)
   'unchecked-subtract-int (fn-of '(Any Any) 'Any)
   'underive       (fn-of '(Any Any) 'Any #:rest 'Any)
   'unreduced      (fn-of '(Any) 'Any)
   'unsigned-bit-shift-right (fn-of '(Long Long) 'Long)
   'update-keys    (fn-of '(Any Any) 'Any)
   'update-vals    (fn-of '(Any Any) 'Any)
   'var?           (fn-of '(Any) 'Boolean)
   'volatile?      (fn-of '(Any) 'Boolean)
   'xml-seq        (fn-of '(Any) 'Any)

   ;; JS interop (ClojureScript)
   'js/parseInt       (fn-of '(Any) 'Long #:rest 'Any)
   'js/parseFloat     (fn-of '(String) 'Double)
   'js/isNaN          (fn-of '(Any) 'Boolean)
   'js/isFinite       (fn-of '(Any) 'Boolean)
   'js/encodeURI      (fn-of '(String) 'String)
   'js/decodeURI      (fn-of '(String) 'String)
   'js/encodeURIComponent (fn-of '(String) 'String)
   'js/decodeURIComponent (fn-of '(String) 'String)
   'js/Math.abs       (fn-of '(Any) 'Any)
   'js/Math.floor     (fn-of '(Double) 'Double)
   'js/Math.ceil      (fn-of '(Double) 'Double)
   'js/Math.round     (fn-of '(Double) 'Long)
   'js/Math.max       (fn-of '(Any Any) 'Any #:rest 'Any)
   'js/Math.min       (fn-of '(Any Any) 'Any #:rest 'Any)
   'js/Math.pow       (fn-of '(Double Double) 'Double)
   'js/Math.sqrt      (fn-of '(Double) 'Double)
   'js/Math.random    (fn-of '() 'Double)
   'js/Math.log       (fn-of '(Double) 'Double)
   'js/Math.sin       (fn-of '(Double) 'Double)
   'js/Math.cos       (fn-of '(Double) 'Double)
   'js/console.log    (fn-of '() 'Nil #:rest 'Any)
   'js/console.warn   (fn-of '() 'Nil #:rest 'Any)
   'js/console.error  (fn-of '() 'Nil #:rest 'Any)
   'js/undefined      (p 'Nil)
   'js/NaN            (p 'Double)
   'js/Infinity       (p 'Double)
   ))

(define CLJS-EXCLUDE
  (set
   ;; Java instance methods
   '.getMessage '.getCause '.getClass '.hashCode '.equals '.compareTo
   '.indexOf '.lastIndexOf '.charAt '.substring '.replace '.replaceAll
   '.replaceFirst '.matches '.split '.isEmpty '.toCharArray '.getBytes
   '.intern '.format '.size '.get '.put '.add '.remove '.clear
   '.containsKey '.containsValue '.keySet '.values '.entrySet
   '.iterator '.hasNext '.next
   '.exists '.toString '.length '.trim '.startsWith '.endsWith
   '.contains '.toLowerCase '.toUpperCase
   '.getPath '.getName '.getParent '.getParentFile '.mkdirs '.mkdir
   '.isDirectory '.isFile '.delete '.canRead '.canWrite '.lastModified
   '.toPath '.close
   ;; Java static methods
   'System/getProperty 'System/getenv 'System/exit 'System/currentTimeMillis
   'System/nanoTime
   'Math/abs 'Math/floor 'Math/ceil 'Math/round 'Math/max 'Math/min
   'Math/pow 'Math/sqrt 'Math/random 'Math/log 'Math/sin 'Math/cos
   'Math/tan 'Math/PI 'Math/E
   'Integer/parseInt 'Integer/valueOf 'Integer/MAX_VALUE 'Integer/MIN_VALUE
   'Long/parseLong 'Long/valueOf 'Long/MAX_VALUE 'Long/MIN_VALUE
   'Double/parseDouble 'Double/valueOf 'Double/NaN 'Double/POSITIVE_INFINITY
   'Double/NEGATIVE_INFINITY 'Double/isNaN 'Double/isInfinite
   'Float/parseFloat 'Float/valueOf
   'Boolean/parseBoolean 'Boolean/valueOf
   'String/format 'String/valueOf 'String/join
   'Character/isDigit 'Character/isLetter 'Character/isWhitespace
   'Class/forName
   'Thread/sleep 'Thread/currentThread
   'Runtime/getRuntime
   'UUID/randomUUID 'UUID/fromString
   ;; JVM dynamic vars
   '*command-line-args*
   ;; JVM-only core functions
   'slurp 'spit 'bean 'class 'supers 'bases 'ancestors 'parents
   'future 'future-call 'future-cancel 'future-cancelled? 'future-done? 'future?
   'promise 'deliver 'realized?
   'agent 'send 'send-off 'await 'shutdown-agents))

(provide STDLIB-TYPES CLJS-EXCLUDE)
