// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub fn square(x: i64) i64 {
    return (x * x);
}

pub fn sumSquares(a: i64, b: i64) i64 {
    return (square(a) + square(b));
}
