// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub fn rollPair(ctx: *rt.Ctx) i64 {
    return (rt.rng_below(ctx, 6) + rt.rng_below(ctx, 6));
}
