// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub fn lookup(m: rt.Map(i64), k: []const u8) ?i64 {
    return m.get(k);
}

pub fn has(m: rt.Map(i64), k: []const u8) bool {
    return m.contains(k);
}

pub fn size(m: rt.Map(i64)) i64 {
    return rt.count(m);
}

pub fn put(m: rt.Map(i64), k: []const u8, v: i64) rt.Map(i64) {
    return m.assoc(k, v);
}
