// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub fn norm(s: []const u8) []const u8 {
    return rt.trim(rt.lower_case(s));
}

pub fn flags(s: []const u8) bool {
    return (rt.starts_with(s, "x") and rt.ends_with(s, "z") and rt.includes(s, "y") and (!rt.blank(s)));
}

pub fn head3(s: []const u8) []const u8 {
    return rt.subs3(s, 0, 3);
}

pub fn tail(s: []const u8) []const u8 {
    return rt.subs(s, 1);
}

pub fn glue(parts: []const []const u8) []const u8 {
    return rt.join(",", parts);
}

pub fn fix(s: []const u8) []const u8 {
    return rt.replace(s, "a", "b");
}

pub fn lines(s: []const u8) []const []const u8 {
    return rt.split_lines(s);
}

pub fn dir(p: []const u8) []const u8 {
    return rt.parent(p);
}

pub fn under(a: []const u8, b: []const u8) []const u8 {
    return rt.path(a, b);
}

pub fn readIt(p: []const u8) []const u8 {
    return rt.slurp(p);
}

pub fn writeIt(p: []const u8, s: []const u8) void {
    _ = rt.spit(p, s);
}
