/* Generated by native.qbe-validation-corpus; do not edit. */
#include "native_shim.h"

#include <stdio.h>

int64_t native_m0_fn_0(native_arena *arena, const native_capability *capability,
                       int64_t left, int64_t right);
int64_t native_m1_fn_3(int64_t left, int64_t right, int64_t distance);
native_vec *native_m2_fn_0(native_arena *arena, const native_capability *capability,
                           const native_vec *left, const native_vec *right);
native_vec *native_m2_fn_1(native_arena *arena, const native_capability *capability,
                           const native_vec *source);
native_vec *native_m2_fn_2(native_arena *arena, const native_capability *capability,
                           const native_vec *source, int64_t start, int64_t end);

int64_t native_m3_fn_0(int64_t left, int64_t right);
int64_t native_m3_fn_1(int64_t left, int64_t right);
int64_t native_m3_fn_2(int64_t left, int64_t right);
int64_t native_m3_fn_3(int64_t left, int64_t right);
int64_t native_m3_fn_4(int64_t left, int64_t right);

static void report_scalar_trap(uint32_t code) {
  fprintf(stdout, "qbe-scalar-trap %u\n", code);
  fflush(stdout);
}

int main(int argc, char **argv) {
  if (argc == 2) {
    native_set_trap_reporter(report_scalar_trap);
    if (strcmp(argv[1], "sub-overflow") == 0) {
      (void)native_m3_fn_0(INT64_MIN, INT64_C(1));
    } else if (strcmp(argv[1], "sub-overflow-positive") == 0) {
      (void)native_m3_fn_0(INT64_MAX, -INT64_C(1));
    } else if (strcmp(argv[1], "mul-overflow") == 0) {
      (void)native_m3_fn_1(INT64_MAX, INT64_C(2));
    } else if (strcmp(argv[1], "mul-overflow-negative") == 0) {
      (void)native_m3_fn_1(INT64_MIN, -INT64_C(1));
    } else if (strcmp(argv[1], "mul-overflow-positive-negative") == 0) {
      (void)native_m3_fn_1(INT64_C(3037000500), -INT64_C(3037000500));
    } else if (strcmp(argv[1], "mul-overflow-negative-negative") == 0) {
      (void)native_m3_fn_1(-INT64_C(3037000500), -INT64_C(3037000500));
    } else if (strcmp(argv[1], "quot-zero") == 0) {
      (void)native_m3_fn_2(INT64_C(1), INT64_C(0));
    } else if (strcmp(argv[1], "rem-zero") == 0) {
      (void)native_m3_fn_3(INT64_C(1), INT64_C(0));
    } else {
      (void)native_m3_fn_4(INT64_C(1), INT64_C(0));
    }
    fprintf(stderr, "qbe-scalar-trap MISSED %s\n", argv[1]);
    return 99;
  }
  uint8_t storage[256];
  native_arena arena;
  native_capability capability = { UINT64_C(1) };
  native_arena_init(&arena, storage, sizeof(storage));
  if (native_m0_fn_0(&arena, &capability, INT64_C(20), INT64_C(22)) != INT64_C(42)) {
    return 1;
  }
  int64_t *slot = native_arena_alloc(&arena, sizeof(*slot), _Alignof(int64_t));
  *slot = native_m0_fn_0(&arena, &capability, INT64_C(-1), INT64_C(1));
  if (*slot != INT64_C(0)) {
    return 2;
  }
  if (native_m1_fn_3(INT64_C(240), INT64_C(90), INT64_C(1)) != INT64_C(432)) {
    return 6;
  }
  native_arena_reset(&arena);
  int64_t left_items[] = { INT64_C(3), INT64_C(5) };
  int64_t right_items[] = { INT64_C(8), INT64_C(13), INT64_C(21) };
  const int64_t expected[] = { INT64_C(3), INT64_C(5), INT64_C(8),
                               INT64_C(13), INT64_C(21) };
  native_vec left = { left_items, INT64_C(2), INT64_C(2), NULL };
  native_vec right = { right_items, INT64_C(3), INT64_C(3), NULL };
  native_vec *joined = native_m2_fn_0(&arena, &capability, &left, &right);
  if ((joined == &left) || (joined == &right) ||
      (joined->length != INT64_C(5)) || (joined->capacity != INT64_C(5))) {
    return 3;
  }
  if (memcmp(joined->elements, expected, sizeof(expected)) != 0) {
    return 4;
  }
  if ((left.length != INT64_C(2)) || (right.length != INT64_C(3))) {
    return 5;
  }
  native_vec *reversed = native_m2_fn_1(&arena, &capability, joined);
  native_vec *middle = native_m2_fn_2(&arena, &capability, joined, INT64_C(1), INT64_C(4));
  const int64_t reverse_expected[] = { INT64_C(21), INT64_C(13), INT64_C(8),
                                       INT64_C(5), INT64_C(3) };
  const int64_t middle_expected[] = { INT64_C(5), INT64_C(8), INT64_C(13) };
  if ((reversed->length != INT64_C(5)) || (middle->length != INT64_C(3))
      || (memcmp(reversed->elements, reverse_expected, sizeof(reverse_expected)) != 0)
      || (memcmp(middle->elements, middle_expected, sizeof(middle_expected)) != 0)) {
    return 7;
  }
  if (native_m3_fn_0(INT64_MIN, INT64_C(0)) != INT64_MIN
      || native_m3_fn_0(INT64_MAX, INT64_C(0)) != INT64_MAX
      || native_m3_fn_0(INT64_MIN, -INT64_C(1)) != (INT64_MIN + INT64_C(1))
      || native_m3_fn_0(INT64_MAX, INT64_C(1)) != (INT64_MAX - INT64_C(1))
      || native_m3_fn_1(INT64_MIN, INT64_C(1)) != INT64_MIN
      || native_m3_fn_1(INT64_MAX, INT64_C(1)) != INT64_MAX
      || native_m3_fn_1(INT64_MIN, INT64_C(0)) != INT64_C(0)
      || native_m3_fn_1(INT64_C(3037000499), INT64_C(3037000499))
           != INT64_C(9223372030926249001)
      || native_m3_fn_1(INT64_C(3037000499), -INT64_C(3037000499))
           != -INT64_C(9223372030926249001)
      || native_m3_fn_1(-INT64_C(3037000499), INT64_C(3037000499))
           != -INT64_C(9223372030926249001)
      || native_m3_fn_1(-INT64_C(3037000499), -INT64_C(3037000499))
           != INT64_C(9223372030926249001)) {
    return 8;
  }
  if (native_m3_fn_2(-INT64_C(7), INT64_C(3)) != -INT64_C(2)
      || native_m3_fn_2(INT64_C(7), -INT64_C(3)) != -INT64_C(2)
      || native_m3_fn_2(-INT64_C(7), -INT64_C(3)) != INT64_C(2)
      || native_m3_fn_3(-INT64_C(7), INT64_C(3)) != -INT64_C(1)
      || native_m3_fn_3(INT64_C(7), -INT64_C(3)) != INT64_C(1)
      || native_m3_fn_3(-INT64_C(7), -INT64_C(3)) != -INT64_C(1)
      || native_m3_fn_4(-INT64_C(7), INT64_C(3)) != INT64_C(2)
      || native_m3_fn_4(INT64_C(7), -INT64_C(3)) != -INT64_C(2)
      || native_m3_fn_4(-INT64_C(7), -INT64_C(3)) != -INT64_C(1)) {
    return 9;
  }
  if (native_m3_fn_2(INT64_MIN, -INT64_C(1)) != INT64_MIN
      || native_m3_fn_3(INT64_MIN, -INT64_C(1)) != INT64_C(0)
      || native_m3_fn_4(INT64_MIN, -INT64_C(1)) != INT64_C(0)) {
    return 10;
  }
  native_arena_reset(&arena);
  return 0;
}
