/* Generated by native.qbe-validation-corpus; do not edit. */
#include "native_shim.h"

int64_t native_m0_fn_0(native_arena *arena, const native_capability *capability,
                       int64_t left, int64_t right);

int main(void) {
  uint8_t storage[64];
  native_arena arena;
  native_capability capability = { UINT64_C(1) };
  native_arena_init(&arena, storage, sizeof(storage));
  if (native_m0_fn_0(&arena, &capability, INT64_C(20), INT64_C(22)) != INT64_C(42)) {
    return 1;
  }
  int64_t *slot = native_arena_alloc(&arena, sizeof(*slot), _Alignof(int64_t));
  *slot = native_m0_fn_0(&arena, &capability, INT64_C(-1), INT64_C(1));
  if (*slot != INT64_C(0)) {
    return 2;
  }
  native_arena_reset(&arena);
  return 0;
}
