// generated by beagle (odin backend) — do not edit
package main

import "core:fmt"
import rt "beagle_rt"

Point :: struct {
    x: i64,
    y: i64,
}

get_x :: proc(p: Point) -> i64 {
    return p.x;
}
