// generated by beagle (odin backend) — do not edit
package g


add :: proc(a: int, b: int) -> int {
    return (a + b);
}

sub :: proc(a: int, b: int) -> int {
    return (a - b);
}

mul :: proc(a: int, b: int) -> int {
    return (a * b);
}

negate :: proc(n: int) -> int {
    return (-n);
}
