// generated by beagle (odin backend) — do not edit
package g

import "core:fmt"

sum_range :: proc(n: i64) -> i64 {
    acc := 0;
    i := 0;
    for {
        if (i == n) {
            return acc;
        } else {
            _r0 := (acc + i);
            _r1 := (i + 1);
            acc = _r0;
            i = _r1;
            continue;
        }
    }
}

print_range :: proc(n: i64) {
    for i in 0..<n { fmt.println(i); }
}
