// generated by beagle (odin backend) — do not edit
package i


color_name :: proc(c: i64) -> string {
    return ("red" if (c == .Red) else "green" if (c == .Green) else "blue" if (c == .Blue) else "unknown");
}
