// generated by beagle (odin backend) — do not edit
package j


Vec3 :: struct {
    x: f32,
    y: f32,
    z: f32,
}

scale :: proc(v: ^Vec3, s: f32) {
    v^.x = (v^.x * s);
    v^.y = (v^.y * s);
    v^.z = (v^.z * s);
}
