// generated by beagle (odin backend) — do not edit
package g


hash32 :: proc(x: int, y: int) -> int {
    h := ((x * 374761393) ~ (y * 668265263));
    h2 := (h ~ (h >> 13));
    h3 := (h2 * 1103515245);
    return ((h3 ~ (h3 >> 16)) & 2147483647);
}
