// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub const MindIn = struct {
    x: i64,
    z: i64,
    belief: i64,
    alarm: i64,
};

pub const Obs = struct {
    well_threat: i64,
    social: i64,
    well_dx: i64,
    well_dz: i64,
    wolf_near: i64,
    wolf_dx: i64,
    wolf_dz: i64,
    wolf_here: i64,
};

pub const BeliefOut = struct {
    belief: i64,
    alarm: i64,
};

pub const Decision = struct {
    act: i64,
    dx: i64,
    dz: i64,
};

pub const ACT_IDLE: i64 = 0;

pub const ACT_WANDER: i64 = 1;

pub const ACT_AVOID: i64 = 2;

pub const ACT_FLEE: i64 = 3;

pub const ACT_DIG: i64 = 4;

pub const ALARM_MAX: i64 = 1000;

pub const RISE_THRESHOLD: i64 = 220;

pub const DECAY: i64 = 9;

pub const WARY_AT: i64 = 250;

pub const ALARMED_AT: i64 = 500;

pub const PANIC_AT: i64 = 750;

pub const DIG_RELIEF: i64 = 320;

pub fn clampAlarm(a: i64) i64 {
    return (if ((a > ALARM_MAX)) ALARM_MAX else if ((a < 0)) 0 else a);
}

pub const WOLF_FEAR_AT: i64 = 250;

pub fn beliefUpdate(ctx: *rt.Ctx, m: MindIn, obs: Obs) BeliefOut {
    _ = ctx;
    const observed = (obs.well_threat + (obs.social >> 2) + obs.wolf_near);
    const belief = (m.belief + ((observed - m.belief) >> 3));
    const rising = (belief > RISE_THRESHOLD);
    const alarm = (if (rising) (m.alarm + (belief >> 4)) else (m.alarm - DECAY));
    return BeliefOut{ .belief = belief, .alarm = clampAlarm(alarm) };
}

pub fn decide(ctx: *rt.Ctx, m: MindIn, b: BeliefOut, obs: Obs) Decision {
    _ = m;
    return (if ((b.alarm >= PANIC_AT)) Decision{ .act = ACT_DIG, .dx = 0, .dz = 0 } else if ((obs.wolf_near >= WOLF_FEAR_AT)) Decision{ .act = ACT_FLEE, .dx = (obs.wolf_dx * 2), .dz = (obs.wolf_dz * 2) } else if ((b.alarm >= ALARMED_AT)) Decision{ .act = ACT_FLEE, .dx = (obs.well_dx * 2), .dz = (obs.well_dz * 2) } else if ((b.alarm >= WARY_AT)) Decision{ .act = ACT_AVOID, .dx = obs.well_dx, .dz = obs.well_dz } else blk1: { const roll = rt.rng_below(ctx, 8); break :blk1 (if ((roll < 3)) blk2: { const dx = (rt.rng_below(ctx, 3) - 1); const dz = (rt.rng_below(ctx, 3) - 1); break :blk2 Decision{ .act = ACT_WANDER, .dx = dx, .dz = dz }; } else Decision{ .act = ACT_IDLE, .dx = 0, .dz = 0 }); });
}

pub fn digRelief(alarm: i64) i64 {
    const a = (alarm - DIG_RELIEF);
    return (if ((a < 0)) 0 else a);
}

pub const StepOut = struct {
    x: i64,
    z: i64,
    belief: i64,
    alarm: i64,
    act: i64,
    alive: bool,
    spawn: bool,
};

pub fn clampCoord(v: i64, maxv: i64) i64 {
    return (if ((v < 0)) 0 else if ((v > (maxv - 1))) (maxv - 1) else v);
}

pub fn tickStep(ctx: *rt.Ctx, m: MindIn, obs: Obs, max_x: i64, max_z: i64) StepOut {
    const b = beliefUpdate(ctx, m, obs);
    const d = decide(ctx, m, b, obs);
    const alarm = (if ((d.act == ACT_DIG)) digRelief(b.alarm) else b.alarm);
    const eaten = ((obs.wolf_here > 0) and (rt.rng_below(ctx, 4) == 0));
    const calm = ((alarm == 0) and (b.belief < 60));
    const born = (calm and (!eaten) and (rt.rng_below(ctx, 64) == 0));
    return StepOut{ .x = clampCoord((m.x + d.dx), max_x), .z = clampCoord((m.z + d.dz), max_z), .belief = b.belief, .alarm = alarm, .act = d.act, .alive = (!eaten), .spawn = born };
}

pub const WolfIn = struct {
    x: i64,
    z: i64,
    energy: i64,
    fed: i64,
};

pub const WolfObs = struct {
    scent: i64,
    prey_dx: i64,
    prey_dz: i64,
    prey_near: i64,
};

pub const WolfOut = struct {
    x: i64,
    z: i64,
    energy: i64,
    fed: i64,
    howl: i64,
    alive: bool,
    spawn: bool,
};

pub const WOLF_DRAIN: i64 = 2;

pub const WOLF_FEED_GAIN: i64 = 180;

pub const WOLF_SATED_AT: i64 = 700;

pub const WOLF_HOWL_AFTER: i64 = 120;

pub fn wolfStep(ctx: *rt.Ctx, w: WolfIn, obs: WolfObs, max_x: i64, max_z: i64) WolfOut {
    const energy = @max(0, (w.energy - WOLF_DRAIN));
    const hungry = (energy < WOLF_SATED_AT);
    const tracking = (hungry and (obs.scent > 0));
    const dx = (if (tracking) obs.prey_dx else (rt.rng_below(ctx, 3) - 1));
    const dz = (if (tracking) obs.prey_dz else (rt.rng_below(ctx, 3) - 1));
    const feeding = (hungry and (obs.prey_near > 0));
    const energy2 = (if (feeding) @min(1000, (energy + WOLF_FEED_GAIN)) else energy);
    const fed = (if (feeding) 0 else (w.fed + 1));
    const howl = (if ((hungry and (fed > WOLF_HOWL_AFTER) and (rt.rng_below(ctx, 32) == 0))) @as(i64, 1) else 0);
    return WolfOut{ .x = clampCoord((w.x + dx), max_x), .z = clampCoord((w.z + dz), max_z), .energy = energy2, .fed = fed, .howl = howl, .alive = (energy2 > 0), .spawn = ((energy2 >= 900) and (rt.rng_below(ctx, 128) == 0)) };
}

/// SoA buffer for MindIn — engine state, one slice per field.
/// Allocated by the harness (any allocator); never freed here —
/// emitted code never frees, the harness owns lifetimes.
pub const MindInSoA = struct {
    x: []i64,
    z: []i64,
    belief: []i64,
    alarm: []i64,

    pub fn alloc(a: std.mem.Allocator, n: usize) !MindInSoA {
        return .{
            .x = try a.alloc(i64, n),
            .z = try a.alloc(i64, n),
            .belief = try a.alloc(i64, n),
            .alarm = try a.alloc(i64, n),
        };
    }

    pub fn get(self: *const MindInSoA, i: usize) MindIn {
        return .{
            .x = self.x[i],
            .z = self.z[i],
            .belief = self.belief[i],
            .alarm = self.alarm[i],
        };
    }

    pub fn set(self: *MindInSoA, i: usize, v: MindIn) void {
        self.x[i] = v.x;
        self.z[i] = v.z;
        self.belief[i] = v.belief;
        self.alarm[i] = v.alarm;
    }

    pub fn copyFrom(self: *MindInSoA, src: *const MindInSoA, n: usize) void {
        @memcpy(self.x[0..n], src.x[0..n]);
        @memcpy(self.z[0..n], src.z[0..n]);
        @memcpy(self.belief[0..n], src.belief[0..n]);
        @memcpy(self.alarm[0..n], src.alarm[0..n]);
    }
};

/// SoA buffer for StepOut — engine state, one slice per field.
/// Allocated by the harness (any allocator); never freed here —
/// emitted code never frees, the harness owns lifetimes.
pub const StepOutSoA = struct {
    x: []i64,
    z: []i64,
    belief: []i64,
    alarm: []i64,
    act: []i64,
    alive: []bool,
    spawn: []bool,

    pub fn alloc(a: std.mem.Allocator, n: usize) !StepOutSoA {
        return .{
            .x = try a.alloc(i64, n),
            .z = try a.alloc(i64, n),
            .belief = try a.alloc(i64, n),
            .alarm = try a.alloc(i64, n),
            .act = try a.alloc(i64, n),
            .alive = try a.alloc(bool, n),
            .spawn = try a.alloc(bool, n),
        };
    }

    pub fn get(self: *const StepOutSoA, i: usize) StepOut {
        return .{
            .x = self.x[i],
            .z = self.z[i],
            .belief = self.belief[i],
            .alarm = self.alarm[i],
            .act = self.act[i],
            .alive = self.alive[i],
            .spawn = self.spawn[i],
        };
    }

    pub fn set(self: *StepOutSoA, i: usize, v: StepOut) void {
        self.x[i] = v.x;
        self.z[i] = v.z;
        self.belief[i] = v.belief;
        self.alarm[i] = v.alarm;
        self.act[i] = v.act;
        self.alive[i] = v.alive;
        self.spawn[i] = v.spawn;
    }

    pub fn copyFrom(self: *StepOutSoA, src: *const StepOutSoA, n: usize) void {
        @memcpy(self.x[0..n], src.x[0..n]);
        @memcpy(self.z[0..n], src.z[0..n]);
        @memcpy(self.belief[0..n], src.belief[0..n]);
        @memcpy(self.alarm[0..n], src.alarm[0..n]);
        @memcpy(self.act[0..n], src.act[0..n]);
        @memcpy(self.alive[0..n], src.alive[0..n]);
        @memcpy(self.spawn[0..n], src.spawn[0..n]);
    }
};

/// SoA buffer for WolfIn — engine state, one slice per field.
/// Allocated by the harness (any allocator); never freed here —
/// emitted code never frees, the harness owns lifetimes.
pub const WolfInSoA = struct {
    x: []i64,
    z: []i64,
    energy: []i64,
    fed: []i64,

    pub fn alloc(a: std.mem.Allocator, n: usize) !WolfInSoA {
        return .{
            .x = try a.alloc(i64, n),
            .z = try a.alloc(i64, n),
            .energy = try a.alloc(i64, n),
            .fed = try a.alloc(i64, n),
        };
    }

    pub fn get(self: *const WolfInSoA, i: usize) WolfIn {
        return .{
            .x = self.x[i],
            .z = self.z[i],
            .energy = self.energy[i],
            .fed = self.fed[i],
        };
    }

    pub fn set(self: *WolfInSoA, i: usize, v: WolfIn) void {
        self.x[i] = v.x;
        self.z[i] = v.z;
        self.energy[i] = v.energy;
        self.fed[i] = v.fed;
    }

    pub fn copyFrom(self: *WolfInSoA, src: *const WolfInSoA, n: usize) void {
        @memcpy(self.x[0..n], src.x[0..n]);
        @memcpy(self.z[0..n], src.z[0..n]);
        @memcpy(self.energy[0..n], src.energy[0..n]);
        @memcpy(self.fed[0..n], src.fed[0..n]);
    }
};

/// SoA buffer for WolfOut — engine state, one slice per field.
/// Allocated by the harness (any allocator); never freed here —
/// emitted code never frees, the harness owns lifetimes.
pub const WolfOutSoA = struct {
    x: []i64,
    z: []i64,
    energy: []i64,
    fed: []i64,
    howl: []i64,
    alive: []bool,
    spawn: []bool,

    pub fn alloc(a: std.mem.Allocator, n: usize) !WolfOutSoA {
        return .{
            .x = try a.alloc(i64, n),
            .z = try a.alloc(i64, n),
            .energy = try a.alloc(i64, n),
            .fed = try a.alloc(i64, n),
            .howl = try a.alloc(i64, n),
            .alive = try a.alloc(bool, n),
            .spawn = try a.alloc(bool, n),
        };
    }

    pub fn get(self: *const WolfOutSoA, i: usize) WolfOut {
        return .{
            .x = self.x[i],
            .z = self.z[i],
            .energy = self.energy[i],
            .fed = self.fed[i],
            .howl = self.howl[i],
            .alive = self.alive[i],
            .spawn = self.spawn[i],
        };
    }

    pub fn set(self: *WolfOutSoA, i: usize, v: WolfOut) void {
        self.x[i] = v.x;
        self.z[i] = v.z;
        self.energy[i] = v.energy;
        self.fed[i] = v.fed;
        self.howl[i] = v.howl;
        self.alive[i] = v.alive;
        self.spawn[i] = v.spawn;
    }

    pub fn copyFrom(self: *WolfOutSoA, src: *const WolfOutSoA, n: usize) void {
        @memcpy(self.x[0..n], src.x[0..n]);
        @memcpy(self.z[0..n], src.z[0..n]);
        @memcpy(self.energy[0..n], src.energy[0..n]);
        @memcpy(self.fed[0..n], src.fed[0..n]);
        @memcpy(self.howl[0..n], src.howl[0..n]);
        @memcpy(self.alive[0..n], src.alive[0..n]);
        @memcpy(self.spawn[0..n], src.spawn[0..n]);
    }
};

/// Engine range loop over entities [lo, hi): gather from SoA, run
/// tickStep under the counter-rng policy — rng seeded per
/// (seed, tick_no, entity index, system lane), order-independent,
/// so disjoint ranges parallelize without losing bit-determinism —
/// and scatter the result. Record params index per entity; scalars
/// broadcast. Lane 0x932B4A9287327F1C derives from the system name.
pub fn tickStepAllRange(tick: std.mem.Allocator, seed: u64, tick_no: u64, in: *const MindInSoA, obs: []const Obs, max_x: i64, max_z: i64, out: *StepOutSoA, lo: usize, hi: usize) void {
    var i = lo;
    while (i < hi) : (i += 1) {
        var crng = rt.Splitmix64.init(rt.mix64(seed ^ rt.mix64(tick_no +% 1) ^ rt.mix64(@as(u64, i) +% 0x932B4A9287327F1C)));
        var ctx = Ctx{ .tick = tick, .rng = &crng };
        out.set(i, tickStep(&ctx, in.get(i), obs[i], max_x, max_z));
    }
}

/// Commit-boundary COMPACTION with births: survivors are copied
/// (name-matched fields, index order preserved); then each living
/// spawner appends one child at the parent's next state, capped by
/// the buffer. The dead stay behind in tick memory. Returns the
/// new live count.
pub fn tickStepCompactAll(out: *const StepOutSoA, next: *MindInSoA, n: usize, cap: usize) usize {
    var w: usize = 0;
    var i: usize = 0;
    while (i < n) : (i += 1) {
        if (!out.alive[i]) continue;
        next.x[w] = out.x[i];
        next.z[w] = out.z[i];
        next.belief[w] = out.belief[i];
        next.alarm[w] = out.alarm[i];
        w += 1;
    }
    i = 0;
    while (i < n) : (i += 1) {
        if (!out.spawn[i] or !out.alive[i] or w >= cap) continue;
        next.x[w] = out.x[i];
        next.z[w] = out.z[i];
        next.belief[w] = out.belief[i];
        next.alarm[w] = out.alarm[i];
        w += 1;
    }
    return w;
}

/// Engine range loop over entities [lo, hi): gather from SoA, run
/// wolfStep under the counter-rng policy — rng seeded per
/// (seed, tick_no, entity index, system lane), order-independent,
/// so disjoint ranges parallelize without losing bit-determinism —
/// and scatter the result. Record params index per entity; scalars
/// broadcast. Lane 0x80B95819A8F7E62B derives from the system name.
pub fn wolfStepAllRange(tick: std.mem.Allocator, seed: u64, tick_no: u64, in: *const WolfInSoA, obs: []const WolfObs, max_x: i64, max_z: i64, out: *WolfOutSoA, lo: usize, hi: usize) void {
    var i = lo;
    while (i < hi) : (i += 1) {
        var crng = rt.Splitmix64.init(rt.mix64(seed ^ rt.mix64(tick_no +% 1) ^ rt.mix64(@as(u64, i) +% 0x80B95819A8F7E62B)));
        var ctx = Ctx{ .tick = tick, .rng = &crng };
        out.set(i, wolfStep(&ctx, in.get(i), obs[i], max_x, max_z));
    }
}

/// Commit-boundary COMPACTION with births: survivors are copied
/// (name-matched fields, index order preserved); then each living
/// spawner appends one child at the parent's next state, capped by
/// the buffer. The dead stay behind in tick memory. Returns the
/// new live count.
pub fn wolfStepCompactAll(out: *const WolfOutSoA, next: *WolfInSoA, n: usize, cap: usize) usize {
    var w: usize = 0;
    var i: usize = 0;
    while (i < n) : (i += 1) {
        if (!out.alive[i]) continue;
        next.x[w] = out.x[i];
        next.z[w] = out.z[i];
        next.energy[w] = out.energy[i];
        next.fed[w] = out.fed[i];
        w += 1;
    }
    i = 0;
    while (i < n) : (i += 1) {
        if (!out.spawn[i] or !out.alive[i] or w >= cap) continue;
        next.x[w] = out.x[i];
        next.z[w] = out.z[i];
        next.energy[w] = out.energy[i];
        next.fed[w] = out.fed[i];
        w += 1;
    }
    return w;
}
