// generated by beagle (zig backend) — do not edit
const std = @import("std");
const rt = @import("beagle_rt.zig");
pub const Ctx = rt.Ctx;

pub const MindIn = struct {
    x: i64,
    z: i64,
    belief: i64,
    alarm: i64,
};

pub const Obs = struct {
    well_threat: i64,
    social: i64,
    well_dx: i64,
    well_dz: i64,
};

pub const BeliefOut = struct {
    belief: i64,
    alarm: i64,
};

pub const Decision = struct {
    act: i64,
    dx: i64,
    dz: i64,
};

pub const ACT_IDLE: i64 = 0;

pub const ACT_WANDER: i64 = 1;

pub const ACT_AVOID: i64 = 2;

pub const ACT_FLEE: i64 = 3;

pub const ACT_DIG: i64 = 4;

pub const ALARM_MAX: i64 = 1000;

pub const RISE_THRESHOLD: i64 = 220;

pub const DECAY: i64 = 9;

pub const WARY_AT: i64 = 250;

pub const ALARMED_AT: i64 = 500;

pub const PANIC_AT: i64 = 750;

pub const DIG_RELIEF: i64 = 320;

pub fn clampAlarm(a: i64) i64 {
    return (if ((a > ALARM_MAX)) ALARM_MAX else if ((a < 0)) 0 else a);
}

pub fn beliefUpdate(ctx: *rt.Ctx, m: MindIn, obs: Obs) BeliefOut {
    _ = ctx;
    const observed = (obs.well_threat + (obs.social >> 2));
    const belief = (m.belief + ((observed - m.belief) >> 3));
    const rising = (belief > RISE_THRESHOLD);
    const alarm = (if (rising) (m.alarm + (belief >> 4)) else (m.alarm - DECAY));
    return BeliefOut{ .belief = belief, .alarm = clampAlarm(alarm) };
}

pub fn decide(ctx: *rt.Ctx, m: MindIn, b: BeliefOut, obs: Obs) Decision {
    _ = m;
    return (if ((b.alarm >= PANIC_AT)) Decision{ .act = ACT_DIG, .dx = 0, .dz = 0 } else if ((b.alarm >= ALARMED_AT)) Decision{ .act = ACT_FLEE, .dx = (obs.well_dx * 2), .dz = (obs.well_dz * 2) } else if ((b.alarm >= WARY_AT)) Decision{ .act = ACT_AVOID, .dx = obs.well_dx, .dz = obs.well_dz } else blk1: { const roll = rt.rng_below(ctx, 8); break :blk1 (if ((roll < 3)) blk2: { const dx = (rt.rng_below(ctx, 3) - 1); const dz = (rt.rng_below(ctx, 3) - 1); break :blk2 Decision{ .act = ACT_WANDER, .dx = dx, .dz = dz }; } else Decision{ .act = ACT_IDLE, .dx = 0, .dz = 0 }); });
}

pub fn digRelief(alarm: i64) i64 {
    const a = (alarm - DIG_RELIEF);
    return (if ((a < 0)) 0 else a);
}

pub const StepOut = struct {
    x: i64,
    z: i64,
    belief: i64,
    alarm: i64,
    act: i64,
};

pub fn clampCoord(v: i64, maxv: i64) i64 {
    return (if ((v < 0)) 0 else if ((v > (maxv - 1))) (maxv - 1) else v);
}

pub fn tickStep(ctx: *rt.Ctx, m: MindIn, obs: Obs, max_x: i64, max_z: i64) StepOut {
    const b = beliefUpdate(ctx, m, obs);
    const d = decide(ctx, m, b, obs);
    const alarm = (if ((d.act == ACT_DIG)) digRelief(b.alarm) else b.alarm);
    return StepOut{ .x = clampCoord((m.x + d.dx), max_x), .z = clampCoord((m.z + d.dz), max_z), .belief = b.belief, .alarm = alarm, .act = d.act };
}

/// Commit-boundary copy: world state leaves tick memory by
/// value (escape-checked slice-free in v1).
pub fn promote(v: StepOut) StepOut {
    return v;
}
