/* Generated by native.body-c17; do not edit. */
#include "module_5.h"

struct native_m5_text_0_blob { uint64_t length; uint8_t bytes[sizeof "  epoch  "]; };
static const struct native_m5_text_0_blob native_m5_text_0 = { (uint64_t)(sizeof "  epoch  " - 1U), "  epoch  " };
_Static_assert(offsetof(struct native_m5_text_0_blob, bytes) == 8, "text blob is length-prefixed");

native_m5_type_1 native_m5_fn_0(native_arena *arena, const native_capability *capability, native_m5_type_3 native_v_0, native_m5_type_1 native_v_1) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  (void)native_v_1;
  native_m5_type_0 native_s_0;
  native_m5_type_3 native_s_1;
  native_m5_type_1 native_s_2;
  native_m5_type_1 native_s_3;
  native_m5_type_2 native_s_4;
  native_m5_type_1 native_s_5;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = native_text_trim((native_arena *)native_s_0, native_v_0);
  native_s_2 = (int64_t)native_text_length(native_s_1);
  native_s_3 = INT64_C(5);
  (void)native_s_3;
  native_s_4 = (native_s_2 == native_s_3);
  if (native_s_4) {
    goto native_l0_1;
  } else {
    goto native_l0_2;
  }
native_l0_1: ;
  return native_v_1;
native_l0_2: ;
  native_s_5 = INT64_C(-1);
  (void)native_s_5;
  return native_s_5;
}
native_m5_type_1 native_m5_fn_1(native_arena *arena, const native_capability *capability, native_m5_type_1 native_v_0) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  native_m5_type_0 native_s_0;
  native_m5_type_3 native_s_1;
  native_m5_type_1 native_s_2;
  native_m5_type_2 native_s_3;
  native_m5_type_1 native_s_4;
  native_s_0 = arena;
  (void)native_s_0;
  native_s_1 = (uint64_t)(uintptr_t)&native_m5_text_0;
  (void)native_s_1;
  native_s_2 = native_m5_fn_0((native_arena *)native_s_0, capability, native_s_1, native_v_0);
  native_s_3 = (native_s_2 == native_v_0);
  if (native_s_3) {
    goto native_l1_1;
  } else {
    goto native_l1_2;
  }
native_l1_1: ;
  return native_v_0;
native_l1_2: ;
  native_s_4 = INT64_C(-1);
  (void)native_s_4;
  return native_s_4;
}
