/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

struct native_m0_text_0_blob { uint64_t length; uint8_t bytes[sizeof "epoch"]; };
static const struct native_m0_text_0_blob native_m0_text_0 = { (uint64_t)(sizeof "epoch" - 1U), "epoch" };
_Static_assert(offsetof(struct native_m0_text_0_blob, bytes) == 8, "text blob is length-prefixed");

native_m0_type_1 native_m0_fn_0(native_arena *arena, const native_capability *capability, native_m0_type_1 native_v_0) {
  (void)arena;
  (void)capability;
  (void)native_v_0;
  native_arena native_epoch_0;
  native_m0_type_0 native_s_0;
  native_m0_type_0 native_s_1;
  native_m0_type_3 native_s_2;
  native_m0_type_3 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_2 native_s_6;
  native_m0_type_0 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_0 native_s_9;
  native_s_0 = arena;
  (void)native_s_0;
  (void)native_arena_init_growable(&native_epoch_0, (size_t)0U);
  native_s_1 = &native_epoch_0;
  (void)native_s_1;
  native_s_2 = (uint64_t)(uintptr_t)&native_m0_text_0;
  (void)native_s_2;
  {
    const uint64_t native_parts_3[2] = { native_s_2, native_s_2 };
    native_s_3 = native_text_concat((native_arena *)native_s_1, native_parts_3, UINT64_C(2));
  }
  native_s_4 = (int64_t)native_text_length(native_s_3);
  native_s_5 = INT64_C(10);
  (void)native_s_5;
  native_s_6 = (native_s_4 == native_s_5);
  if (native_s_6) {
    goto native_l0_1;
  } else {
    goto native_l0_2;
  }
native_l0_1: ;
  native_arena_destroy((native_arena *)native_s_1);
  native_s_7 = NULL;
  (void)native_s_7;
  return native_v_0;
native_l0_2: ;
  native_s_8 = INT64_C(-1);
  (void)native_s_8;
  native_arena_destroy((native_arena *)native_s_1);
  native_s_9 = NULL;
  (void)native_s_9;
  return native_s_8;
}
