/* Generated by native.fold-c17; do not edit. */
#ifndef NATIVE_MODULE_0_ABI_H
#define NATIVE_MODULE_0_ABI_H

#include "native_shim.h"

typedef int64_t native_m0_type_0;
_Static_assert(sizeof(native_m0_type_0) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_0) == 8, "layout alignment");

typedef struct native_m0_type_1 {
  native_m0_type_0 field_0;
  native_m0_type_0 field_1;
  native_m0_type_0 field_2;
} native_m0_type_1;
_Static_assert(sizeof(native_m0_type_1) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_1) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_1, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_1, field_1) == 8, "field offset");
_Static_assert(offsetof(native_m0_type_1, field_2) == 16, "field offset");

typedef bool native_m0_type_2;
_Static_assert(sizeof(native_m0_type_2) == 1, "layout size");
_Static_assert(_Alignof(native_m0_type_2) == 1, "layout alignment");

typedef double native_m0_type_3;
_Static_assert(sizeof(native_m0_type_3) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_3) == 8, "layout alignment");

typedef void *native_m0_type_4;
_Static_assert(sizeof(native_m0_type_4) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_4) == 8, "layout alignment");

typedef struct native_m0_type_5 {
  native_m0_type_0 field_0;
  native_m0_type_0 field_1;
} native_m0_type_5;
_Static_assert(sizeof(native_m0_type_5) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_5) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_5, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_5, field_1) == 8, "field offset");

typedef void *native_m0_type_6;
_Static_assert(sizeof(native_m0_type_6) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_6) == 8, "layout alignment");

typedef struct native_m0_type_7 {
  native_m0_type_0 field_0;
  native_m0_type_0 field_1;
  native_m0_type_6 field_2;
  native_m0_type_0 field_3;
} native_m0_type_7;
_Static_assert(sizeof(native_m0_type_7) == 32, "layout size");
_Static_assert(_Alignof(native_m0_type_7) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_7, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_7, field_1) == 8, "field offset");
_Static_assert(offsetof(native_m0_type_7, field_2) == 16, "field offset");
_Static_assert(offsetof(native_m0_type_7, field_3) == 24, "field offset");

typedef uint32_t native_m0_type_8;
_Static_assert(sizeof(native_m0_type_8) == 4, "layout size");
_Static_assert(_Alignof(native_m0_type_8) == 4, "layout alignment");

typedef struct native_m0_type_9 {
  native_m0_type_8 tag;
  union {
    native_m0_type_2 variant_0;
    native_m0_type_0 variant_1;
    native_m0_type_3 variant_2;
    native_m0_type_4 variant_3;
    native_m0_type_6 variant_4;
  } payload;
} native_m0_type_9;
_Static_assert(sizeof(native_m0_type_9) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_9) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_9, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_9, payload) == 8, "union payload offset");

typedef struct native_m0_type_10 {
  native_m0_type_8 tag;
} native_m0_type_10;
_Static_assert(sizeof(native_m0_type_10) == 4, "layout size");
_Static_assert(_Alignof(native_m0_type_10) == 4, "layout alignment");
_Static_assert(offsetof(native_m0_type_10, tag) == 0, "union tag offset");

typedef struct native_m0_type_11 {
  native_m0_type_8 tag;
} native_m0_type_11;
_Static_assert(sizeof(native_m0_type_11) == 4, "layout size");
_Static_assert(_Alignof(native_m0_type_11) == 4, "layout alignment");
_Static_assert(offsetof(native_m0_type_11, tag) == 0, "union tag offset");

typedef struct native_m0_type_12 {
  native_m0_type_9 field_0;
  native_m0_type_9 field_1;
  native_m0_type_9 field_2;
} native_m0_type_12;
_Static_assert(sizeof(native_m0_type_12) == 48, "layout size");
_Static_assert(_Alignof(native_m0_type_12) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_12, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_12, field_1) == 16, "field offset");
_Static_assert(offsetof(native_m0_type_12, field_2) == 32, "field offset");

typedef struct native_m0_type_13 {
  native_m0_type_6 field_0;
  native_m0_type_12 field_1;
} native_m0_type_13;
_Static_assert(sizeof(native_m0_type_13) == 56, "layout size");
_Static_assert(_Alignof(native_m0_type_13) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_13, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_13, field_1) == 8, "field offset");

typedef struct native_m0_type_14 {
  native_m0_type_0 field_0;
  native_m0_type_0 field_1;
  native_m0_type_0 field_2;
} native_m0_type_14;
_Static_assert(sizeof(native_m0_type_14) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_14) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_14, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_14, field_1) == 8, "field offset");
_Static_assert(offsetof(native_m0_type_14, field_2) == 16, "field offset");

/* vector of native_m0_type_0, stride 8 */
typedef struct native_m0_type_15 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_15;
_Static_assert(sizeof(native_m0_type_15) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_15) == 8, "layout alignment");

typedef struct native_m0_type_16 {
  native_m0_type_0 field_0;
  native_m0_type_15 field_1;
} native_m0_type_16;
_Static_assert(sizeof(native_m0_type_16) == 32, "layout size");
_Static_assert(_Alignof(native_m0_type_16) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_16, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_16, field_1) == 8, "field offset");

typedef struct native_m0_type_17 {
  native_m0_type_0 field_0;
  native_m0_type_15 field_1;
} native_m0_type_17;
_Static_assert(sizeof(native_m0_type_17) == 32, "layout size");
_Static_assert(_Alignof(native_m0_type_17) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_17, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_17, field_1) == 8, "field offset");

/* vector of native_m0_type_2, stride 1 */
typedef struct native_m0_type_18 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_18;
_Static_assert(sizeof(native_m0_type_18) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_18) == 8, "layout alignment");

/* vector of native_m0_type_12, stride 48 */
typedef struct native_m0_type_19 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_19;
_Static_assert(sizeof(native_m0_type_19) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_19) == 8, "layout alignment");

/* vector of native_m0_type_39, stride 104 */
typedef struct native_m0_type_20 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_20;
_Static_assert(sizeof(native_m0_type_20) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_20) == 8, "layout alignment");

/* vector of native_m0_type_14, stride 24 */
typedef struct native_m0_type_21 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_21;
_Static_assert(sizeof(native_m0_type_21) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_21) == 8, "layout alignment");

/* vector of native_m0_type_16, stride 32 */
typedef struct native_m0_type_22 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_22;
_Static_assert(sizeof(native_m0_type_22) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_22) == 8, "layout alignment");

/* vector of native_m0_type_17, stride 32 */
typedef struct native_m0_type_23 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_23;
_Static_assert(sizeof(native_m0_type_23) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_23) == 8, "layout alignment");

/* vector of native_m0_type_7, stride 32 */
typedef struct native_m0_type_24 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_24;
_Static_assert(sizeof(native_m0_type_24) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_24) == 8, "layout alignment");

/* vector of native_m0_type_1, stride 24 */
typedef struct native_m0_type_25 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_25;
_Static_assert(sizeof(native_m0_type_25) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_25) == 8, "layout alignment");

typedef struct native_m0_type_26 {
  native_m0_type_0 field_0;
  native_m0_type_4 field_1;
  native_m0_type_0 field_2;
  native_m0_type_20 field_3;
  native_m0_type_21 field_4;
  native_m0_type_25 field_5;
  native_m0_type_24 field_6;
} native_m0_type_26;
_Static_assert(sizeof(native_m0_type_26) == 120, "layout size");
_Static_assert(_Alignof(native_m0_type_26) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_26, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_26, field_1) == 8, "field offset");
_Static_assert(offsetof(native_m0_type_26, field_2) == 16, "field offset");
_Static_assert(offsetof(native_m0_type_26, field_3) == 24, "field offset");
_Static_assert(offsetof(native_m0_type_26, field_4) == 48, "field offset");
_Static_assert(offsetof(native_m0_type_26, field_5) == 72, "field offset");
_Static_assert(offsetof(native_m0_type_26, field_6) == 96, "field offset");

typedef struct native_m0_type_27 {
  native_m0_type_4 field_0;
  native_m0_type_19 field_1;
  native_m0_type_19 field_2;
  native_m0_type_19 field_3;
  native_m0_type_0 field_4;
  native_m0_type_26 field_5;
} native_m0_type_27;
_Static_assert(sizeof(native_m0_type_27) == 208, "layout size");
_Static_assert(_Alignof(native_m0_type_27) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_27, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_27, field_1) == 8, "field offset");
_Static_assert(offsetof(native_m0_type_27, field_2) == 32, "field offset");
_Static_assert(offsetof(native_m0_type_27, field_3) == 56, "field offset");
_Static_assert(offsetof(native_m0_type_27, field_4) == 80, "field offset");
_Static_assert(offsetof(native_m0_type_27, field_5) == 88, "field offset");

typedef struct native_m0_type_28 {
  native_m0_type_4 field_0;
  native_m0_type_0 field_1;
  native_m0_type_20 field_2;
  native_m0_type_21 field_3;
  native_m0_type_25 field_4;
  native_m0_type_24 field_5;
  native_m0_type_18 field_6;
  native_m0_type_15 field_7;
  native_m0_type_23 field_8;
  native_m0_type_22 field_9;
  native_m0_type_22 field_10;
  native_m0_type_22 field_11;
} native_m0_type_28;
_Static_assert(sizeof(native_m0_type_28) == 256, "layout size");
_Static_assert(_Alignof(native_m0_type_28) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_28, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_1) == 8, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_2) == 16, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_3) == 40, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_4) == 64, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_5) == 88, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_6) == 112, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_7) == 136, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_8) == 160, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_9) == 184, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_10) == 208, "field offset");
_Static_assert(offsetof(native_m0_type_28, field_11) == 232, "field offset");

/* vector of native_m0_type_13, stride 56 */
typedef struct native_m0_type_29 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_29;
_Static_assert(sizeof(native_m0_type_29) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_29) == 8, "layout alignment");

typedef struct native_m0_type_30 {
  native_m0_type_0 field_0;
  native_m0_type_29 field_1;
} native_m0_type_30;
_Static_assert(sizeof(native_m0_type_30) == 32, "layout size");
_Static_assert(_Alignof(native_m0_type_30) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_30, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_30, field_1) == 8, "field offset");

/* vector of native_m0_type_30, stride 32 */
typedef struct native_m0_type_31 {
  const void *elements;
  int64_t length;
  int64_t stride;
} native_m0_type_31;
_Static_assert(sizeof(native_m0_type_31) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_31) == 8, "layout alignment");

typedef void *native_m0_type_32;
_Static_assert(sizeof(native_m0_type_32) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_32) == 8, "layout alignment");

typedef struct native_m0_type_33 {
  native_m0_type_8 tag;
  union {
    native_m0_type_0 variant_0;
    native_m0_type_11 variant_1;
  } payload;
} native_m0_type_33;
_Static_assert(sizeof(native_m0_type_33) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_33) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_33, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_33, payload) == 8, "union payload offset");

typedef struct native_m0_type_34 {
  native_m0_type_8 tag;
  union {
    native_m0_type_2 variant_0;
    native_m0_type_11 variant_1;
  } payload;
} native_m0_type_34;
_Static_assert(sizeof(native_m0_type_34) == 8, "layout size");
_Static_assert(_Alignof(native_m0_type_34) == 4, "layout alignment");
_Static_assert(offsetof(native_m0_type_34, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_34, payload) == 4, "union payload offset");

typedef struct native_m0_type_35 {
  native_m0_type_8 tag;
  union {
    native_m0_type_3 variant_0;
    native_m0_type_11 variant_1;
  } payload;
} native_m0_type_35;
_Static_assert(sizeof(native_m0_type_35) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_35) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_35, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_35, payload) == 8, "union payload offset");

typedef struct native_m0_type_36 {
  native_m0_type_8 tag;
  union {
    native_m0_type_4 variant_0;
    native_m0_type_11 variant_1;
  } payload;
} native_m0_type_36;
_Static_assert(sizeof(native_m0_type_36) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_36) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_36, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_36, payload) == 8, "union payload offset");

typedef struct native_m0_type_37 {
  native_m0_type_8 tag;
  union {
    native_m0_type_5 variant_0;
    native_m0_type_11 variant_1;
  } payload;
} native_m0_type_37;
_Static_assert(sizeof(native_m0_type_37) == 24, "layout size");
_Static_assert(_Alignof(native_m0_type_37) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_37, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_37, payload) == 8, "union payload offset");

typedef struct native_m0_type_38 {
  native_m0_type_8 tag;
  union {
    native_m0_type_6 variant_0;
    native_m0_type_11 variant_1;
  } payload;
} native_m0_type_38;
_Static_assert(sizeof(native_m0_type_38) == 16, "layout size");
_Static_assert(_Alignof(native_m0_type_38) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_38, tag) == 0, "union tag offset");
_Static_assert(offsetof(native_m0_type_38, payload) == 8, "union payload offset");

typedef struct native_m0_type_39 {
  native_m0_type_6 field_0;
  native_m0_type_36 field_1;
  native_m0_type_33 field_2;
  native_m0_type_35 field_3;
  native_m0_type_34 field_4;
  native_m0_type_38 field_5;
  native_m0_type_37 field_6;
} native_m0_type_39;
_Static_assert(sizeof(native_m0_type_39) == 104, "layout size");
_Static_assert(_Alignof(native_m0_type_39) == 8, "layout alignment");
_Static_assert(offsetof(native_m0_type_39, field_0) == 0, "field offset");
_Static_assert(offsetof(native_m0_type_39, field_1) == 8, "field offset");
_Static_assert(offsetof(native_m0_type_39, field_2) == 24, "field offset");
_Static_assert(offsetof(native_m0_type_39, field_3) == 40, "field offset");
_Static_assert(offsetof(native_m0_type_39, field_4) == 56, "field offset");
_Static_assert(offsetof(native_m0_type_39, field_5) == 64, "field offset");
_Static_assert(offsetof(native_m0_type_39, field_6) == 80, "field offset");


#endif
