/* Generated by native.body-c17; do not edit. */
#include "module_0.h"

native_m0_type_1 native_m0_fn_0(native_m0_type_1 native_v_0) {
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_s_0 = false;
  native_s_1 = native_v_0;
  native_s_2 = native_s_0;
  goto native_l0_1;
native_l0_1: ;
  if (native_s_2) {
    goto native_l0_2;
  } else {
    goto native_l0_3;
  }
native_l0_2: ;
  native_s_6 = native_s_1;
  goto native_l0_4;
native_l0_3: ;
  native_s_3 = false;
  native_s_4 = (native_s_1 == native_s_3);
  native_s_5 = true;
  native_s_1 = native_s_4;
  native_s_2 = native_s_5;
  goto native_l0_1;
native_l0_4: ;
  return native_s_6;
}
native_m0_type_0 native_m0_fn_1(native_m0_type_0 native_v_0, native_m0_type_0 native_v_1) {
  native_m0_type_1 native_s_0;
  native_m0_type_0 native_s_1;
  native_m0_type_0 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_0 native_s_5;
  native_m0_type_0 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_0 native_s_8;
  native_s_0 = false;
  native_s_1 = native_v_0;
  native_s_2 = native_v_1;
  native_s_3 = native_s_0;
  goto native_l1_1;
native_l1_1: ;
  if (native_s_3) {
    goto native_l1_2;
  } else {
    goto native_l1_3;
  }
native_l1_2: ;
  native_s_8 = native_s_1;
  goto native_l1_4;
native_l1_3: ;
  native_s_4 = true;
  native_s_5 = native_s_2;
  native_s_6 = native_s_1;
  native_s_7 = native_s_4;
  native_s_1 = native_s_5;
  native_s_2 = native_s_6;
  native_s_3 = native_s_7;
  goto native_l1_1;
native_l1_4: ;
  return native_s_8;
}
native_m0_type_1 native_m0_fn_2(native_m0_type_1 native_v_0, native_m0_type_1 native_v_1) {
  native_m0_type_1 native_s_0;
  native_m0_type_1 native_s_1;
  native_m0_type_1 native_s_2;
  native_m0_type_1 native_s_3;
  native_m0_type_1 native_s_4;
  native_m0_type_1 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_1 native_s_8;
  native_m0_type_1 native_s_9;
  native_m0_type_1 native_s_10;
  native_m0_type_1 native_s_11;
  native_s_0 = false;
  native_s_1 = native_v_0;
  native_s_2 = native_s_0;
  goto native_l2_1;
native_l2_1: ;
  if (native_s_2) {
    goto native_l2_2;
  } else {
    goto native_l2_3;
  }
native_l2_2: ;
  native_s_11 = native_s_1;
  goto native_l2_8;
native_l2_3: ;
  native_s_3 = false;
  native_s_4 = native_v_1;
  native_s_5 = native_s_3;
  goto native_l2_4;
native_l2_4: ;
  if (native_s_5) {
    goto native_l2_5;
  } else {
    goto native_l2_6;
  }
native_l2_5: ;
  native_s_9 = native_s_4;
  goto native_l2_7;
native_l2_6: ;
  native_s_6 = false;
  native_s_7 = (native_s_4 == native_s_6);
  native_s_8 = true;
  native_s_4 = native_s_7;
  native_s_5 = native_s_8;
  goto native_l2_4;
native_l2_7: ;
  native_s_10 = true;
  native_s_1 = native_s_9;
  native_s_2 = native_s_10;
  goto native_l2_1;
native_l2_8: ;
  return native_s_11;
}
native_m0_type_2 native_m0_fn_3(native_m0_type_0 native_v_0, native_m0_type_0 native_v_1, native_m0_type_1 native_v_2) {
  native_m0_type_1 native_s_0;
  native_m0_type_0 native_s_1;
  native_m0_type_0 native_s_2;
  native_m0_type_2 native_s_3;
  native_m0_type_0 native_s_4;
  native_m0_type_0 native_s_5;
  native_m0_type_1 native_s_6;
  native_m0_type_1 native_s_7;
  native_m0_type_0 native_s_8;
  native_m0_type_2 native_s_9;
  native_m0_type_2 native_s_10;
  native_m0_type_1 native_s_11;
  native_m0_type_1 native_s_12;
  native_m0_type_1 native_s_13;
  native_m0_type_0 native_s_14;
  native_m0_type_0 native_s_15;
  native_m0_type_1 native_s_16;
  native_m0_type_1 native_s_17;
  native_m0_type_0 native_s_18;
  native_m0_type_2 native_s_19;
  native_m0_type_2 native_s_20;
  native_s_0 = false;
  native_s_1 = INT64_C(0);
  native_s_2 = INT64_C(0);
  native_s_3 = (native_m0_type_2){ .field_0 = native_v_2, .field_1 = native_s_2 };
  native_s_4 = native_v_0;
  native_s_5 = native_v_1;
  native_s_6 = native_v_2;
  native_s_7 = native_s_0;
  native_s_8 = native_s_1;
  native_s_9 = native_s_3;
  goto native_l3_1;
native_l3_1: ;
  if (native_s_7) {
    goto native_l3_2;
  } else {
    goto native_l3_3;
  }
native_l3_2: ;
  native_s_10 = (native_m0_type_2){ .field_0 = native_s_6, .field_1 = native_s_8 };
  native_s_20 = native_s_10;
  goto native_l3_4;
native_l3_3: ;
  native_s_11 = false;
  native_s_12 = (native_s_6 == native_s_11);
  native_s_13 = true;
  native_s_14 = native_s_5;
  native_s_15 = native_s_4;
  native_s_16 = native_s_12;
  native_s_17 = native_s_13;
  native_s_18 = native_s_4;
  native_s_19 = native_s_9;
  native_s_4 = native_s_14;
  native_s_5 = native_s_15;
  native_s_6 = native_s_16;
  native_s_7 = native_s_17;
  native_s_8 = native_s_18;
  native_s_9 = native_s_19;
  goto native_l3_1;
native_l3_4: ;
  return native_s_20;
}
